package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_es extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "hacer clic" }, { "AbstractDocument.addition.textAndMnemonic", "agregación" }, { "AbstractDocument.deletion.textAndMnemonic", "supresión" }, { "AbstractDocument.redo.textAndMnemonic", "Rehacer" }, { "AbstractDocument.styleChange.textAndMnemonic", "cambio de estilo" }, { "AbstractDocument.undo.textAndMnemonic", "Deshacer" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "Rehacer" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "Deshacer" }, { "ColorChooser.cancel.textAndMnemonic", "Cancelar" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alfa" }, { "ColorChooser.cmykBlack.textAndMnemonic", "Negro" }, { "ColorChooser.cmykCyan.textAndMnemonic", "Cian" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" }, { "ColorChooser.cmykYellow.textAndMnemonic", "Amarillo" }, { "ColorChooser.hsl.textAndMnemonic", "HS&L" }, { "ColorChooser.hslHue.textAndMnemonic", "Matiz" }, { "ColorChooser.hslLightness.textAndMnemonic", "Iluminación" }, { "ColorChooser.hslSaturation.textAndMnemonic", "Saturación" }, { "ColorChooser.hslTransparency.textAndMnemonic", "Transparencia" }, 
        { "ColorChooser.hsv.textAndMnemonic", "&HSV" }, { "ColorChooser.hsvHue.textAndMnemonic", "Matiz" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "Saturación" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparencia" }, { "ColorChooser.hsvValue.textAndMnemonic", "Valor" }, { "ColorChooser.ok.textAndMnemonic", "Aceptar" }, { "ColorChooser.preview.textAndMnemonic", "Vista Previa" }, { "ColorChooser.reset.textAndMnemonic", "&Restablecer" }, { "ColorChooser.rgb.textAndMnemonic", "R&GB" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alfa" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "A&zul" }, { "ColorChooser.rgbGreen.textAndMnemonic", "&Verde" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "&Código de Color" }, { "ColorChooser.rgbRed.textAndMnemonic", "Ro&jo" }, { "ColorChooser.sample.textAndMnemonic", "Texto de Ejemplo  Texto de Ejemplo" }, { "ColorChooser.swatches.textAndMnemonic", "Mue&stras" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "Reciente:" }, { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Todos los Archivos" }, { "FileChooser.cancelButton.textAndMnemonic", "Cancelar" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Cuadro de diálogo para abortar el selector de archivos" }, { "FileChooser.directoryDescription.textAndMnemonic", "Directorio" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "Abrir" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Abrir directorio seleccionado" }, { "FileChooser.fileDescription.textAndMnemonic", "Archivo Genérico" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "Detalles de archivos" }, { "FileChooser.filesListAccessibleName", "Lista de archivos" }, 
        { "FileChooser.helpButton.textAndMnemonic", "A&yuda" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "Ayuda del Selector de Archivos" }, { "FileChooser.newFolderError.textAndMnemonic", "Error al crear una nueva carpeta" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "No se ha podido crear la carpeta.\n\nEl sistema no puede encontrar la ruta de acceso especificada." }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "No se ha podido crear la carpeta" }, { "FileChooser.openButton.textAndMnemonic", "Abrir" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "Abrir archivo seleccionado" }, { "FileChooser.openDialogTitle.textAndMnemonic", "Abrir" }, { "FileChooser.other.newFolder", "Nueva Carpeta" }, 
        { "FileChooser.other.newFolder.subsequent", "Nueva Carpeta.{0}" }, { "FileChooser.renameError.textAndMnemonic", "No se puede cambiar el nombre de {0}" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "No se puede cambiar el nombre de {0}: ya existe un archivo con el nombre especificado. Especifique otro nombre de archivo. " }, { "FileChooser.renameErrorTitle.textAndMnemonic", "Error al cambiar el nombre del archivo o carpeta" }, { "FileChooser.saveButton.textAndMnemonic", "Guardar" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "Guardar archivo seleccionado" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "Guardar" }, { "FileChooser.updateButton.textAndMnemonic", "Act&ualizar" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "Actualizar lista de directorios" }, { "FileChooser.win32.newFolder", "Nueva Carpeta" }, 
        { "FileChooser.win32.newFolder.subsequent", "Nueva Carpeta ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "Examinar..." }, { "FormView.resetButton.textAndMnemonic", "Restablecer" }, { "FormView.submitButton.textAndMnemonic", "Enviar Consulta" }, { "InternalFrame.closeButtonToolTip", "Cerrar" }, { "InternalFrame.iconButtonToolTip", "Minimizar" }, { "InternalFrame.maxButtonToolTip", "Maximizar" }, { "InternalFrame.restoreButtonToolTip", "Restaurar" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Cerrar" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "Cerrar" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Convertir en Icono" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Ma&ximizar" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximizar" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Mi&nimizar" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Mover" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Restaurar" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "&Tamaño" }, { "IsindexView.prompt", "En este índice se pueden efectuar búsquedas. Escriba las palabras clave de búsqueda:" }, { "OptionPane.cancelButton.textAndMnemonic", "Cancelar" }, { "OptionPane.inputDialog.titleAndMnemonic", "Entrada" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "Mensaje" }, { "OptionPane.noButton.textAndMnemonic", "&No" }, { "OptionPane.okButton.textAndMnemonic", "Aceptar" }, { "OptionPane.title.textAndMnemonic", "Seleccionar una Opción" }, { "OptionPane.yesButton.textAndMnemonic", "&Sí" }, { "PrintingDialog.abortButton.textAndMnemonic", "&Abortar" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Abortar Impresión" }, { "PrintingDialog.contentAborting.textAndMnemonic", "Abortando la impresión..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "Impresión en curso..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "Página {0} impresa..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "Impresión (Abortando)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "Impresión" }, { "ProgressMonitor.progress.textAndMnemonic", "Progreso..." }, { "SplitPane.leftButton.textAndMnemonic", "botón izquierdo" }, { "SplitPane.rightButton.textAndMnemonic", "botón derecho" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */