package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_de extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "Klicken" }, { "AbstractDocument.addition.textAndMnemonic", "Hinzufügen" }, { "AbstractDocument.deletion.textAndMnemonic", "Löschen" }, { "AbstractDocument.redo.textAndMnemonic", "Wiederherstellen" }, { "AbstractDocument.styleChange.textAndMnemonic", "Formatvorlagenänderung" }, { "AbstractDocument.undo.textAndMnemonic", "Rückgängig" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "Wiederherstellen" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "Rückgängig" }, { "ColorChooser.cancel.textAndMnemonic", "Abbrechen" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alpha" }, { "ColorChooser.cmykBlack.textAndMnemonic", "Schwarz" }, { "ColorChooser.cmykCyan.textAndMnemonic", "Zyan" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" }, { "ColorChooser.cmykYellow.textAndMnemonic", "Gelb" }, { "ColorChooser.hsl.textAndMnemonic", "HS&L" }, { "ColorChooser.hslHue.textAndMnemonic", "Farbton" }, { "ColorChooser.hslLightness.textAndMnemonic", "Helligkeit" }, { "ColorChooser.hslSaturation.textAndMnemonic", "Sättigung" }, { "ColorChooser.hslTransparency.textAndMnemonic", "Transparenz" }, 
        { "ColorChooser.hsv.textAndMnemonic", "&HSV" }, { "ColorChooser.hsvHue.textAndMnemonic", "Farbton" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "Sättigung" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparenz" }, { "ColorChooser.hsvValue.textAndMnemonic", "Wert" }, { "ColorChooser.ok.textAndMnemonic", "OK" }, { "ColorChooser.preview.textAndMnemonic", "Vorschau" }, { "ColorChooser.reset.textAndMnemonic", "&Zurücksetzen" }, { "ColorChooser.rgb.textAndMnemonic", "R&GB" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alpha" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "&Blau" }, { "ColorChooser.rgbGreen.textAndMnemonic", "Grü&n" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "&Farbcode" }, { "ColorChooser.rgbRed.textAndMnemonic", "Ro&t" }, { "ColorChooser.sample.textAndMnemonic", "Beispieltext  Beispieltext" }, { "ColorChooser.swatches.textAndMnemonic", "&Swatches" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "Aktuell:" }, { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Alle Dateien" }, { "FileChooser.cancelButton.textAndMnemonic", "Abbrechen" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Dialogfeld für Dateiauswahl schließen" }, { "FileChooser.directoryDescription.textAndMnemonic", "Verzeichnis" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "Öffnen" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Ausgewähltes Verzeichnis öffnen" }, { "FileChooser.fileDescription.textAndMnemonic", "Allgemeine Datei" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "Dateidetails" }, { "FileChooser.filesListAccessibleName", "Dateiliste" }, 
        { "FileChooser.helpButton.textAndMnemonic", "&Hilfe" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "FileChooser-Hilfe" }, { "FileChooser.newFolderError.textAndMnemonic", "Fehler beim Erstellen eines neuen Ordners" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Ordner kann nicht erstellt werden.\n\nSystem kann den angegebenen Pfad nicht finden." }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Ordner kann nicht erstellt werden" }, { "FileChooser.openButton.textAndMnemonic", "Öffnen" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "Ausgewählte Datei öffnen" }, { "FileChooser.openDialogTitle.textAndMnemonic", "Öffnen" }, { "FileChooser.other.newFolder", "NewFolder" }, 
        { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" }, { "FileChooser.renameError.textAndMnemonic", "{0} kann nicht umbenannt werden" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "{0} kann nicht umbenannt werden: Es ist bereits eine Datei mit dem angegebenen Namen vorhanden. Geben Sie einen anderen Dateinamen an. " }, { "FileChooser.renameErrorTitle.textAndMnemonic", "Fehler beim Umbenennen von Datei oder Ordner" }, { "FileChooser.saveButton.textAndMnemonic", "Speichern" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "Ausgewählte Datei speichern" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "Speichern" }, { "FileChooser.updateButton.textAndMnemonic", "A&ktualisieren" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "Verzeichnisliste aktualisieren" }, { "FileChooser.win32.newFolder", "Neuer Ordner" }, 
        { "FileChooser.win32.newFolder.subsequent", "Neuer Ordner ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "Durchsuchen..." }, { "FormView.resetButton.textAndMnemonic", "Zurücksetzen" }, { "FormView.submitButton.textAndMnemonic", "Abfrage weiterleiten" }, { "InternalFrame.closeButtonToolTip", "Schließen" }, { "InternalFrame.iconButtonToolTip", "Minimieren" }, { "InternalFrame.maxButtonToolTip", "Maximieren" }, { "InternalFrame.restoreButtonToolTip", "Wiederherstellen" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Schließen" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "Schließen" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Als Symbol darstellen" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Ma&ximieren" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximieren" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Mi&nimieren" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Verschieben" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Wiederherstellen" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "&Größe" }, { "IsindexView.prompt", "Dieser Index kann durchsucht werden. Geben Sie Schlüsselwörter für die Suche ein:" }, { "OptionPane.cancelButton.textAndMnemonic", "Abbrechen" }, { "OptionPane.inputDialog.titleAndMnemonic", "Eingabe" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "Meldung" }, { "OptionPane.noButton.textAndMnemonic", "&Nein" }, { "OptionPane.okButton.textAndMnemonic", "OK" }, { "OptionPane.title.textAndMnemonic", "Option auswählen" }, { "OptionPane.yesButton.textAndMnemonic", "&Ja" }, { "PrintingDialog.abortButton.textAndMnemonic", "&Abbruch" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Druckvorgang abbrechen" }, { "PrintingDialog.contentAborting.textAndMnemonic", "Druckvorgang wird abgebrochen..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "Druckvorgang läuft..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "Seite {0} wurde gedruckt..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "Drucken (Abbruch)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "Drucken" }, { "ProgressMonitor.progress.textAndMnemonic", "Fortschritt..." }, { "SplitPane.leftButton.textAndMnemonic", "linke Schaltfläche" }, { "SplitPane.rightButton.textAndMnemonic", "rechte Schaltfläche" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_de.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */