package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_fr extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "cliquer" }, { "AbstractDocument.addition.textAndMnemonic", "ajout" }, { "AbstractDocument.deletion.textAndMnemonic", "suppression" }, { "AbstractDocument.redo.textAndMnemonic", "Rétablir" }, { "AbstractDocument.styleChange.textAndMnemonic", "modification de style" }, { "AbstractDocument.undo.textAndMnemonic", "Annuler" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "Rétablir" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "Annuler" }, { "ColorChooser.cancel.textAndMnemonic", "Annuler" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alpha" }, { "ColorChooser.cmykBlack.textAndMnemonic", "Noir" }, { "ColorChooser.cmykCyan.textAndMnemonic", "Cyan" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" }, { "ColorChooser.cmykYellow.textAndMnemonic", "Jaune" }, { "ColorChooser.hsl.textAndMnemonic", "TS&L" }, { "ColorChooser.hslHue.textAndMnemonic", "Teinte" }, { "ColorChooser.hslLightness.textAndMnemonic", "Lumière" }, { "ColorChooser.hslSaturation.textAndMnemonic", "Saturation" }, { "ColorChooser.hslTransparency.textAndMnemonic", "Transparence" }, 
        { "ColorChooser.hsv.textAndMnemonic", "&TSV" }, { "ColorChooser.hsvHue.textAndMnemonic", "Teinte" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "Saturation" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparence" }, { "ColorChooser.hsvValue.textAndMnemonic", "Valeur" }, { "ColorChooser.ok.textAndMnemonic", "OK" }, { "ColorChooser.preview.textAndMnemonic", "Aperçu" }, { "ColorChooser.reset.textAndMnemonic", "&Réinitialiser" }, { "ColorChooser.rgb.textAndMnemonic", "R&VB" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alpha" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "&Bleu" }, { "ColorChooser.rgbGreen.textAndMnemonic", "&Vert" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "&Code couleur" }, { "ColorChooser.rgbRed.textAndMnemonic", "R&ouge" }, { "ColorChooser.sample.textAndMnemonic", "Echantillon de texte  Echantillon de texte" }, { "ColorChooser.swatches.textAndMnemonic", "&Echantillons" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "Dernier :" }, { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Tous les fichiers" }, { "FileChooser.cancelButton.textAndMnemonic", "Annuler" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Ferme la boîte de dialogue du sélecteur de fichiers" }, { "FileChooser.directoryDescription.textAndMnemonic", "Répertoire" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "Ouvrir" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Ouvre le répertoire sélectionné" }, { "FileChooser.fileDescription.textAndMnemonic", "Fichier générique" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "Détails des fichiers" }, { "FileChooser.filesListAccessibleName", "Liste des fichiers" }, 
        { "FileChooser.helpButton.textAndMnemonic", "&Aide" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "Aide du sélecteur de fichiers" }, { "FileChooser.newFolderError.textAndMnemonic", "Erreur lors de la création du dossier" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Impossible de créer le dossier.\n\nLe système ne parvient pas à trouver le chemin indiqué." }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Impossible de créer le dossier" }, { "FileChooser.openButton.textAndMnemonic", "Ouvrir" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "Ouvre le fichier sélectionné" }, { "FileChooser.openDialogTitle.textAndMnemonic", "Ouvrir" }, { "FileChooser.other.newFolder", "NewFolder" }, 
        { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" }, { "FileChooser.renameError.textAndMnemonic", "Impossible de renommer {0}" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "Impossible de renommer {0} : il existe déjà un fichier portant le nom indiqué. Indiquez-en un autre. " }, { "FileChooser.renameErrorTitle.textAndMnemonic", "Erreur lors du changement de nom du fichier ou du dossier" }, { "FileChooser.saveButton.textAndMnemonic", "Enregistrer" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "Enregistre le fichier sélectionné" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "Enregistrer" }, { "FileChooser.updateButton.textAndMnemonic", "Mettre à jo&ur" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "Met à jour la liste des répertoires" }, { "FileChooser.win32.newFolder", "Nouveau dossier" }, 
        { "FileChooser.win32.newFolder.subsequent", "Nouveau dossier ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "Parcourir..." }, { "FormView.resetButton.textAndMnemonic", "Réinitialiser" }, { "FormView.submitButton.textAndMnemonic", "Soumettre la requête" }, { "InternalFrame.closeButtonToolTip", "Fermer" }, { "InternalFrame.iconButtonToolTip", "Réduire" }, { "InternalFrame.maxButtonToolTip", "Agrandir" }, { "InternalFrame.restoreButtonToolTip", "Restaurer" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Fermer" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "Fermer" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Réduire" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "&Agrandir" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Agrandir" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "&Réduire" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "Dép&lacer" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Restaurer" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "Re&dimensionner" }, { "IsindexView.prompt", "Ceci est un index de recherche. Tapez des mots-clés pour la recherche :" }, { "OptionPane.cancelButton.textAndMnemonic", "Annuler" }, { "OptionPane.inputDialog.titleAndMnemonic", "Entrée" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "Message" }, { "OptionPane.noButton.textAndMnemonic", "&Non" }, { "OptionPane.okButton.textAndMnemonic", "OK" }, { "OptionPane.title.textAndMnemonic", "Sélectionner une option" }, { "OptionPane.yesButton.textAndMnemonic", "&Oui" }, { "PrintingDialog.abortButton.textAndMnemonic", "&Abandonner" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Abandonner l'impression" }, { "PrintingDialog.contentAborting.textAndMnemonic", "Abandon de l'impression..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "Impression en cours..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "Page {0} imprimée..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "Impression (abandon)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "Impression" }, { "ProgressMonitor.progress.textAndMnemonic", "Progression..." }, { "SplitPane.leftButton.textAndMnemonic", "bouton gauche" }, { "SplitPane.rightButton.textAndMnemonic", "bouton droit" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_fr.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */