package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_zh_CN extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "单击" }, { "AbstractDocument.addition.textAndMnemonic", "添加" }, { "AbstractDocument.deletion.textAndMnemonic", "删除" }, { "AbstractDocument.redo.textAndMnemonic", "重做" }, { "AbstractDocument.styleChange.textAndMnemonic", "样式更改" }, { "AbstractDocument.undo.textAndMnemonic", "撤消" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "重做" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "撤消" }, { "ColorChooser.cancel.textAndMnemonic", "取消" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alpha" }, { "ColorChooser.cmykBlack.textAndMnemonic", "黑色" }, { "ColorChooser.cmykCyan.textAndMnemonic", "青色" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "紫红色" }, { "ColorChooser.cmykYellow.textAndMnemonic", "黄色" }, { "ColorChooser.hsl.textAndMnemonic", "HSL(&L)" }, { "ColorChooser.hslHue.textAndMnemonic", "色调" }, { "ColorChooser.hslLightness.textAndMnemonic", "亮度" }, { "ColorChooser.hslSaturation.textAndMnemonic", "饱和度" }, { "ColorChooser.hslTransparency.textAndMnemonic", "透明度" }, 
        { "ColorChooser.hsv.textAndMnemonic", "HSV(&H)" }, { "ColorChooser.hsvHue.textAndMnemonic", "色调" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "饱和度" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "透明度" }, { "ColorChooser.hsvValue.textAndMnemonic", "值" }, { "ColorChooser.ok.textAndMnemonic", "确定" }, { "ColorChooser.preview.textAndMnemonic", "预览" }, { "ColorChooser.reset.textAndMnemonic", "重置(&R)" }, { "ColorChooser.rgb.textAndMnemonic", "RGB(&G)" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alpha" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "蓝色(&B)" }, { "ColorChooser.rgbGreen.textAndMnemonic", "绿色(&N)" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "颜色代码(&C)" }, { "ColorChooser.rgbRed.textAndMnemonic", "红色(&D)" }, { "ColorChooser.sample.textAndMnemonic", "示例文本  示例文本" }, { "ColorChooser.swatches.textAndMnemonic", "样本(&S)" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "最近:" }, { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "所有文件" }, { "FileChooser.cancelButton.textAndMnemonic", "取消" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "中止文件选择器对话框" }, { "FileChooser.directoryDescription.textAndMnemonic", "目录" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "打开" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "打开选择的目录" }, { "FileChooser.fileDescription.textAndMnemonic", "通用文件" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "文件详细信息" }, { "FileChooser.filesListAccessibleName", "文件列表" }, 
        { "FileChooser.helpButton.textAndMnemonic", "帮助(&H)" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "FileChooser 帮助" }, { "FileChooser.newFolderError.textAndMnemonic", "创建新的文件夹时出错" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "无法创建文件夹。\n\n系统找不到指定的路径。" }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "无法创建文件夹" }, { "FileChooser.openButton.textAndMnemonic", "打开" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "打开所选文件" }, { "FileChooser.openDialogTitle.textAndMnemonic", "打开" }, { "FileChooser.other.newFolder", "NewFolder" }, 
        { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" }, { "FileChooser.renameError.textAndMnemonic", "无法重命名{0}" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "无法重命名{0}: 已存在具有所指定名称的文件。请指定其他文件名。" }, { "FileChooser.renameErrorTitle.textAndMnemonic", "重命名文件或文件夹时出错" }, { "FileChooser.saveButton.textAndMnemonic", "保存" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "保存所选文件" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "保存" }, { "FileChooser.updateButton.textAndMnemonic", "更新(&U)" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "更新目录列表" }, { "FileChooser.win32.newFolder", "新建文件夹" }, 
        { "FileChooser.win32.newFolder.subsequent", "新建文件夹 ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "浏览..." }, { "FormView.resetButton.textAndMnemonic", "重置" }, { "FormView.submitButton.textAndMnemonic", "提交查询" }, { "InternalFrame.closeButtonToolTip", "关闭" }, { "InternalFrame.iconButtonToolTip", "最小化" }, { "InternalFrame.maxButtonToolTip", "最大化" }, { "InternalFrame.restoreButtonToolTip", "还原" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "关闭(&C)" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "关闭" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "图标化" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "最大化(&X)" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "最大化" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "最小化(&N)" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "移动(&M)" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "还原(&R)" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "大小(&S)" }, { "IsindexView.prompt", "这是可搜索索引。请输入搜索关键字: " }, { "OptionPane.cancelButton.textAndMnemonic", "取消" }, { "OptionPane.inputDialog.titleAndMnemonic", "输入" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "消息" }, { "OptionPane.noButton.textAndMnemonic", "否(&N)" }, { "OptionPane.okButton.textAndMnemonic", "确定" }, { "OptionPane.title.textAndMnemonic", "选择一个选项" }, { "OptionPane.yesButton.textAndMnemonic", "是(&Y)" }, { "PrintingDialog.abortButton.textAndMnemonic", "中止(&A)" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "中止打印" }, { "PrintingDialog.contentAborting.textAndMnemonic", "正在中止打印..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "正在进行打印..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "已打印页 {0}..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "打印 (正在中止)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "打印" }, { "ProgressMonitor.progress.textAndMnemonic", "进度..." }, { "SplitPane.leftButton.textAndMnemonic", "左键" }, { "SplitPane.rightButton.textAndMnemonic", "右键" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_zh_CN.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */