package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_pt_BR extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "clicar" }, { "AbstractDocument.addition.textAndMnemonic", "adição" }, { "AbstractDocument.deletion.textAndMnemonic", "exclusão" }, { "AbstractDocument.redo.textAndMnemonic", "Refazer" }, { "AbstractDocument.styleChange.textAndMnemonic", "alteração de estilo" }, { "AbstractDocument.undo.textAndMnemonic", "Desfazer" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "Refazer" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "Desfazer" }, { "ColorChooser.cancel.textAndMnemonic", "Cancelar" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alfa" }, { "ColorChooser.cmykBlack.textAndMnemonic", "Preto" }, { "ColorChooser.cmykCyan.textAndMnemonic", "Ciano" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" }, { "ColorChooser.cmykYellow.textAndMnemonic", "Amarelo" }, { "ColorChooser.hsl.textAndMnemonic", "HS&L" }, { "ColorChooser.hslHue.textAndMnemonic", "Matiz" }, { "ColorChooser.hslLightness.textAndMnemonic", "Clareza" }, { "ColorChooser.hslSaturation.textAndMnemonic", "Saturação" }, { "ColorChooser.hslTransparency.textAndMnemonic", "Transparência" }, 
        { "ColorChooser.hsv.textAndMnemonic", "&HSV" }, { "ColorChooser.hsvHue.textAndMnemonic", "Matiz" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "Saturação" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparência" }, { "ColorChooser.hsvValue.textAndMnemonic", "Valor" }, { "ColorChooser.ok.textAndMnemonic", "OK" }, { "ColorChooser.preview.textAndMnemonic", "Visualizar" }, { "ColorChooser.reset.textAndMnemonic", "&Redefinir" }, { "ColorChooser.rgb.textAndMnemonic", "R&GB" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alfa" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "&Azul" }, { "ColorChooser.rgbGreen.textAndMnemonic", "&Verde" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "&Código da Cor" }, { "ColorChooser.rgbRed.textAndMnemonic", "&Vermelho" }, { "ColorChooser.sample.textAndMnemonic", "Texto de Amostra Texto de Amostra" }, { "ColorChooser.swatches.textAndMnemonic", "Amo&stras" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "Recente:" }, { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Todos os Arquivos" }, { "FileChooser.cancelButton.textAndMnemonic", "Cancelar" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Abortar caixa de diálogo do seletor de arquivos" }, { "FileChooser.directoryDescription.textAndMnemonic", "Diretório" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "Abrir" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Abrir diretório selecionado" }, { "FileChooser.fileDescription.textAndMnemonic", "Arquivo Genérico" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "Detalhes do Arquivo" }, { "FileChooser.filesListAccessibleName", "Lista de Arquivos" }, 
        { "FileChooser.helpButton.textAndMnemonic", "Aj&uda" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "Ajuda do FileChooser" }, { "FileChooser.newFolderError.textAndMnemonic", "Erro ao criar nova pasta" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Não é possível criar a pasta.\n\nO sistema não pode localizar o caminho especificado." }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Não é possível criar a pasta" }, { "FileChooser.openButton.textAndMnemonic", "Abrir" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "Abrir arquivo selecionado" }, { "FileChooser.openDialogTitle.textAndMnemonic", "Abrir" }, { "FileChooser.other.newFolder", "NewFolder" }, 
        { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" }, { "FileChooser.renameError.textAndMnemonic", "Não é possível renomear {0}" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "Não é possível renomear {0}: Um arquivo com o nome especificado já existe. Especifique outro nome de arquivo." }, { "FileChooser.renameErrorTitle.textAndMnemonic", "Erro ao Renomear o Arquivo ou a Pasta" }, { "FileChooser.saveButton.textAndMnemonic", "Salvar" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "Salvar arquivo selecionado" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "Salvar" }, { "FileChooser.updateButton.textAndMnemonic", "At&ualizar" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "Atualizar lista de diretórios" }, { "FileChooser.win32.newFolder", "Nova Pasta" }, 
        { "FileChooser.win32.newFolder.subsequent", "Nova Pasta ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "Procurar..." }, { "FormView.resetButton.textAndMnemonic", "Redefinir" }, { "FormView.submitButton.textAndMnemonic", "Submeter Consulta" }, { "InternalFrame.closeButtonToolTip", "Fechar" }, { "InternalFrame.iconButtonToolTip", "Minimizar" }, { "InternalFrame.maxButtonToolTip", "Maximizar" }, { "InternalFrame.restoreButtonToolTip", "Restaurar" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Fechar" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "Fechar" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Iconizar" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Ma&ximizar" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximizar" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Mi&nimizar" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Mover" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Restaurar" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "&Dimensionar" }, { "IsindexView.prompt", "Trata-se de um índice pesquisável. Informe as palavras-chave de pesquisa:" }, { "OptionPane.cancelButton.textAndMnemonic", "Cancelar" }, { "OptionPane.inputDialog.titleAndMnemonic", "Entrada" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "Mensagem" }, { "OptionPane.noButton.textAndMnemonic", "&Não" }, { "OptionPane.okButton.textAndMnemonic", "OK" }, { "OptionPane.title.textAndMnemonic", "Selecionar uma Opção" }, { "OptionPane.yesButton.textAndMnemonic", "&Sim" }, { "PrintingDialog.abortButton.textAndMnemonic", "&Abortar" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Abortar Impressão" }, { "PrintingDialog.contentAborting.textAndMnemonic", "Abortando impressão..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "Impressão em andamento..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "Página impressa {0}..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "Impressão (Abortando)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "Impressão" }, { "ProgressMonitor.progress.textAndMnemonic", "Andamento..." }, { "SplitPane.leftButton.textAndMnemonic", "botão esquerdo" }, { "SplitPane.rightButton.textAndMnemonic", "botão direito" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */