package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_zh_TW extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "按一下" }, { "AbstractDocument.addition.textAndMnemonic", "附加" }, { "AbstractDocument.deletion.textAndMnemonic", "刪除" }, { "AbstractDocument.redo.textAndMnemonic", "重做" }, { "AbstractDocument.styleChange.textAndMnemonic", "樣式變更" }, { "AbstractDocument.undo.textAndMnemonic", "還原" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "重做" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "還原" }, { "ColorChooser.cancel.textAndMnemonic", "取消" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alpha" }, { "ColorChooser.cmykBlack.textAndMnemonic", "黑色" }, { "ColorChooser.cmykCyan.textAndMnemonic", "藍綠色" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "紫紅色" }, { "ColorChooser.cmykYellow.textAndMnemonic", "黃色" }, { "ColorChooser.hsl.textAndMnemonic", "HSL(&L)" }, { "ColorChooser.hslHue.textAndMnemonic", "色調" }, { "ColorChooser.hslLightness.textAndMnemonic", "亮度" }, { "ColorChooser.hslSaturation.textAndMnemonic", "彩度" }, { "ColorChooser.hslTransparency.textAndMnemonic", "透明度" }, 
        { "ColorChooser.hsv.textAndMnemonic", "HSV(&H)" }, { "ColorChooser.hsvHue.textAndMnemonic", "色調" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "彩度" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "透明度" }, { "ColorChooser.hsvValue.textAndMnemonic", "數值" }, { "ColorChooser.ok.textAndMnemonic", "確定" }, { "ColorChooser.preview.textAndMnemonic", "預覽" }, { "ColorChooser.reset.textAndMnemonic", "重設(&R)" }, { "ColorChooser.rgb.textAndMnemonic", "RGB(&G)" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alpha" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "藍(&B)" }, { "ColorChooser.rgbGreen.textAndMnemonic", "綠(&N)" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "顏色代碼(&C)" }, { "ColorChooser.rgbRed.textAndMnemonic", "紅(&D)" }, { "ColorChooser.sample.textAndMnemonic", "範例文字  範例文字" }, { "ColorChooser.swatches.textAndMnemonic", "調色板(&S)" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "最新選擇:" }, { "ComboBox.togglePopup.textAndMnemonic", "切換即現式視窗" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "所有檔案" }, { "FileChooser.cancelButton.textAndMnemonic", "取消" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "中止檔案選擇器對話方塊" }, { "FileChooser.directoryDescription.textAndMnemonic", "目錄" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "開啟" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "開啟選取的目錄" }, { "FileChooser.fileDescription.textAndMnemonic", "一般檔案" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "檔案詳細資訊" }, { "FileChooser.filesListAccessibleName", "檔案清單" }, 
        { "FileChooser.helpButton.textAndMnemonic", "說明(&H)" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "「檔案選擇器」說明" }, { "FileChooser.newFolderError.textAndMnemonic", "建立新資料夾時發生錯誤" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "無法建立資料夾。\n\n系統找不到指定的路徑。" }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "無法建立資料夾" }, { "FileChooser.openButton.textAndMnemonic", "開啟" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "開啟選取的檔案" }, { "FileChooser.openDialogTitle.textAndMnemonic", "開啟" }, { "FileChooser.other.newFolder", "新資料夾" }, 
        { "FileChooser.other.newFolder.subsequent", "新資料夾.{0}" }, { "FileChooser.renameError.textAndMnemonic", "無法重新命名 {0}" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "無法重新命名 {0}: 已經存在您所指定名稱的檔案。請指定不同的名稱。" }, { "FileChooser.renameErrorTitle.textAndMnemonic", "重新命名檔案或資料夾時發生錯誤。" }, { "FileChooser.saveButton.textAndMnemonic", "儲存" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "儲存選取的檔案" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "儲存" }, { "FileChooser.updateButton.textAndMnemonic", "更新(&U)" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "更新目錄清單" }, { "FileChooser.win32.newFolder", "新資料夾" }, 
        { "FileChooser.win32.newFolder.subsequent", "新資料夾 ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "瀏覽..." }, { "FormView.resetButton.textAndMnemonic", "重設" }, { "FormView.submitButton.textAndMnemonic", "送出查詢" }, { "InternalFrame.closeButtonToolTip", "關閉" }, { "InternalFrame.iconButtonToolTip", "最小化" }, { "InternalFrame.maxButtonToolTip", "最大化" }, { "InternalFrame.restoreButtonToolTip", "復原" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "關閉(&C)" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "關閉" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "圖示化" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "最大化(&X)" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "最大化" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "最小化(&N)" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "移動(&M)" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "回復(&R)" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "調整大小(&S)" }, { "IsindexView.prompt", "這是一個可搜尋的索引。輸入搜尋關鍵字: " }, { "OptionPane.cancelButton.textAndMnemonic", "取消" }, { "OptionPane.inputDialog.titleAndMnemonic", "輸入" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "訊息" }, { "OptionPane.noButton.textAndMnemonic", "否(&N)" }, { "OptionPane.okButton.textAndMnemonic", "確定" }, { "OptionPane.title.textAndMnemonic", "選取一個選項" }, { "OptionPane.yesButton.textAndMnemonic", "是(&Y)" }, { "PrintingDialog.abortButton.textAndMnemonic", "中止(&A)" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "中止列印" }, { "PrintingDialog.contentAborting.textAndMnemonic", "正在中止列印..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "正在列印..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "已列印的頁面 {0}..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "列印 (中止)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "列印" }, { "ProgressMonitor.progress.textAndMnemonic", "進度..." }, { "SplitPane.leftButton.textAndMnemonic", "左按鈕" }, { "SplitPane.rightButton.textAndMnemonic", "右按鈕" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_zh_TW.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */