package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_sv extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "klicka" }, { "AbstractDocument.addition.textAndMnemonic", "tillägg" }, { "AbstractDocument.deletion.textAndMnemonic", "borttagning" }, { "AbstractDocument.redo.textAndMnemonic", "Gör om" }, { "AbstractDocument.styleChange.textAndMnemonic", "formatändring" }, { "AbstractDocument.undo.textAndMnemonic", "Ångra" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "Gör om" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "Ångra" }, { "ColorChooser.cancel.textAndMnemonic", "Avbryt" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "Alfa" }, { "ColorChooser.cmykBlack.textAndMnemonic", "Svart" }, { "ColorChooser.cmykCyan.textAndMnemonic", "Cyan" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "Magenta" }, { "ColorChooser.cmykYellow.textAndMnemonic", "Gul" }, { "ColorChooser.hsl.textAndMnemonic", "HS&L" }, { "ColorChooser.hslHue.textAndMnemonic", "Nyans" }, { "ColorChooser.hslLightness.textAndMnemonic", "Ljusstyrka" }, { "ColorChooser.hslSaturation.textAndMnemonic", "Mättnad" }, { "ColorChooser.hslTransparency.textAndMnemonic", "Transparens" }, 
        { "ColorChooser.hsv.textAndMnemonic", "&HSV" }, { "ColorChooser.hsvHue.textAndMnemonic", "Nyans" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "Mättnad" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "Transparens" }, { "ColorChooser.hsvValue.textAndMnemonic", "Värde" }, { "ColorChooser.ok.textAndMnemonic", "OK" }, { "ColorChooser.preview.textAndMnemonic", "Granska" }, { "ColorChooser.reset.textAndMnemonic", "&Återställ" }, { "ColorChooser.rgb.textAndMnemonic", "R&GB" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "Alfa" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "&Blå" }, { "ColorChooser.rgbGreen.textAndMnemonic", "Grö&n" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "&Färgkod" }, { "ColorChooser.rgbRed.textAndMnemonic", "Rö&d" }, { "ColorChooser.sample.textAndMnemonic", "Exempeltext  Exempeltext" }, { "ColorChooser.swatches.textAndMnemonic", "&Prov" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "Senaste:" }, { "ComboBox.togglePopup.textAndMnemonic", "växlaPopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Alla filer" }, { "FileChooser.cancelButton.textAndMnemonic", "Avbryt" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "Avbryt dialogrutan för filval" }, { "FileChooser.directoryDescription.textAndMnemonic", "Katalog" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "Öppna" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "Öppna vald katalog" }, { "FileChooser.fileDescription.textAndMnemonic", "Generisk fil" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "Fildetaljer" }, { "FileChooser.filesListAccessibleName", "Fillista" }, 
        { "FileChooser.helpButton.textAndMnemonic", "&Hjälp" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "Hjälp för val av fil" }, { "FileChooser.newFolderError.textAndMnemonic", "Kan inte skapa ny mapp" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "Kan inte skapa mappen.\n\nSystemet kan inte hitta angiven sökväg." }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "Kan inte skapa mappen" }, { "FileChooser.openButton.textAndMnemonic", "Öppna" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "Öppna vald fil" }, { "FileChooser.openDialogTitle.textAndMnemonic", "Öppna" }, { "FileChooser.other.newFolder", "Ny mapp" }, 
        { "FileChooser.other.newFolder.subsequent", "Ny mapp {0}" }, { "FileChooser.renameError.textAndMnemonic", "Kan inte namnändra {0}" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "Kan inte namnändra {0}: En fil med angivet namn finns redan. Ange ett annat filnamn. " }, { "FileChooser.renameErrorTitle.textAndMnemonic", "Ett fel inträffade vid försök att ändra namn på fil eller mapp" }, { "FileChooser.saveButton.textAndMnemonic", "Spara" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "Spara vald fil" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "Spara" }, { "FileChooser.updateButton.textAndMnemonic", "Upp&datera" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "Uppdatera kataloglista" }, { "FileChooser.win32.newFolder", "Ny mapp" }, 
        { "FileChooser.win32.newFolder.subsequent", "Ny mapp ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "Bläddra..." }, { "FormView.resetButton.textAndMnemonic", "Återställ" }, { "FormView.submitButton.textAndMnemonic", "Skicka fråga" }, { "InternalFrame.closeButtonToolTip", "Stäng" }, { "InternalFrame.iconButtonToolTip", "Minimera" }, { "InternalFrame.maxButtonToolTip", "Maximera" }, { "InternalFrame.restoreButtonToolTip", "Återställ" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "&Stäng" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "Stäng" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Minimera" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Ma&ximera" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximera" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Mi&nimera" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "&Flytta" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "&Återställ" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "&Storlek" }, { "IsindexView.prompt", "Detta är ett sökbart index. Ange sökord:" }, { "OptionPane.cancelButton.textAndMnemonic", "Avbryt" }, { "OptionPane.inputDialog.titleAndMnemonic", "Indata" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "Meddelande" }, { "OptionPane.noButton.textAndMnemonic", "&Nej" }, { "OptionPane.okButton.textAndMnemonic", "OK" }, { "OptionPane.title.textAndMnemonic", "Välj ett alternativ" }, { "OptionPane.yesButton.textAndMnemonic", "&Ja" }, { "PrintingDialog.abortButton.textAndMnemonic", "&Avbryt" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Avbryt utskrift" }, { "PrintingDialog.contentAborting.textAndMnemonic", "Utskriften avbryts..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "Utskrift pågår..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "Skriver ut sida {0}..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "Skriver ut (avbryter)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "Skriver ut" }, { "ProgressMonitor.progress.textAndMnemonic", "Pågår..." }, { "SplitPane.leftButton.textAndMnemonic", "vänsterknapp" }, { "SplitPane.rightButton.textAndMnemonic", "högerknapp" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_sv.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */