package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_ko extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "누르기" }, { "AbstractDocument.addition.textAndMnemonic", "추가" }, { "AbstractDocument.deletion.textAndMnemonic", "삭제" }, { "AbstractDocument.redo.textAndMnemonic", "재실행" }, { "AbstractDocument.styleChange.textAndMnemonic", "스타일 변경" }, { "AbstractDocument.undo.textAndMnemonic", "실행 취소" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "재실행" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "실행 취소" }, { "ColorChooser.cancel.textAndMnemonic", "취소" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "알파" }, { "ColorChooser.cmykBlack.textAndMnemonic", "검정색" }, { "ColorChooser.cmykCyan.textAndMnemonic", "청록색" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "진홍색" }, { "ColorChooser.cmykYellow.textAndMnemonic", "노란색" }, { "ColorChooser.hsl.textAndMnemonic", "HSL(&L)" }, { "ColorChooser.hslHue.textAndMnemonic", "색조" }, { "ColorChooser.hslLightness.textAndMnemonic", "밝기" }, { "ColorChooser.hslSaturation.textAndMnemonic", "채도" }, { "ColorChooser.hslTransparency.textAndMnemonic", "투명" }, 
        { "ColorChooser.hsv.textAndMnemonic", "HSV(&H)" }, { "ColorChooser.hsvHue.textAndMnemonic", "색조" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "채도" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "투명" }, { "ColorChooser.hsvValue.textAndMnemonic", "값" }, { "ColorChooser.ok.textAndMnemonic", "확인" }, { "ColorChooser.preview.textAndMnemonic", "미리보기" }, { "ColorChooser.reset.textAndMnemonic", "재설정(&R)" }, { "ColorChooser.rgb.textAndMnemonic", "RGB(&G)" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "알파" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "파란색(&B)" }, { "ColorChooser.rgbGreen.textAndMnemonic", "녹색(&N)" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "색상 코드(&C)" }, { "ColorChooser.rgbRed.textAndMnemonic", "빨간색(&D)" }, { "ColorChooser.sample.textAndMnemonic", "샘플 텍스트  샘플 텍스트" }, { "ColorChooser.swatches.textAndMnemonic", "견본(&S)" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "최근 목록:" }, { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "모든 파일" }, { "FileChooser.cancelButton.textAndMnemonic", "취소" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "파일 선택기 대화상자 중단" }, { "FileChooser.directoryDescription.textAndMnemonic", "디렉토리" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "열기" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "선택된 디렉토리 열기" }, { "FileChooser.fileDescription.textAndMnemonic", "일반 파일" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "파일 세부정보" }, { "FileChooser.filesListAccessibleName", "파일 목록" }, 
        { "FileChooser.helpButton.textAndMnemonic", "도움말(&H)" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "FileChooser 도움말" }, { "FileChooser.newFolderError.textAndMnemonic", "새 폴더를 생성하는 중 오류가 발생했습니다." }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "폴더를 생성할 수 없습니다.\n\n시스템에서 지정된 경로를 찾을 수 없습니다." }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "폴더를 생성할 수 없음" }, { "FileChooser.openButton.textAndMnemonic", "열기" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "선택된 파일 열기" }, { "FileChooser.openDialogTitle.textAndMnemonic", "열기" }, { "FileChooser.other.newFolder", "NewFolder" }, 
        { "FileChooser.other.newFolder.subsequent", "NewFolder.{0}" }, { "FileChooser.renameError.textAndMnemonic", "{0}의 이름을 바꿀 수 없습니다." }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "{0}의 이름을 바꿀 수 없음: 지정한 이름을 사용하는 파일이 존재합니다. 다른 파일 이름을 지정하십시오." }, { "FileChooser.renameErrorTitle.textAndMnemonic", "파일 또는 폴더 이름 바꾸는 중 오류 발생" }, { "FileChooser.saveButton.textAndMnemonic", "저장" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "선택된 파일 저장" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "저장" }, { "FileChooser.updateButton.textAndMnemonic", "업데이트(&U)" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "디렉토리 목록 업데이트" }, { "FileChooser.win32.newFolder", "새 폴더" }, 
        { "FileChooser.win32.newFolder.subsequent", "새 폴더({0})" }, { "FormView.browseFileButton.textAndMnemonic", "찾아보기..." }, { "FormView.resetButton.textAndMnemonic", "재설정" }, { "FormView.submitButton.textAndMnemonic", "질의 제출" }, { "InternalFrame.closeButtonToolTip", "닫기" }, { "InternalFrame.iconButtonToolTip", "최소화" }, { "InternalFrame.maxButtonToolTip", "최대화" }, { "InternalFrame.restoreButtonToolTip", "복원" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "닫기(&C)" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "닫기" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "아이콘화" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "최대화(&X)" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "최대화" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "최소화(&N)" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "이동(&M)" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "복원(&R)" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "크기(&S)" }, { "IsindexView.prompt", "다음은 검색 가능한 인덱스입니다. 검색 키워드 입력:" }, { "OptionPane.cancelButton.textAndMnemonic", "취소" }, { "OptionPane.inputDialog.titleAndMnemonic", "입력" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "메시지" }, { "OptionPane.noButton.textAndMnemonic", "아니오(&N)" }, { "OptionPane.okButton.textAndMnemonic", "확인" }, { "OptionPane.title.textAndMnemonic", "옵션 선택" }, { "OptionPane.yesButton.textAndMnemonic", "예(&Y)" }, { "PrintingDialog.abortButton.textAndMnemonic", "중단(&A)" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "인쇄 중단" }, { "PrintingDialog.contentAborting.textAndMnemonic", "인쇄 중단 중..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "인쇄 진행 중..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "인쇄된 페이지 {0}..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "인쇄(중단 중)" }, { "PrintingDialog.titleProgress.textAndMnemonic", "인쇄" }, { "ProgressMonitor.progress.textAndMnemonic", "진행..." }, { "SplitPane.leftButton.textAndMnemonic", "왼쪽 단추" }, { "SplitPane.rightButton.textAndMnemonic", "오른쪽 단추" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_ko.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */