package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_ja extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AbstractButton.click.textAndMnemonic", "クリック" }, { "AbstractDocument.addition.textAndMnemonic", "追加" }, { "AbstractDocument.deletion.textAndMnemonic", "削除" }, { "AbstractDocument.redo.textAndMnemonic", "やり直し" }, { "AbstractDocument.styleChange.textAndMnemonic", "スタイル変更" }, { "AbstractDocument.undo.textAndMnemonic", "元に戻す" }, { "AbstractUndoableEdit.redo.textAndMnemonic", "やり直し" }, { "AbstractUndoableEdit.undo.textAndMnemonic", "元に戻す" }, { "ColorChooser.cancel.textAndMnemonic", "取消" }, { "ColorChooser.cmyk.textAndMnemonic", "C&MYK" }, 
        { "ColorChooser.cmykAlpha.textAndMnemonic", "アルファ" }, { "ColorChooser.cmykBlack.textAndMnemonic", "黒" }, { "ColorChooser.cmykCyan.textAndMnemonic", "シアン" }, { "ColorChooser.cmykMagenta.textAndMnemonic", "マゼンタ" }, { "ColorChooser.cmykYellow.textAndMnemonic", "黄" }, { "ColorChooser.hsl.textAndMnemonic", "HSL(&L)" }, { "ColorChooser.hslHue.textAndMnemonic", "色相" }, { "ColorChooser.hslLightness.textAndMnemonic", "明度" }, { "ColorChooser.hslSaturation.textAndMnemonic", "彩度" }, { "ColorChooser.hslTransparency.textAndMnemonic", "透明度" }, 
        { "ColorChooser.hsv.textAndMnemonic", "HSV(&H)" }, { "ColorChooser.hsvHue.textAndMnemonic", "色相" }, { "ColorChooser.hsvSaturation.textAndMnemonic", "彩度" }, { "ColorChooser.hsvTransparency.textAndMnemonic", "透明度" }, { "ColorChooser.hsvValue.textAndMnemonic", "値" }, { "ColorChooser.ok.textAndMnemonic", "OK" }, { "ColorChooser.preview.textAndMnemonic", "プレビュー" }, { "ColorChooser.reset.textAndMnemonic", "リセット(&R)" }, { "ColorChooser.rgb.textAndMnemonic", "RGB(&G)" }, { "ColorChooser.rgbAlpha.textAndMnemonic", "アルファ" }, 
        { "ColorChooser.rgbBlue.textAndMnemonic", "青(&B)" }, { "ColorChooser.rgbGreen.textAndMnemonic", "緑(&N)" }, { "ColorChooser.rgbHexCode.textAndMnemonic", "色コード(&C)" }, { "ColorChooser.rgbRed.textAndMnemonic", "赤(&D)" }, { "ColorChooser.sample.textAndMnemonic", "サンプル・テキスト  サンプル・テキスト" }, { "ColorChooser.swatches.textAndMnemonic", "サンプル(&S)" }, { "ColorChooser.swatchesRecent.textAndMnemonic", "最新:" }, { "ComboBox.togglePopup.textAndMnemonic", "トグル・ポップアップ" }, { "FileChooser.acceptAllFileFilter.textAndMnemonic", "すべてのファイル" }, { "FileChooser.cancelButton.textAndMnemonic", "取消" }, 
        { "FileChooser.cancelButtonToolTip.textAndMnemonic", "ファイル・チューザ・ダイアログを終了します" }, { "FileChooser.directoryDescription.textAndMnemonic", "ディレクトリ" }, { "FileChooser.directoryOpenButton.textAndMnemonic", "開く" }, { "FileChooser.directoryOpenButtonToolTip.textAndMnemonic", "選択したディレクトリを開きます" }, { "FileChooser.fileDescription.textAndMnemonic", "汎用ファイル" }, { "FileChooser.fileSizeGigaBytes", "{0} GB" }, { "FileChooser.fileSizeKiloBytes", "{0} KB" }, { "FileChooser.fileSizeMegaBytes", "{0} MB" }, { "FileChooser.filesDetailsAccessibleName", "ファイルの詳細" }, { "FileChooser.filesListAccessibleName", "ファイル・リスト" }, 
        { "FileChooser.helpButton.textAndMnemonic", "ヘルプ(&H)" }, { "FileChooser.helpButtonToolTip.textAndMnemonic", "FileChooserのヘルプです" }, { "FileChooser.newFolderError.textAndMnemonic", "新規フォルダの作成エラー" }, { "FileChooser.newFolderErrorSeparator", ":" }, { "FileChooser.newFolderParentDoesntExist.textAndMnemonic", "フォルダを作成できません。\n\n指定したパスが見つかりません。" }, { "FileChooser.newFolderParentDoesntExistTitle.textAndMnemonic", "フォルダを作成できません" }, { "FileChooser.openButton.textAndMnemonic", "開く" }, { "FileChooser.openButtonToolTip.textAndMnemonic", "選択したファイルを開きます" }, { "FileChooser.openDialogTitle.textAndMnemonic", "開く" }, { "FileChooser.other.newFolder", "新規フォルダ" }, 
        { "FileChooser.other.newFolder.subsequent", "新規フォルダ.{0}" }, { "FileChooser.renameError.textAndMnemonic", "{0}の名前を変更できません" }, { "FileChooser.renameErrorFileExists.textAndMnemonic", "{0}の名前を変更できません: 指定した名前のファイルはすでに存在します。別のファイル名を指定してください。 " }, { "FileChooser.renameErrorTitle.textAndMnemonic", "ファイルまたはフォルダの名前変更エラー" }, { "FileChooser.saveButton.textAndMnemonic", "保存" }, { "FileChooser.saveButtonToolTip.textAndMnemonic", "選択したファイルを保存します" }, { "FileChooser.saveDialogTitle.textAndMnemonic", "保存" }, { "FileChooser.updateButton.textAndMnemonic", "更新(&U)" }, { "FileChooser.updateButtonToolTip.textAndMnemonic", "ディレクトリのリストを更新します" }, { "FileChooser.win32.newFolder", "新規フォルダ" }, 
        { "FileChooser.win32.newFolder.subsequent", "新規フォルダ({0})" }, { "FormView.browseFileButton.textAndMnemonic", "参照..." }, { "FormView.resetButton.textAndMnemonic", "リセット" }, { "FormView.submitButton.textAndMnemonic", "問合せの実行" }, { "InternalFrame.closeButtonToolTip", "閉じる" }, { "InternalFrame.iconButtonToolTip", "最小化" }, { "InternalFrame.maxButtonToolTip", "最大化" }, { "InternalFrame.restoreButtonToolTip", "復元" }, { "InternalFrameTitlePane.closeButton.textAndMnemonic", "閉じる(&C)" }, { "InternalFrameTitlePane.closeButtonAccessibleName", "閉じる" }, 
        { "InternalFrameTitlePane.iconifyButtonAccessibleName", "アイコン化" }, { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "最大化(&X)" }, { "InternalFrameTitlePane.maximizeButtonAccessibleName", "最大化" }, { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "最小化(&N)" }, { "InternalFrameTitlePane.moveButton.textAndMnemonic", "移動(&M)" }, { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "復元(&R)" }, { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "サイズ(&S)" }, { "IsindexView.prompt", "検索用の索引です。検索するキーワードを入力してください:" }, { "OptionPane.cancelButton.textAndMnemonic", "取消" }, { "OptionPane.inputDialog.titleAndMnemonic", "入力" }, 
        { "OptionPane.messageDialog.titleAndMnemonic", "メッセージ" }, { "OptionPane.noButton.textAndMnemonic", "いいえ(&N)" }, { "OptionPane.okButton.textAndMnemonic", "OK" }, { "OptionPane.title.textAndMnemonic", "オプションの選択" }, { "OptionPane.yesButton.textAndMnemonic", "はい(&Y)" }, { "PrintingDialog.abortButton.textAndMnemonic", "中止(&A)" }, { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "印刷の中止" }, { "PrintingDialog.contentAborting.textAndMnemonic", "印刷を中止しています..." }, { "PrintingDialog.contentInitial.textAndMnemonic", "印刷中..." }, { "PrintingDialog.contentProgress.textAndMnemonic", "ページ{0}を印刷しました..." }, 
        { "PrintingDialog.titleAborting.textAndMnemonic", "印刷を中止しています" }, { "PrintingDialog.titleProgress.textAndMnemonic", "印刷しています" }, { "ProgressMonitor.progress.textAndMnemonic", "進行中..." }, { "SplitPane.leftButton.textAndMnemonic", "左ボタン" }, { "SplitPane.rightButton.textAndMnemonic", "右ボタン" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\swing\internal\plaf\basic\resources\basic_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */