package sun.applet.resources;

import java.util.ListResourceBundle;

public class MsgAppletViewer_sv extends ListResourceBundle {
  public Object[][] getContents() { return new Object[][] { 
        { "textframe.button.dismiss", "Stäng" }, { "appletviewer.tool.title", "Applet Viewer: {0}" }, { "appletviewer.menu.applet", "Applet" }, { "appletviewer.menuitem.restart", "Starta om" }, { "appletviewer.menuitem.reload", "Ladda om" }, { "appletviewer.menuitem.stop", "Stopp" }, { "appletviewer.menuitem.save", "Spara..." }, { "appletviewer.menuitem.start", "Starta" }, { "appletviewer.menuitem.clone", "Klona..." }, { "appletviewer.menuitem.tag", "Tagg..." }, 
        { "appletviewer.menuitem.info", "Information..." }, { "appletviewer.menuitem.edit", "Redigera" }, { "appletviewer.menuitem.encoding", "Teckenkodning" }, { "appletviewer.menuitem.print", "Skriv ut..." }, { "appletviewer.menuitem.props", "Egenskaper..." }, { "appletviewer.menuitem.close", "Stäng" }, { "appletviewer.menuitem.quit", "Avsluta" }, { "appletviewer.label.hello", "Hej..." }, { "appletviewer.status.start", "startar applet..." }, { "appletviewer.appletsave.filedialogtitle", "Serialisera applet till fil" }, 
        { "appletviewer.appletsave.err1", "serialiserar {0} till {1}" }, { "appletviewer.appletsave.err2", "i appletSave: {0}" }, { "appletviewer.applettag", "Tagg visas" }, { "appletviewer.applettag.textframe", "HTML-tagg för applet" }, { "appletviewer.appletinfo.applet", "-- ingen appletinformation --" }, { "appletviewer.appletinfo.param", "-- ingen parameterinformation --" }, { "appletviewer.appletinfo.textframe", "Appletinformation" }, { "appletviewer.appletprint.fail", "Kunde inte skriva ut." }, { "appletviewer.appletprint.finish", "Utskriften klar." }, { "appletviewer.appletprint.cancel", "Utskriften avbruten." }, 
        { "appletviewer.appletencoding", "Teckenkodning: {0}" }, { "appletviewer.parse.warning.requiresname", "Varning: <param name=... value=...>-taggen kräver ett namnattribut." }, { "appletviewer.parse.warning.paramoutside", "Varning: <param>-taggen finns utanför <applet> ... </applet>." }, { "appletviewer.parse.warning.applet.requirescode", "Varning: <applet>-taggen kräver ett kodattribut." }, { "appletviewer.parse.warning.applet.requiresheight", "Varning: <applet>-taggen kräver ett höjdattribut." }, { "appletviewer.parse.warning.applet.requireswidth", "Varning: <applet>-taggen kräver ett breddattribut." }, { "appletviewer.parse.warning.object.requirescode", "Varning: <object>-taggen kräver ett kodattribut." }, { "appletviewer.parse.warning.object.requiresheight", "Varning: <object>-taggen kräver ett höjdattribut." }, { "appletviewer.parse.warning.object.requireswidth", "Varning: <object>-taggen kräver ett breddattribut." }, { "appletviewer.parse.warning.embed.requirescode", "Varning: <embed>-taggen kräver ett kodattribut." }, 
        { "appletviewer.parse.warning.embed.requiresheight", "Varning: <embed>-taggen kräver ett höjdattribut." }, { "appletviewer.parse.warning.embed.requireswidth", "Varning: <embed>-taggen kräver ett breddattribut." }, { "appletviewer.parse.warning.appnotLongersupported", "Varning: <app>-taggen stöds inte längre, använd <applet> istället:" }, { "appletviewer.usage", "Syntax: appletviewer-<alternativ> url:er \n\ndär <alternativ> inkluderar:\n  -debug                  Startar appletvisning i Java-felsökningen\n  -encoding <kodning>    Anger teckenkodning  som används i HTML-filer\n  -J<körningsflagga>        Överför argument till Java-tolkningen\n\nAlternativet -J är inte standard och kan ändras utan föregående meddelande." }, { "appletviewer.main.err.unsupportedopt", "Alternativ som inte stöds: {0}" }, { "appletviewer.main.err.unrecognizedarg", "Okänt argument: {0}" }, { "appletviewer.main.err.dupoption", "Duplicerat alternativ: {0}" }, { "appletviewer.main.err.inputfile", "Inga angivna indatafiler." }, { "appletviewer.main.err.badurl", "Felaktig URL: {0} ( {1} )" }, { "appletviewer.main.err.io", "I/O-undantag vid läsning: {0}" }, 
        { "appletviewer.main.err.readablefile", "Kontrollera att {0} är en fil som är läsbar." }, { "appletviewer.main.err.correcturl", "Är {0} den korrekta URL:en?" }, { "appletviewer.main.prop.store", "Användarspecifika egenskaper för AppletViewer" }, { "appletviewer.main.err.prop.cantread", "Kan inte läsa egenskapsfilen: {0}" }, { "appletviewer.main.err.prop.cantsave", "Kan inte spara egenskapsfilen: {0}" }, { "appletviewer.main.warn.nosecmgr", "Varning! Säkerheten avaktiveras." }, { "appletviewer.main.debug.cantfinddebug", "Hittar inte felsökningsprogrammet!" }, { "appletviewer.main.debug.cantfindmain", "Hittar inte huvudmetoden i felsökningsprogrammet!" }, { "appletviewer.main.debug.exceptionindebug", "Undantag i felsökningsprogrammet!" }, { "appletviewer.main.debug.cantaccess", "Det finns ingen åtkomst till felsökningsprogrammet!" }, 
        { "appletviewer.main.nosecmgr", "Varning: SecurityManager har inte installerats!" }, { "appletviewer.main.warning", "Varning: Inga appletar har startats. Kontrollera att indata innehåller <applet>-tagg." }, { "appletviewer.main.warn.prop.overwrite", "Varning: Skriver tillfälligt över systemegenskap enligt begäran från användare: nyckel: {0} tidigare värde: {1} nytt värde: {2}" }, { "appletviewer.main.warn.cantreadprops", "Varning: Kan inte läsa egenskapsfil för AppletViewer: {0} Standardvärden används." }, { "appletioexception.loadclass.throw.interrupted", "klassladdning avbröts: {0}" }, { "appletioexception.loadclass.throw.notloaded", "klass inte laddad: {0}" }, { "appletclassloader.loadcode.verbose", "Öppnar ström till: {0} för hämtning av {1}" }, { "appletclassloader.filenotfound", "Hittade inte fil vid sökning efter: {0}" }, { "appletclassloader.fileformat", "Undantag av filformat vid laddning av: {0}" }, { "appletclassloader.fileioexception", "I/O-undantag vid laddning: {0}" }, 
        { "appletclassloader.fileexception", "{0} undantag vid laddning: {1}" }, { "appletclassloader.filedeath", "{0} avslutad vid laddning: {1}" }, { "appletclassloader.fileerror", "{0} fel vid laddning: {1}" }, { "appletclassloader.findclass.verbose.openstream", "Öppnar ström till: {0} för hämtning av {1}" }, { "appletclassloader.getresource.verbose.forname", "AppletClassLoader.getResource för namnet: {0}" }, { "appletclassloader.getresource.verbose.found", "Hittade resursen: {0} som systemresurs" }, { "appletclassloader.getresourceasstream.verbose", "Hittade resursen: {0} som systemresurs" }, { "appletpanel.runloader.err", "Antingen objekt- eller kodparameter!" }, { "appletpanel.runloader.exception", "undantag vid avserialisering {0}" }, { "appletpanel.destroyed", "Applet raderad." }, 
        { "appletpanel.loaded", "Applet laddad." }, { "appletpanel.started", "Applet startad." }, { "appletpanel.inited", "Applet initierad." }, { "appletpanel.stopped", "Applet stoppad." }, { "appletpanel.disposed", "Applet kasserad." }, { "appletpanel.nocode", "APPLET-tagg saknar CODE-parameter." }, { "appletpanel.notfound", "load: hittade inte klassen {0}." }, { "appletpanel.nocreate", "load: {0} kan inte instansieras." }, { "appletpanel.noconstruct", "load: {0} är inte allmän eller saknar allmän konstruktor." }, { "appletpanel.death", "avslutad" }, 
        { "appletpanel.exception", "undantag: {0}." }, { "appletpanel.exception2", "undantag: {0}: {1}." }, { "appletpanel.error", "fel: {0}." }, { "appletpanel.error2", "fel {0}: {1}." }, { "appletpanel.notloaded", "Initiera: applet är inte laddad." }, { "appletpanel.notinited", "Starta: applet är inte initierad." }, { "appletpanel.notstarted", "Stoppa: applet har inte startats." }, { "appletpanel.notstopped", "Radera: applet har inte stoppats." }, { "appletpanel.notdestroyed", "Kassera: applet har inte raderats." }, { "appletpanel.notdisposed", "Ladda: applet har inte kasserats." }, 
        { "appletpanel.bail", "Avbruten." }, { "appletpanel.filenotfound", "Hittade inte fil vid sökning efter: {0}" }, { "appletpanel.fileformat", "Undantag av filformat vid laddning av: {0}" }, { "appletpanel.fileioexception", "I/O-undantag vid laddning: {0}" }, { "appletpanel.fileexception", "{0} undantag vid laddning: {1}" }, { "appletpanel.filedeath", "{0} avslutad vid laddning: {1}" }, { "appletpanel.fileerror", "{0} fel vid laddning: {1}" }, { "appletpanel.badattribute.exception", "HTML-tolkning: felaktigt värde för bredd-/höjdattribut" }, { "appletillegalargumentexception.objectinputstream", "AppletObjectInputStream kräver laddare med icke-null" }, { "appletprops.title", "AppletViewer-egenskaper" }, 
        { "appletprops.label.http.server", "HTTP-proxyserver:" }, { "appletprops.label.http.proxy", "HTTP-proxyport:" }, { "appletprops.label.network", "Nätverksåtkomst:" }, { "appletprops.choice.network.item.none", "Ingen" }, { "appletprops.choice.network.item.applethost", "Appletvärd" }, { "appletprops.choice.network.item.unrestricted", "Obegränsad" }, { "appletprops.label.class", "Klassåtkomst:" }, { "appletprops.choice.class.item.restricted", "Begränsad" }, { "appletprops.choice.class.item.unrestricted", "Obegränsad" }, { "appletprops.label.unsignedapplet", "Tillåt osignerade appletar:" }, 
        { "appletprops.choice.unsignedapplet.no", "Nej" }, { "appletprops.choice.unsignedapplet.yes", "Ja" }, { "appletprops.button.apply", "Använd" }, { "appletprops.button.cancel", "Avbryt" }, { "appletprops.button.reset", "Återställ" }, { "appletprops.apply.exception", "Kunde inte spara egenskaper: {0}" }, { "appletprops.title.invalidproxy", "Ogiltig post" }, { "appletprops.label.invalidproxy", "Proxyport måste vara ett positivt heltal." }, { "appletprops.button.ok", "OK" }, { "appletprops.prop.store", "Användarspecifika egenskaper för AppletViewer" }, 
        { "appletsecurityexception.checkcreateclassloader", "Säkerhetsundantag: klassladdare" }, { "appletsecurityexception.checkaccess.thread", "Säkerhetsundantag: tråd" }, { "appletsecurityexception.checkaccess.threadgroup", "Säkerhetsundantag: trådgrupp: {0}" }, { "appletsecurityexception.checkexit", "Säkerhetsundantag: utgång: {0}" }, { "appletsecurityexception.checkexec", "Säkerhetsundantag: exec: {0}" }, { "appletsecurityexception.checklink", "Säkerhetsundantag: länk: {0}" }, { "appletsecurityexception.checkpropsaccess", "Säkerhetsundantag: egenskaper" }, { "appletsecurityexception.checkpropsaccess.key", "Säkerhetsundantag: egenskapsåtkomst {0}" }, { "appletsecurityexception.checkread.exception1", "Säkerhetsundantag: {0}, {1}" }, { "appletsecurityexception.checkread.exception2", "Säkerhetsundantag: file.read: {0}" }, 
        { "appletsecurityexception.checkread", "Säkerhetsundantag: file.read: {0} == {1}" }, { "appletsecurityexception.checkwrite.exception", "Säkerhetsundantag: {0}, {1}" }, { "appletsecurityexception.checkwrite", "Säkerhetsundantag: file.write: {0} == {1}" }, { "appletsecurityexception.checkread.fd", "Säkerhetsundantag: fd.read" }, { "appletsecurityexception.checkwrite.fd", "Säkerhetsundantag: fd.write" }, { "appletsecurityexception.checklisten", "Säkerhetsundantag: socket.listen: {0}" }, { "appletsecurityexception.checkaccept", "Säkerhetsundantag: socket.accept: {0}:{1}" }, { "appletsecurityexception.checkconnect.networknone", "Säkerhetsundantag: socket.connect: {0}->{1}" }, { "appletsecurityexception.checkconnect.networkhost1", "Säkerhetsundantag: Kunde inte ansluta till {0} med ursprung från {1}." }, { "appletsecurityexception.checkconnect.networkhost2", "Säkerhetsundantag: Kunde inte matcha IP för värd {0} eller för {1}. " }, 
        { "appletsecurityexception.checkconnect.networkhost3", "Säkerhetsundantag: Kunde inte matcha IP för värd {0}. Se egenskapen trustProxy." }, { "appletsecurityexception.checkconnect", "Säkerhetsundantag: connect: {0}->{1}" }, { "appletsecurityexception.checkpackageaccess", "Säkerhetsundantag: ingen åtkomst till paket: {0}" }, { "appletsecurityexception.checkpackagedefinition", "Säkerhetsundantag: kan inte definiera paket: {0}" }, { "appletsecurityexception.cannotsetfactory", "Säkerhetsundantag: kan inte ange fabrik" }, { "appletsecurityexception.checkmemberaccess", "Säkerhetsundantag: kontrollera medlemsåtkomst" }, { "appletsecurityexception.checkgetprintjob", "Säkerhetsundantag: getPrintJob" }, { "appletsecurityexception.checksystemclipboardaccess", "Säkerhetsundantag: getSystemClipboard" }, { "appletsecurityexception.checkawteventqueueaccess", "Säkerhetsundantag: getEventQueue" }, { "appletsecurityexception.checksecurityaccess", "Säkerhetsundantag: säkerhetsåtgärd: {0}" }, 
        { "appletsecurityexception.getsecuritycontext.unknown", "okänd typ av klassladdare. kan inte kontrollera getContext" }, { "appletsecurityexception.checkread.unknown", "okänd typ av klassladdare. kan inte kontrollera kontrolläsning {0}" }, { "appletsecurityexception.checkconnect.unknown", "okänd typ av klassladdare. kan inte kontrollera kontrollanslutning" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\applet\resources\MsgAppletViewer_sv.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */