package sun.applet.resources;

import java.util.ListResourceBundle;

public class MsgAppletViewer_ko extends ListResourceBundle {
  public Object[][] getContents() { return new Object[][] { 
        { "textframe.button.dismiss", "해제" }, { "appletviewer.tool.title", "애플릿 뷰어: {0}" }, { "appletviewer.menu.applet", "애플릿" }, { "appletviewer.menuitem.restart", "재시작" }, { "appletviewer.menuitem.reload", "재로드" }, { "appletviewer.menuitem.stop", "정지" }, { "appletviewer.menuitem.save", "저장..." }, { "appletviewer.menuitem.start", "시작" }, { "appletviewer.menuitem.clone", "복제..." }, { "appletviewer.menuitem.tag", "태그 지정..." }, 
        { "appletviewer.menuitem.info", "정보..." }, { "appletviewer.menuitem.edit", "편집" }, { "appletviewer.menuitem.encoding", "문자 인코딩" }, { "appletviewer.menuitem.print", "인쇄..." }, { "appletviewer.menuitem.props", "속성..." }, { "appletviewer.menuitem.close", "닫기" }, { "appletviewer.menuitem.quit", "종료" }, { "appletviewer.label.hello", "시작..." }, { "appletviewer.status.start", "애플릿을 시작하는 중..." }, { "appletviewer.appletsave.filedialogtitle", "파일로 애플릿 직렬화" }, 
        { "appletviewer.appletsave.err1", "{0}을(를) {1}(으)로 직렬화하는 중" }, { "appletviewer.appletsave.err2", "appletSave에 오류 발생: {0}" }, { "appletviewer.applettag", "태그가 표시됨" }, { "appletviewer.applettag.textframe", "애플릿 HTML 태그" }, { "appletviewer.appletinfo.applet", "-- 애플릿 정보 없음 --" }, { "appletviewer.appletinfo.param", "-- 매개변수 정보 없음 --" }, { "appletviewer.appletinfo.textframe", "애플릿 정보" }, { "appletviewer.appletprint.fail", "인쇄를 실패했습니다." }, { "appletviewer.appletprint.finish", "인쇄를 완료했습니다." }, { "appletviewer.appletprint.cancel", "인쇄가 취소되었습니다." }, 
        { "appletviewer.appletencoding", "문자 인코딩: {0}" }, { "appletviewer.parse.warning.requiresname", "경고: <param name=... value=...> 태그에는 name 속성이 필요합니다." }, { "appletviewer.parse.warning.paramoutside", "경고: <param> 태그가 <applet> ... </applet> 밖에 있습니다." }, { "appletviewer.parse.warning.applet.requirescode", "경고: <applet> 태그에는 code 속성이 필요합니다." }, { "appletviewer.parse.warning.applet.requiresheight", "경고: <applet> 태그에는 height 속성이 필요합니다." }, { "appletviewer.parse.warning.applet.requireswidth", "경고: <applet> 태그에는 width 속성이 필요합니다." }, { "appletviewer.parse.warning.object.requirescode", "경고: <object> 태그에는 code 속성이 필요합니다." }, { "appletviewer.parse.warning.object.requiresheight", "경고: <object> 태그에는 height 속성이 필요합니다." }, { "appletviewer.parse.warning.object.requireswidth", "경고: <object> 태그에는 width 속성이 필요합니다." }, { "appletviewer.parse.warning.embed.requirescode", "경고: <embed> 태그에는 code 속성이 필요합니다." }, 
        { "appletviewer.parse.warning.embed.requiresheight", "경고: <embed> 태그에는 height 속성이 필요합니다." }, { "appletviewer.parse.warning.embed.requireswidth", "경고: <embed> 태그에는 width 속성이 필요합니다." }, { "appletviewer.parse.warning.appnotLongersupported", "경고: <app> 태그는 더 이상 지원되지 않습니다. 대신 <applet>을 사용하십시오." }, { "appletviewer.usage", "사용법: appletviewer <options> url(s)\n\n여기서 <options>는 다음과 같습니다.\n  -debug                  Java 디버거에서 애플릿 뷰어를 시작합니다.\n  -encoding <encoding>    HTML 파일에 사용될 문자 인코딩을 지정합니다.\n  -J<runtime flag>        Java 인터프리터로 인수를 전달합니다.\n\n-J 옵션은 표준이 아니며 예고 없이 변경될 수 있습니다." }, { "appletviewer.main.err.unsupportedopt", "지원되지 않는 옵션: {0}" }, { "appletviewer.main.err.unrecognizedarg", "알 수 없는 인수: {0}" }, { "appletviewer.main.err.dupoption", "중복된 옵션 사용: {0}" }, { "appletviewer.main.err.inputfile", "지정된 입력 파일이 없습니다." }, { "appletviewer.main.err.badurl", "잘못된 URL: {0}({1})" }, { "appletviewer.main.err.io", "읽는 중 I/O 예외사항 발생: {0}" }, 
        { "appletviewer.main.err.readablefile", "{0}이(가) 파일이며 읽기 가능한 상태인지 확인하십시오." }, { "appletviewer.main.err.correcturl", "{0}이(가) 올바른 URL입니까?" }, { "appletviewer.main.prop.store", "사용자 관련 AppletViewer 속성" }, { "appletviewer.main.err.prop.cantread", "사용자 속성 파일을 읽을 수 없음: {0}" }, { "appletviewer.main.err.prop.cantsave", "사용자 속성 파일을 저장할 수 없음: {0}" }, { "appletviewer.main.warn.nosecmgr", "경고: 보안을 사용 안함으로 설정하는 중입니다." }, { "appletviewer.main.debug.cantfinddebug", "디버거를 찾을 수 없습니다!" }, { "appletviewer.main.debug.cantfindmain", "디버거에서 기본 메소드를 찾을 수 없습니다!" }, { "appletviewer.main.debug.exceptionindebug", "디버거에 예외사항이 발생했습니다!" }, { "appletviewer.main.debug.cantaccess", "디버거에 액세스할 수 없습니다!" }, 
        { "appletviewer.main.nosecmgr", "경고: SecurityManager가 설치되지 않았습니다!" }, { "appletviewer.main.warning", "경고: 시작된 애플릿이 없습니다. <applet> 태그가 입력되었는지 확인하십시오." }, { "appletviewer.main.warn.prop.overwrite", "경고: 사용자의 요청에 따라 일시적으로 시스템 속성을 겹쳐 쓰는 중: 키: {0}, 이전 값: {1}, 새 값: {2}" }, { "appletviewer.main.warn.cantreadprops", "경고: AppletViewer 속성 파일을 읽을 수 없음: {0}. 기본값을 사용하는 중입니다." }, { "appletioexception.loadclass.throw.interrupted", "클래스 로드가 중단됨: {0}" }, { "appletioexception.loadclass.throw.notloaded", "클래스가 로드되지 않음: {0}" }, { "appletclassloader.loadcode.verbose", "{1}을(를) 가져오기 위해 {0}에 대한 스트림을 여는 중" }, { "appletclassloader.filenotfound", "{0}을(를) 검색하는 중 파일을 찾지 못했습니다." }, { "appletclassloader.fileformat", "로드 중 파일 형식 예외사항 발생: {0}" }, { "appletclassloader.fileioexception", "로드 중 I/O 예외사항 발생: {0}" }, 
        { "appletclassloader.fileexception", "로드 중 {0} 예외사항 발생: {1}" }, { "appletclassloader.filedeath", "로드 중 {0}이(가) 종료됨: {1}" }, { "appletclassloader.fileerror", "로드 중 {0} 오류 발생: {1}" }, { "appletclassloader.findclass.verbose.openstream", "{1}을(를) 가져오기 위해 {0}에 대한 스트림을 여는 중" }, { "appletclassloader.getresource.verbose.forname", "이름에 대한 AppletClassLoader.getResource: {0}" }, { "appletclassloader.getresource.verbose.found", "시스템 리소스로 {0} 리소스를 찾았습니다." }, { "appletclassloader.getresourceasstream.verbose", "시스템 리소스로 {0} 리소스를 찾았습니다." }, { "appletpanel.runloader.err", "객체 또는 코드 매개변수입니다!" }, { "appletpanel.runloader.exception", "{0}의 직렬화를 해제하는 중 예외사항이 발생했습니다." }, { "appletpanel.destroyed", "애플릿이 삭제되었습니다." }, 
        { "appletpanel.loaded", "애플릿이 로드되었습니다." }, { "appletpanel.started", "애플릿이 시작되었습니다." }, { "appletpanel.inited", "애플릿이 초기화되었습니다." }, { "appletpanel.stopped", "애플릿이 정지되었습니다." }, { "appletpanel.disposed", "애플릿이 배치되었습니다." }, { "appletpanel.nocode", "APPLET 태그에 CODE 매개변수가 누락되었습니다." }, { "appletpanel.notfound", "로드: {0} 클래스를 찾을 수 없습니다." }, { "appletpanel.nocreate", "로드: {0}을(를) 인스턴스화할 수 없습니다." }, { "appletpanel.noconstruct", "로드: {0}은(는) 공용이 아니거나 공용 생성자를 포함하지 않습니다." }, { "appletpanel.death", "종료됨" }, 
        { "appletpanel.exception", "예외사항: {0}." }, { "appletpanel.exception2", "예외사항: {0}: {1}." }, { "appletpanel.error", "오류: {0}." }, { "appletpanel.error2", "오류: {0}: {1}." }, { "appletpanel.notloaded", "초기화: 애플릿이 로드되지 않았습니다." }, { "appletpanel.notinited", "시작: 애플릿이 초기화되지 않았습니다." }, { "appletpanel.notstarted", "정지: 애플릿이 시작되지 않았습니다." }, { "appletpanel.notstopped", "삭제: 애플릿이 정지되지 않았습니다." }, { "appletpanel.notdestroyed", "배치: 애플릿이 삭제되지 않았습니다." }, { "appletpanel.notdisposed", "로드: 애플릿이 배치되지 않았습니다." }, 
        { "appletpanel.bail", "중단됨: 중단하는 중입니다." }, { "appletpanel.filenotfound", "{0}을(를) 검색하는 중 파일을 찾지 못했습니다." }, { "appletpanel.fileformat", "로드 중 파일 형식 예외사항 발생: {0}" }, { "appletpanel.fileioexception", "로드 중 I/O 예외사항 발생: {0}" }, { "appletpanel.fileexception", "로드 중 {0} 예외사항 발생: {1}" }, { "appletpanel.filedeath", "로드 중 {0}이(가) 종료됨: {1}" }, { "appletpanel.fileerror", "로드 중 {0} 오류 발생: {1}" }, { "appletpanel.badattribute.exception", "HTML 구문 분석 중: width/height 속성에 대한 값이 올바르지 않습니다." }, { "appletillegalargumentexception.objectinputstream", "AppletObjectInputStream에 널이 아닌 로더가 필요합니다." }, { "appletprops.title", "AppletViewer 속성" }, 
        { "appletprops.label.http.server", "HTTP 프록시 서버:" }, { "appletprops.label.http.proxy", "HTTP 프록시 포트:" }, { "appletprops.label.network", "네트워크 액세스:" }, { "appletprops.choice.network.item.none", "없음" }, { "appletprops.choice.network.item.applethost", "애플릿 호스트" }, { "appletprops.choice.network.item.unrestricted", "제한되지 않음" }, { "appletprops.label.class", "클래스 액세스:" }, { "appletprops.choice.class.item.restricted", "제한됨" }, { "appletprops.choice.class.item.unrestricted", "제한되지 않음" }, { "appletprops.label.unsignedapplet", "서명되지 않은 애플릿 허용:" }, 
        { "appletprops.choice.unsignedapplet.no", "아니오" }, { "appletprops.choice.unsignedapplet.yes", "예" }, { "appletprops.button.apply", "적용" }, { "appletprops.button.cancel", "취소" }, { "appletprops.button.reset", "재설정" }, { "appletprops.apply.exception", "속성 저장 실패: {0}" }, { "appletprops.title.invalidproxy", "부적합한 항목" }, { "appletprops.label.invalidproxy", "프록시 포트는 양의 정수 값이어야 합니다." }, { "appletprops.button.ok", "확인" }, { "appletprops.prop.store", "사용자 관련 AppletViewer 속성" }, 
        { "appletsecurityexception.checkcreateclassloader", "보안 예외사항: 클래스 로더" }, { "appletsecurityexception.checkaccess.thread", "보안 예외사항: 스레드" }, { "appletsecurityexception.checkaccess.threadgroup", "보안 예외사항: 스레드 그룹: {0}" }, { "appletsecurityexception.checkexit", "보안 예외사항: 종료: {0}" }, { "appletsecurityexception.checkexec", "보안 예외사항: 실행: {0}" }, { "appletsecurityexception.checklink", "보안 예외사항: 링크: {0}" }, { "appletsecurityexception.checkpropsaccess", "보안 예외사항: 속성" }, { "appletsecurityexception.checkpropsaccess.key", "보안 예외사항: 속성 액세스 {0}" }, { "appletsecurityexception.checkread.exception1", "보안 예외사항: {0}, {1}" }, { "appletsecurityexception.checkread.exception2", "보안 예외사항: file.read: {0}" }, 
        { "appletsecurityexception.checkread", "보안 예외사항: file.read: {0} == {1}" }, { "appletsecurityexception.checkwrite.exception", "보안 예외사항: {0}, {1}" }, { "appletsecurityexception.checkwrite", "보안 예외사항: file.write: {0} == {1}" }, { "appletsecurityexception.checkread.fd", "보안 예외사항: fd.read" }, { "appletsecurityexception.checkwrite.fd", "보안 예외사항: fd.write" }, { "appletsecurityexception.checklisten", "보안 예외사항: socket.listen: {0}" }, { "appletsecurityexception.checkaccept", "보안 예외사항: socket.accept: {0}:{1}" }, { "appletsecurityexception.checkconnect.networknone", "보안 예외사항: socket.connect: {0}->{1}" }, { "appletsecurityexception.checkconnect.networkhost1", "보안 예외사항: {1}에서 {0}에 접속할 수 없습니다." }, { "appletsecurityexception.checkconnect.networkhost2", "보안 예외사항: {0} 호스트 또는 {1}에 대한 IP를 분석할 수 없습니다. " }, 
        { "appletsecurityexception.checkconnect.networkhost3", "보안 예외사항: {0} 호스트에 대한 IP를 분석할 수 없습니다. trustProxy 속성을 참조하십시오." }, { "appletsecurityexception.checkconnect", "보안 예외사항: 접속: {0}->{1}" }, { "appletsecurityexception.checkpackageaccess", "보안 예외사항: 패키지에 액세스할 수 없음: {0}" }, { "appletsecurityexception.checkpackagedefinition", "보안 예외사항: 패키지를 정의할 수 없음: {0}" }, { "appletsecurityexception.cannotsetfactory", "보안 예외사항: 팩토리를 설정할 수 없습니다." }, { "appletsecurityexception.checkmemberaccess", "보안 예외사항: 멤버 액세스를 확인하십시오." }, { "appletsecurityexception.checkgetprintjob", "보안 예외사항: getPrintJob" }, { "appletsecurityexception.checksystemclipboardaccess", "보안 예외사항: getSystemClipboard" }, { "appletsecurityexception.checkawteventqueueaccess", "보안 예외사항: getEventQueue" }, { "appletsecurityexception.checksecurityaccess", "보안 예외사항: 보안 작업: {0}" }, 
        { "appletsecurityexception.getsecuritycontext.unknown", "알 수 없는 클래스 로더 유형입니다. getContext를 확인할 수 없습니다." }, { "appletsecurityexception.checkread.unknown", "알 수 없는 클래스 로더 유형입니다. {0} 읽기를 확인할 수 없습니다." }, { "appletsecurityexception.checkconnect.unknown", "알 수 없는 클래스 로더 유형입니다. 접속을 확인할 수 없습니다." } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\applet\resources\MsgAppletViewer_ko.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */