package sun.applet.resources;

import java.util.ListResourceBundle;

public class MsgAppletViewer_ja extends ListResourceBundle {
  public Object[][] getContents() { return new Object[][] { 
        { "textframe.button.dismiss", "取消" }, { "appletviewer.tool.title", "アプレット・ビューア: {0}" }, { "appletviewer.menu.applet", "アプレット" }, { "appletviewer.menuitem.restart", "再起動" }, { "appletviewer.menuitem.reload", "再ロード" }, { "appletviewer.menuitem.stop", "停止" }, { "appletviewer.menuitem.save", "保存..." }, { "appletviewer.menuitem.start", "開始" }, { "appletviewer.menuitem.clone", "クローン..." }, { "appletviewer.menuitem.tag", "タグ..." }, 
        { "appletviewer.menuitem.info", "情報..." }, { "appletviewer.menuitem.edit", "編集" }, { "appletviewer.menuitem.encoding", "文字エンコーディング" }, { "appletviewer.menuitem.print", "印刷..." }, { "appletviewer.menuitem.props", "プロパティ..." }, { "appletviewer.menuitem.close", "閉じる" }, { "appletviewer.menuitem.quit", "終了" }, { "appletviewer.label.hello", "Hello..." }, { "appletviewer.status.start", "アプレットを開始しています..." }, { "appletviewer.appletsave.filedialogtitle", "アプレットをファイルにシリアライズ" }, 
        { "appletviewer.appletsave.err1", "{0}を{1}にシリアライズ" }, { "appletviewer.appletsave.err2", "appletSave内: {0}" }, { "appletviewer.applettag", "タグの表示" }, { "appletviewer.applettag.textframe", "アプレットHTMLタグ" }, { "appletviewer.appletinfo.applet", "-- アプレット情報なし --" }, { "appletviewer.appletinfo.param", "-- パラメータ情報なし --" }, { "appletviewer.appletinfo.textframe", "アプレット情報" }, { "appletviewer.appletprint.fail", "印刷が失敗しました。" }, { "appletviewer.appletprint.finish", "印刷を終了しました。" }, { "appletviewer.appletprint.cancel", "印刷が取り消されました。" }, 
        { "appletviewer.appletencoding", "文字エンコーディング: {0}" }, { "appletviewer.parse.warning.requiresname", "警告: <param name=... value=...>タグにname属性が必要です。" }, { "appletviewer.parse.warning.paramoutside", "警告: <param>タグが<applet> ... </applet>の外側です。" }, { "appletviewer.parse.warning.applet.requirescode", "警告: <applet>タグにcode属性が必要です。" }, { "appletviewer.parse.warning.applet.requiresheight", "警告: <applet>タグにheight属性が必要です。" }, { "appletviewer.parse.warning.applet.requireswidth", "警告: <applet>タグにwidth属性が必要です。" }, { "appletviewer.parse.warning.object.requirescode", "警告: <object>タグにcode属性が必要です。" }, { "appletviewer.parse.warning.object.requiresheight", "警告: <object>タグにheight属性が必要です。" }, { "appletviewer.parse.warning.object.requireswidth", "警告: <object>タグにwidth属性が必要です。" }, { "appletviewer.parse.warning.embed.requirescode", "警告: <embed>タグにcode属性が必要です。" }, 
        { "appletviewer.parse.warning.embed.requiresheight", "警告: <embed>タグにheight属性が必要です。" }, { "appletviewer.parse.warning.embed.requireswidth", "警告: <embed>タグにwidth属性が必要です。" }, { "appletviewer.parse.warning.appnotLongersupported", "警告: <app>タグは現在はサポートされていません。かわりに<applet>を使用してください。" }, { "appletviewer.usage", "使用方法: appletviewer <options> url(s)\n\n<options>には次のものがあります:\n  -debug                  Javaデバッガでアプレット・ビューアを開始する\n  -encoding <encoding>    HTMLファイルによって使用される文字エンコーディングを指定する\n  -J<runtime flag>        引数をJavaインタプリタに渡す\n\n-Jは非標準オプションであり、予告なしに変更される可能性があります。" }, { "appletviewer.main.err.unsupportedopt", "サポートされていないオプション: {0}" }, { "appletviewer.main.err.unrecognizedarg", "認識されない引数: {0}" }, { "appletviewer.main.err.dupoption", "オプションの使用が重複しています: {0}" }, { "appletviewer.main.err.inputfile", "入力ファイルが指定されていません。" }, { "appletviewer.main.err.badurl", "不正なURL: {0} ( {1} )" }, { "appletviewer.main.err.io", "読込み中の入出力例外です: {0}" }, 
        { "appletviewer.main.err.readablefile", "{0}がファイルであり、読込み可能であることを確認してください。" }, { "appletviewer.main.err.correcturl", "{0}は正しいURLですか。" }, { "appletviewer.main.prop.store", "AppletViewer用のユーザーが指定したプロパティ" }, { "appletviewer.main.err.prop.cantread", "ユーザー・プロパティ・ファイルを読み込めません: {0}" }, { "appletviewer.main.err.prop.cantsave", "ユーザー・プロパティ・ファイルを保存できません: {0}" }, { "appletviewer.main.warn.nosecmgr", "警告: セキュリティを無効化します。" }, { "appletviewer.main.debug.cantfinddebug", "デバッガが見つかりません。" }, { "appletviewer.main.debug.cantfindmain", "デバッガのメイン・メソッドが見つかりません。" }, { "appletviewer.main.debug.exceptionindebug", "デバッガに例外が発生しました。" }, { "appletviewer.main.debug.cantaccess", "デバッガにアクセスできません。" }, 
        { "appletviewer.main.nosecmgr", "警告: SecurityManagerがインストールされていません。" }, { "appletviewer.main.warning", "警告: アプレットが開始されませんでした。入力に<applet>タグがあることを確認してください。" }, { "appletviewer.main.warn.prop.overwrite", "警告: ユーザーのリクエストでシステム・プロパティを一時的に上書きします: キー: {0} 古い値: {1} 新しい値: {2}" }, { "appletviewer.main.warn.cantreadprops", "警告: AppletViewerプロパティ・ファイル{0}を読み込めません。デフォルトを使用します。" }, { "appletioexception.loadclass.throw.interrupted", "クラスのロードが中断しました: {0}" }, { "appletioexception.loadclass.throw.notloaded", "クラスがロードされません: {0}" }, { "appletclassloader.loadcode.verbose", "{1}を取得するための{0}へのストリームを開きます" }, { "appletclassloader.filenotfound", "{0}の検索中にファイルが見つかりません" }, { "appletclassloader.fileformat", "{0}のロード中にファイル形式例外が発生しました" }, { "appletclassloader.fileioexception", "{0}のロード中に入出力例外が発生しました" }, 
        { "appletclassloader.fileexception", "{1}のロード中に{0}例外が発生しました" }, { "appletclassloader.filedeath", "{1}のロード中に{0}が強制終了しました" }, { "appletclassloader.fileerror", "{1}のロード中に{0}エラーが発生しました" }, { "appletclassloader.findclass.verbose.openstream", "{1}を取得するための{0}へのストリームを開きます" }, { "appletclassloader.getresource.verbose.forname", "名前{0}のAppletClassLoader.getResourceです" }, { "appletclassloader.getresource.verbose.found", "リソース{0}がシステム・リソースとして検出されました" }, { "appletclassloader.getresourceasstream.verbose", "リソース{0}がシステム・リソースとして検出されました" }, { "appletpanel.runloader.err", "オブジェクトまたはコード・パラメータのいずれかです。" }, { "appletpanel.runloader.exception", "{0}のデシリアライズ中に例外が発生しました" }, { "appletpanel.destroyed", "アプレットが破棄されました。" }, 
        { "appletpanel.loaded", "アプレットがロードされました。" }, { "appletpanel.started", "アプレットが開始されました。" }, { "appletpanel.inited", "アプレットが初期化されました。" }, { "appletpanel.stopped", "アプレットが停止されました。" }, { "appletpanel.disposed", "アプレットが破棄されました。" }, { "appletpanel.nocode", "APPLETタグにCODEパラメータがありません。" }, { "appletpanel.notfound", "ロード: クラス{0}が見つかりません。" }, { "appletpanel.nocreate", "ロード: {0}をインスタンス化できません。" }, { "appletpanel.noconstruct", "ロード: {0}はpublicでないか、publicコンストラクタを持っていません。" }, { "appletpanel.death", "強制終了されました" }, 
        { "appletpanel.exception", "例外: {0}。" }, { "appletpanel.exception2", "例外: {0}: {1}。" }, { "appletpanel.error", "エラー: {0}。" }, { "appletpanel.error2", "エラー: {0}: {1}。" }, { "appletpanel.notloaded", "初期化: アプレットがロードされていません。" }, { "appletpanel.notinited", "開始: アプレットが初期化されていません。" }, { "appletpanel.notstarted", "停止: アプレットが開始されていません。" }, { "appletpanel.notstopped", "破棄: アプレットが停止されていません。" }, { "appletpanel.notdestroyed", "破棄: アプレットが破棄されていません。" }, { "appletpanel.notdisposed", "ロード: アプレットが破棄されていません。" }, 
        { "appletpanel.bail", "中断済: 終了しています。" }, { "appletpanel.filenotfound", "{0}の検索中にファイルが見つかりません" }, { "appletpanel.fileformat", "{0}のロード中にファイル形式例外が発生しました" }, { "appletpanel.fileioexception", "{0}のロード中に入出力例外が発生しました" }, { "appletpanel.fileexception", "{1}のロード中に{0}例外が発生しました" }, { "appletpanel.filedeath", "{1}のロード中に{0}が強制終了しました" }, { "appletpanel.fileerror", "{1}のロード中に{0}エラーが発生しました" }, { "appletpanel.badattribute.exception", "HTML解析: widthまたはheight属性の値が不正です" }, { "appletillegalargumentexception.objectinputstream", "AppletObjectInputStreamは非nullのローダーが必要です" }, { "appletprops.title", "AppletViewerプロパティ" }, 
        { "appletprops.label.http.server", "Httpプロキシ・サーバー:" }, { "appletprops.label.http.proxy", "Httpプロキシ・ポート:" }, { "appletprops.label.network", "ネットワーク・アクセス:" }, { "appletprops.choice.network.item.none", "なし" }, { "appletprops.choice.network.item.applethost", "アプレット・ホスト" }, { "appletprops.choice.network.item.unrestricted", "制限なし" }, { "appletprops.label.class", "クラス・アクセス:" }, { "appletprops.choice.class.item.restricted", "制限付き" }, { "appletprops.choice.class.item.unrestricted", "制限なし" }, { "appletprops.label.unsignedapplet", "署名されていないアプレットを許可:" }, 
        { "appletprops.choice.unsignedapplet.no", "いいえ" }, { "appletprops.choice.unsignedapplet.yes", "はい" }, { "appletprops.button.apply", "適用" }, { "appletprops.button.cancel", "取消" }, { "appletprops.button.reset", "リセット" }, { "appletprops.apply.exception", "プロパティ{0}の保存に失敗しました" }, { "appletprops.title.invalidproxy", "エントリが無効です" }, { "appletprops.label.invalidproxy", "プロキシ・ポートは正の整数値である必要があります。" }, { "appletprops.button.ok", "OK" }, { "appletprops.prop.store", "AppletViewer用のユーザーが指定したプロパティ" }, 
        { "appletsecurityexception.checkcreateclassloader", "セキュリティの例外: クラスローダー" }, { "appletsecurityexception.checkaccess.thread", "セキュリティの例外: スレッド" }, { "appletsecurityexception.checkaccess.threadgroup", "セキュリティの例外: スレッドグループ: {0}" }, { "appletsecurityexception.checkexit", "セキュリティの例外: 終了: {0}" }, { "appletsecurityexception.checkexec", "セキュリティの例外: 実行: {0}" }, { "appletsecurityexception.checklink", "セキュリティの例外: リンク: {0}" }, { "appletsecurityexception.checkpropsaccess", "セキュリティの例外: プロパティ" }, { "appletsecurityexception.checkpropsaccess.key", "セキュリティの例外: プロパティ・アクセス{0}" }, { "appletsecurityexception.checkread.exception1", "セキュリティの例外: {0}, {1}" }, { "appletsecurityexception.checkread.exception2", "セキュリティの例外: file.read: {0}" }, 
        { "appletsecurityexception.checkread", "セキュリティの例外: file.read: {0} == {1}" }, { "appletsecurityexception.checkwrite.exception", "セキュリティの例外: {0}, {1}" }, { "appletsecurityexception.checkwrite", "セキュリティの例外: file.write: {0} == {1}" }, { "appletsecurityexception.checkread.fd", "セキュリティの例外: fd.read" }, { "appletsecurityexception.checkwrite.fd", "セキュリティの例外: fd.write" }, { "appletsecurityexception.checklisten", "セキュリティの例外: socket.listen: {0}" }, { "appletsecurityexception.checkaccept", "セキュリティの例外: socket.accept: {0}:{1}" }, { "appletsecurityexception.checkconnect.networknone", "セキュリティの例外: socket.connect: {0}->{1}" }, { "appletsecurityexception.checkconnect.networkhost1", "セキュリティの例外: {1}の起点を使用して{0}に接続できませんでした。" }, { "appletsecurityexception.checkconnect.networkhost2", "セキュリティの例外: ホスト{0}または{1}のIPを解決できませんでした。 " }, 
        { "appletsecurityexception.checkconnect.networkhost3", "セキュリティの例外: ホスト{0}のIPを解決できませんでした。trustProxyプロパティを参照してください。" }, { "appletsecurityexception.checkconnect", "セキュリティの例外: 接続: {0}->{1}" }, { "appletsecurityexception.checkpackageaccess", "セキュリティの例外: パッケージにアクセスできません: {0}" }, { "appletsecurityexception.checkpackagedefinition", "セキュリティの例外: パッケージを定義できません: {0}" }, { "appletsecurityexception.cannotsetfactory", "セキュリティの例外: ファクトリを設定できません" }, { "appletsecurityexception.checkmemberaccess", "セキュリティの例外: メンバー・アクセスの確認" }, { "appletsecurityexception.checkgetprintjob", "セキュリティの例外: getPrintJob" }, { "appletsecurityexception.checksystemclipboardaccess", "セキュリティの例外: getSystemClipboard" }, { "appletsecurityexception.checkawteventqueueaccess", "セキュリティの例外: getEventQueue" }, { "appletsecurityexception.checksecurityaccess", "セキュリティの例外: セキュリティ操作: {0}" }, 
        { "appletsecurityexception.getsecuritycontext.unknown", "不明なクラスローダー・タイプです。getContextを確認できません" }, { "appletsecurityexception.checkread.unknown", "不明なクラスローダー・タイプです。{0}の読取りチェックを確認できません" }, { "appletsecurityexception.checkconnect.unknown", "不明なクラスローダー・タイプです。接続チェックを確認できません" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\applet\resources\MsgAppletViewer_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */