package sun.applet.resources;

import java.util.ListResourceBundle;

public class MsgAppletViewer_pt_BR extends ListResourceBundle {
  public Object[][] getContents() { return new Object[][] { 
        { "textframe.button.dismiss", "Rejeitar" }, { "appletviewer.tool.title", "Visualizador do Applet: {0}" }, { "appletviewer.menu.applet", "Applet" }, { "appletviewer.menuitem.restart", "Reiniciar" }, { "appletviewer.menuitem.reload", "Recarregar" }, { "appletviewer.menuitem.stop", "Interromper" }, { "appletviewer.menuitem.save", "Salvar" }, { "appletviewer.menuitem.start", "Iniciar" }, { "appletviewer.menuitem.clone", "Clonar..." }, { "appletviewer.menuitem.tag", "Tag..." }, 
        { "appletviewer.menuitem.info", "Informações..." }, { "appletviewer.menuitem.edit", "Editar" }, { "appletviewer.menuitem.encoding", "Codificação do Caractere" }, { "appletviewer.menuitem.print", "Imprimir..." }, { "appletviewer.menuitem.props", "Propriedades..." }, { "appletviewer.menuitem.close", "Fechar" }, { "appletviewer.menuitem.quit", "Sair" }, { "appletviewer.label.hello", "Olá..." }, { "appletviewer.status.start", "iniciando o applet..." }, { "appletviewer.appletsave.filedialogtitle", "Serializar Applet no Arquivo" }, 
        { "appletviewer.appletsave.err1", "serializando um {0} para {1}" }, { "appletviewer.appletsave.err2", "no appletSave: {0}" }, { "appletviewer.applettag", "Tag mostrada" }, { "appletviewer.applettag.textframe", "Tag HTML do Applet" }, { "appletviewer.appletinfo.applet", "-- nenhuma informação do applet --" }, { "appletviewer.appletinfo.param", "-- sem informação de parâmetro --" }, { "appletviewer.appletinfo.textframe", "Informações do Applet" }, { "appletviewer.appletprint.fail", "Falha na impressão." }, { "appletviewer.appletprint.finish", "Impressão finalizada." }, { "appletviewer.appletprint.cancel", "Impressão cancelada." }, 
        { "appletviewer.appletencoding", "Codificação de Caractere: {0}" }, { "appletviewer.parse.warning.requiresname", "Advertência: a tag <param name=... value=...> requer um atributo de nome." }, { "appletviewer.parse.warning.paramoutside", "Advertência: a tag <param> externa <applet> ... </applet>." }, { "appletviewer.parse.warning.applet.requirescode", "Advertência: a tag <applet> requer um atributo de código." }, { "appletviewer.parse.warning.applet.requiresheight", "Advertência: a tag <applet> requer um atributo de altura." }, { "appletviewer.parse.warning.applet.requireswidth", "Advertência: a tag <applet> requer um atributo de largura." }, { "appletviewer.parse.warning.object.requirescode", "Advertência: a tag <object> requer um atributo de código." }, { "appletviewer.parse.warning.object.requiresheight", "Advertência: a tag <object> requer um atributo de altura." }, { "appletviewer.parse.warning.object.requireswidth", "Advertência: a tag <object> requer um atributo de largura." }, { "appletviewer.parse.warning.embed.requirescode", "Advertência: a tag <embed> requer um atributo de código." }, 
        { "appletviewer.parse.warning.embed.requiresheight", "Advertência: a tag <embed> requer um atributo de altura." }, { "appletviewer.parse.warning.embed.requireswidth", "Advertência: a tag <embed> requer um atributo de largura." }, { "appletviewer.parse.warning.appnotLongersupported", "Advertência: a tag <app> não é mais suportada; use <applet>:" }, { "appletviewer.usage", "Uso: appletviewer <opções> url(s)\n\nem que as <opções> incluem:\n  -debug                  Inicia o visualizador do applet no depurador Java\n  -encoding <codificação>    Especifica a codificação de caractere usada pelos arquivos HTML\n  -J<flag de runtime>        Informa o argumento ao intepretador java\n\nA opção -J não é padrão e está sujeita à alteração sem notificação." }, { "appletviewer.main.err.unsupportedopt", "Opção não suportada: {0}" }, { "appletviewer.main.err.unrecognizedarg", "Argumento não reconhecido: {0}" }, { "appletviewer.main.err.dupoption", "Uso duplicado da opção: {0}" }, { "appletviewer.main.err.inputfile", "Nenhum arquivo de entrada especificado." }, { "appletviewer.main.err.badurl", "URL Inválido: {0} ( {1} )" }, { "appletviewer.main.err.io", "Exceção de E/S ao ler: {0}" }, 
        { "appletviewer.main.err.readablefile", "Certifique-se de que {0} seja um arquivo e seja legível." }, { "appletviewer.main.err.correcturl", "O URL {0} está correto?" }, { "appletviewer.main.prop.store", "Propriedades específicas do usuário do AppletViewer" }, { "appletviewer.main.err.prop.cantread", "Não é possível ler o arquivo de propriedades do usuário: {0}" }, { "appletviewer.main.err.prop.cantsave", "Não é possível salvar o arquivo de propriedades do usuário: {0}" }, { "appletviewer.main.warn.nosecmgr", "Advertência: desativando a segurança." }, { "appletviewer.main.debug.cantfinddebug", "Não é possível localizar o depurador!" }, { "appletviewer.main.debug.cantfindmain", "Não é possível localizar o método main no depurador!" }, { "appletviewer.main.debug.exceptionindebug", "Exceção no depurador!" }, { "appletviewer.main.debug.cantaccess", "Não é possível acessar o depurador!" }, 
        { "appletviewer.main.nosecmgr", "Advertência: SecurityManager não instalado!" }, { "appletviewer.main.warning", "Advertência: Nenhum applet iniciado. Certifique-se de que a entrada contenha uma tag <applet>." }, { "appletviewer.main.warn.prop.overwrite", "Advertência: Substituindo a propriedade do sistema temporariamente a pedido do usuário: chave: {0} valor antigo: {1} valor novo: {2}" }, { "appletviewer.main.warn.cantreadprops", "Advertência: Não é possível ler o arquivo de propriedades AppletViewer: {0} Usando padrões." }, { "appletioexception.loadclass.throw.interrupted", "carregamento de classe interrompido: {0}" }, { "appletioexception.loadclass.throw.notloaded", "classe não carregada: {0}" }, { "appletclassloader.loadcode.verbose", "Fluxo de abertura para: {0} para obter {1}" }, { "appletclassloader.filenotfound", "Arquivo não encontrado ao procurar: {0}" }, { "appletclassloader.fileformat", "Exceção de formato do arquivo ao carregar: {0}" }, { "appletclassloader.fileioexception", "Exceção de E/S ao carregar: {0}" }, 
        { "appletclassloader.fileexception", "exceção de {0} ao carregar: {1}" }, { "appletclassloader.filedeath", "{0} eliminado ao carregar: {1}" }, { "appletclassloader.fileerror", "erro de {0} ao carregar: {1}" }, { "appletclassloader.findclass.verbose.openstream", "Fluxo de abertura para: {0} para obter {1}" }, { "appletclassloader.getresource.verbose.forname", "AppletClassLoader.getResource do nome: {0}" }, { "appletclassloader.getresource.verbose.found", "Recurso encontrado: {0} como um recurso do sistema" }, { "appletclassloader.getresourceasstream.verbose", "Recurso encontrado: {0} como um recurso do sistema" }, { "appletpanel.runloader.err", "Parâmetro de código ou objeto!" }, { "appletpanel.runloader.exception", "exceção ao desserializar {0}" }, { "appletpanel.destroyed", "Applet destruído." }, 
        { "appletpanel.loaded", "Applet carregado." }, { "appletpanel.started", "Applet iniciado." }, { "appletpanel.inited", "Applet inicializado." }, { "appletpanel.stopped", "Applet interrompido." }, { "appletpanel.disposed", "Applet descartado." }, { "appletpanel.nocode", "A tag APPLET não encontrou o parâmetro CODE." }, { "appletpanel.notfound", "carga: classe {0} não encontrada." }, { "appletpanel.nocreate", "carga: {0} não pode ser instanciada." }, { "appletpanel.noconstruct", "carga: {0} não é pública ou não tem construtor público." }, { "appletpanel.death", "eliminado" }, 
        { "appletpanel.exception", "exceção: {0}." }, { "appletpanel.exception2", "exceção: {0}: {1}." }, { "appletpanel.error", "erro: {0}." }, { "appletpanel.error2", "erro: {0}: {1}." }, { "appletpanel.notloaded", "Inic: applet não carregado." }, { "appletpanel.notinited", "Iniciar: applet não inicializado." }, { "appletpanel.notstarted", "Interromper: applet não inicializado." }, { "appletpanel.notstopped", "Destruir: applet não interrompido." }, { "appletpanel.notdestroyed", "Descartar: applet não destruído." }, { "appletpanel.notdisposed", "Carregar: applet não descartado." }, 
        { "appletpanel.bail", "Interrompido: esvaziando." }, { "appletpanel.filenotfound", "Arquivo não encontrado ao procurar: {0}" }, { "appletpanel.fileformat", "Exceção de formato do arquivo ao carregar: {0}" }, { "appletpanel.fileioexception", "Exceção de E/S ao carregar: {0}" }, { "appletpanel.fileexception", "exceção de {0} ao carregar: {1}" }, { "appletpanel.filedeath", "{0} eliminado ao carregar: {1}" }, { "appletpanel.fileerror", "erro de {0} ao carregar: {1}" }, { "appletpanel.badattribute.exception", "Parsing de HTML: valor incorreto do atributo de largura/altura" }, { "appletillegalargumentexception.objectinputstream", "AppletObjectInputStream requer um carregador não nulo" }, { "appletprops.title", "Propriedades do AppletViewer" }, 
        { "appletprops.label.http.server", "Servidor proxy Http:" }, { "appletprops.label.http.proxy", "Porta proxy Http:" }, { "appletprops.label.network", "Acesso de rede:" }, { "appletprops.choice.network.item.none", "Nenhum" }, { "appletprops.choice.network.item.applethost", "Host do Applet" }, { "appletprops.choice.network.item.unrestricted", "Irrestrito" }, { "appletprops.label.class", "Acesso à classe:" }, { "appletprops.choice.class.item.restricted", "Restrito" }, { "appletprops.choice.class.item.unrestricted", "Irrestrito" }, { "appletprops.label.unsignedapplet", "Permitir applets não assinados:" }, 
        { "appletprops.choice.unsignedapplet.no", "Não" }, { "appletprops.choice.unsignedapplet.yes", "Sim" }, { "appletprops.button.apply", "Aplicar" }, { "appletprops.button.cancel", "Cancelar" }, { "appletprops.button.reset", "Redefinir" }, { "appletprops.apply.exception", "Falha ao salvar as propriedades: {0}" }, { "appletprops.title.invalidproxy", "Entrada Inválida" }, { "appletprops.label.invalidproxy", "A Porta Proxy deve ser um valor inteiro positivo." }, { "appletprops.button.ok", "OK" }, { "appletprops.prop.store", "Propriedades específicas do usuário do AppletViewer" }, 
        { "appletsecurityexception.checkcreateclassloader", "Exceção de Segurança: carregador de classes" }, { "appletsecurityexception.checkaccess.thread", "Exceção de Segurança: thread" }, { "appletsecurityexception.checkaccess.threadgroup", "Exceção de Segurança: grupo de threads: {0}" }, { "appletsecurityexception.checkexit", "Exceção de Segurança: saída: {0}" }, { "appletsecurityexception.checkexec", "Exceção de Segurança: exec.: {0}" }, { "appletsecurityexception.checklink", "Exceção de Segurança: link: {0}" }, { "appletsecurityexception.checkpropsaccess", "Exceção de Segurança: propriedades" }, { "appletsecurityexception.checkpropsaccess.key", "Exceção de Segurança: acesso às propriedades {0}" }, { "appletsecurityexception.checkread.exception1", "Exceção de Segurança: {0}, {1}" }, { "appletsecurityexception.checkread.exception2", "Exceção de Segurança: file.read: {0}" }, 
        { "appletsecurityexception.checkread", "Exceção de Segurança: file.read: {0} == {1}" }, { "appletsecurityexception.checkwrite.exception", "Exceção de Segurança: {0}, {1}" }, { "appletsecurityexception.checkwrite", "Exceção de Segurança: file.write: {0} == {1}" }, { "appletsecurityexception.checkread.fd", "Exceção de Segurança: fd.read" }, { "appletsecurityexception.checkwrite.fd", "Exceção de Segurança: fd.write" }, { "appletsecurityexception.checklisten", "Exceção de Segurança: socket.listen: {0}" }, { "appletsecurityexception.checkaccept", "Exceção de Segurança: socket.accept: {0}:{1}" }, { "appletsecurityexception.checkconnect.networknone", "Exceção de Segurança: socket.connect: {0}->{1}" }, { "appletsecurityexception.checkconnect.networkhost1", "Exceção de Segurança: Não foi possível estabelecer conexão com {0} com a origem de {1}." }, { "appletsecurityexception.checkconnect.networkhost2", "Exceção de Segurança: Não foi possível resolver o IP para o host {0} ou para {1}. " }, 
        { "appletsecurityexception.checkconnect.networkhost3", "Exceção de Segurança: Não foi possível resolver o IP para o host {0}. Consulte a propriedade trustProxy." }, { "appletsecurityexception.checkconnect", "Exceção de Segurança: conectar: {0}->{1}" }, { "appletsecurityexception.checkpackageaccess", "Exceção de Segurança: não é possível acessar o pacote: {0}" }, { "appletsecurityexception.checkpackagedefinition", "Exceção de Segurança: não é possível definir o pacote: {0}" }, { "appletsecurityexception.cannotsetfactory", "Exceção de Segurança: não é possível definir o factory" }, { "appletsecurityexception.checkmemberaccess", "Exceção de Segurança: verificar acesso do membro" }, { "appletsecurityexception.checkgetprintjob", "Exceção de Segurança: getPrintJob" }, { "appletsecurityexception.checksystemclipboardaccess", "Exceção de Segurança: getSystemClipboard" }, { "appletsecurityexception.checkawteventqueueaccess", "Exceção de Segurança: getEventQueue" }, { "appletsecurityexception.checksecurityaccess", "Exceção de Segurança: operação de segurança: {0}" }, 
        { "appletsecurityexception.getsecuritycontext.unknown", "tipo de carregador de classe desconhecido. não é possível verificar getContext" }, { "appletsecurityexception.checkread.unknown", "tipo de carregador de classe desconhecido. não é possível verificar a leitura {0}" }, { "appletsecurityexception.checkconnect.unknown", "tipo de carregador de classe desconhecido. não é possível verificar a conexão" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\applet\resources\MsgAppletViewer_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */