package sun.applet.resources;

import java.util.ListResourceBundle;

public class MsgAppletViewer_fr extends ListResourceBundle {
  public Object[][] getContents() { return new Object[][] { 
        { "textframe.button.dismiss", "Abandonner" }, { "appletviewer.tool.title", "Visualiseur d''applets : {0}" }, { "appletviewer.menu.applet", "Applet" }, { "appletviewer.menuitem.restart", "Redémarrer" }, { "appletviewer.menuitem.reload", "Recharger" }, { "appletviewer.menuitem.stop", "Arrêter" }, { "appletviewer.menuitem.save", "Enregistrer..." }, { "appletviewer.menuitem.start", "Démarrer" }, { "appletviewer.menuitem.clone", "Cloner..." }, { "appletviewer.menuitem.tag", "Baliser..." }, 
        { "appletviewer.menuitem.info", "Informations..." }, { "appletviewer.menuitem.edit", "Modifier" }, { "appletviewer.menuitem.encoding", "Encodage de caractères" }, { "appletviewer.menuitem.print", "Imprimer..." }, { "appletviewer.menuitem.props", "Propriétés..." }, { "appletviewer.menuitem.close", "Fermer" }, { "appletviewer.menuitem.quit", "Quitter" }, { "appletviewer.label.hello", "Bonjour..." }, { "appletviewer.status.start", "démarrage de l'applet..." }, { "appletviewer.appletsave.filedialogtitle", "Sérialiser l'applet dans le fichier" }, 
        { "appletviewer.appletsave.err1", "Sérialisation de {0} vers {1}" }, { "appletviewer.appletsave.err2", "dans appletSave : {0}" }, { "appletviewer.applettag", "Balise affichée" }, { "appletviewer.applettag.textframe", "Balise HTML d'applet" }, { "appletviewer.appletinfo.applet", "-- aucune information d'applet --" }, { "appletviewer.appletinfo.param", "-- aucune information de paramètre --" }, { "appletviewer.appletinfo.textframe", "Informations d'applet" }, { "appletviewer.appletprint.fail", "Echec de l'impression." }, { "appletviewer.appletprint.finish", "Impression terminée." }, { "appletviewer.appletprint.cancel", "Impression annulée." }, 
        { "appletviewer.appletencoding", "Encodage de caractères : {0}" }, { "appletviewer.parse.warning.requiresname", "Avertissement : la balise <param name=... value=...> requiert un attribut de nom." }, { "appletviewer.parse.warning.paramoutside", "Avertissement : la balise <param> est en dehors des balises <applet> ... </applet>." }, { "appletviewer.parse.warning.applet.requirescode", "Avertissement : la balise <applet> requiert un attribut de code." }, { "appletviewer.parse.warning.applet.requiresheight", "Avertissement : la balise <applet> requiert un attribut de hauteur." }, { "appletviewer.parse.warning.applet.requireswidth", "Avertissement : la balise <applet> requiert un attribut de largeur." }, { "appletviewer.parse.warning.object.requirescode", "Avertissement : la balise <object> requiert un attribut de code." }, { "appletviewer.parse.warning.object.requiresheight", "Avertissement : la balise <object> requiert un attribut de hauteur." }, { "appletviewer.parse.warning.object.requireswidth", "Avertissement : la balise <object> requiert un attribut de largeur." }, { "appletviewer.parse.warning.embed.requirescode", "Avertissement : la balise <embed> requiert un attribut de code." }, 
        { "appletviewer.parse.warning.embed.requiresheight", "Avertissement : la balise <embed> requiert un attribut de hauteur." }, { "appletviewer.parse.warning.embed.requireswidth", "Avertissement : la balise <embed> requiert un attribut de largeur." }, { "appletviewer.parse.warning.appnotLongersupported", "Avertissement : la balise <app> n'est plus prise en charge, utilisez <applet> à la place :" }, { "appletviewer.usage", "Syntaxe : appletviewer <options> url(s)\n\noù <options> inclut :\n  -debug                  Démarrer le visualiseur d'applets dans le débogueur Java\n  -encoding <encoding>    Indiquer l'encodage de caractères utilisé par les fichiers HTML\n  -J<runtime flag>        Transmettre l'argument à l'interpréteur Java\n\nL'option -J n'est pas standard et elle peut être modifiée sans préavis." }, { "appletviewer.main.err.unsupportedopt", "Option non prise en charge : {0}" }, { "appletviewer.main.err.unrecognizedarg", "Argument non reconnu : {0}" }, { "appletviewer.main.err.dupoption", "Utilisation en double de l''option : {0}" }, { "appletviewer.main.err.inputfile", "Aucun fichier d'entrée indiqué." }, { "appletviewer.main.err.badurl", "URL incorrecte : {0} ({1})" }, { "appletviewer.main.err.io", "Exception d''E/S lors de la lecture : {0}" }, 
        { "appletviewer.main.err.readablefile", "Assurez-vous que {0} est un fichier accessible en lecture." }, { "appletviewer.main.err.correcturl", "L''élément {0} est-il l''URL correcte ?" }, { "appletviewer.main.prop.store", "Propriétés utilisateur pour AppletViewer" }, { "appletviewer.main.err.prop.cantread", "Impossible de lire le fichier de propriétés utilisateur : {0}" }, { "appletviewer.main.err.prop.cantsave", "Impossible d''enregistrer le fichier de propriétés utilisateur : {0}" }, { "appletviewer.main.warn.nosecmgr", "Avertissement : désactivation de la sécurité." }, { "appletviewer.main.debug.cantfinddebug", "Débogueur introuvable." }, { "appletviewer.main.debug.cantfindmain", "La méthode principale est introuvable dans le débogueur." }, { "appletviewer.main.debug.exceptionindebug", "Exception détectée dans le débogueur." }, { "appletviewer.main.debug.cantaccess", "Impossible d'accéder au débogueur." }, 
        { "appletviewer.main.nosecmgr", "Avertissement : SecurityManager n'est pas installé." }, { "appletviewer.main.warning", "Avertissement : aucune applet n'a été démarrée. Assurez-vous que l'entrée contient une balise <applet>." }, { "appletviewer.main.warn.prop.overwrite", "Avertissement : remplacement temporaire de la propriété système à la demande de l''utilisateur - Clé : {0}, ancienne valeur : {1}, nouvelle valeur : {2}" }, { "appletviewer.main.warn.cantreadprops", "Avertissement : impossible de lire le fichier de propriétés d''AppletViewer : {0} Utilisation des valeurs par défaut." }, { "appletioexception.loadclass.throw.interrupted", "chargement de classe interrompu : {0}" }, { "appletioexception.loadclass.throw.notloaded", "classe non chargée : {0}" }, { "appletclassloader.loadcode.verbose", "Ouverture du flux de données dans {0} pour obtenir {1}" }, { "appletclassloader.filenotfound", "Fichier introuvable lors de la recherche de {0}" }, { "appletclassloader.fileformat", "Exception de format de fichier détectée lors du chargement de : {0}" }, { "appletclassloader.fileioexception", "Exception d''E/S lors du chargement de : {0}" }, 
        { "appletclassloader.fileexception", "Exception {0} lors du chargement de : {1}" }, { "appletclassloader.filedeath", "Fermeture de {0} lors du chargement de : {1}" }, { "appletclassloader.fileerror", "Erreur {0} lors du chargement de : {1}" }, { "appletclassloader.findclass.verbose.openstream", "Ouverture du flux de données dans {0} pour obtenir {1}" }, { "appletclassloader.getresource.verbose.forname", "AppletClassLoader.getResource pour le nom : {0}" }, { "appletclassloader.getresource.verbose.found", "Ressource {0} trouvée en tant que ressource système" }, { "appletclassloader.getresourceasstream.verbose", "Ressource {0} trouvée en tant que ressource système" }, { "appletpanel.runloader.err", "Paramètre d'objet ou de code." }, { "appletpanel.runloader.exception", "exception lors de la désérialisation de {0}" }, { "appletpanel.destroyed", "Applet détruite." }, 
        { "appletpanel.loaded", "Applet chargée." }, { "appletpanel.started", "Applet démarrée." }, { "appletpanel.inited", "Applet initialisée." }, { "appletpanel.stopped", "Applet arrêtée." }, { "appletpanel.disposed", "Applet éliminée." }, { "appletpanel.nocode", "Paramètre CODE manquant dans la balise APPLET." }, { "appletpanel.notfound", "Charger : la classe {0} est introuvable." }, { "appletpanel.nocreate", "Charger : impossible d''instantier {0}." }, { "appletpanel.noconstruct", "Charger : l''élément {0} n''est pas public ou ne possède aucun constructeur public." }, { "appletpanel.death", "arrêté" }, 
        { "appletpanel.exception", "exception : {0}." }, { "appletpanel.exception2", "exception : {0} : {1}." }, { "appletpanel.error", "erreur : {0}." }, { "appletpanel.error2", "erreur : {0} : {1}." }, { "appletpanel.notloaded", "Initialiser : applet non chargée." }, { "appletpanel.notinited", "Démarrer : applet non initialisée." }, { "appletpanel.notstarted", "Arrêter : applet non démarrée." }, { "appletpanel.notstopped", "Détruire : applet non arrêtée." }, { "appletpanel.notdestroyed", "Eliminer : applet non détruite." }, { "appletpanel.notdisposed", "Charger : applet non éliminée." }, 
        { "appletpanel.bail", "Interrompu : résolution." }, { "appletpanel.filenotfound", "Fichier introuvable lors de la recherche de {0}" }, { "appletpanel.fileformat", "Exception de format de fichier détectée lors du chargement de : {0}" }, { "appletpanel.fileioexception", "Exception d''E/S lors du chargement de : {0}" }, { "appletpanel.fileexception", "Exception {0} lors du chargement de : {1}" }, { "appletpanel.filedeath", "Fermeture de {0} lors du chargement de : {1}" }, { "appletpanel.fileerror", "Erreur {0} lors du chargement de : {1}" }, { "appletpanel.badattribute.exception", "Analyse HTML : valeur incorrecte pour l'attribut de largeur/hauteur" }, { "appletillegalargumentexception.objectinputstream", "AppletObjectInputStream requiert un chargeur non NULL" }, { "appletprops.title", "Propriétés d'AppletViewer" }, 
        { "appletprops.label.http.server", "Serveur proxy HTTP :" }, { "appletprops.label.http.proxy", "Port proxy HTTP :" }, { "appletprops.label.network", "Accès au réseau :" }, { "appletprops.choice.network.item.none", "Aucun" }, { "appletprops.choice.network.item.applethost", "Hôte de l'applet" }, { "appletprops.choice.network.item.unrestricted", "Sans restriction" }, { "appletprops.label.class", "Accès à la classe :" }, { "appletprops.choice.class.item.restricted", "Avec restriction" }, { "appletprops.choice.class.item.unrestricted", "Sans restriction" }, { "appletprops.label.unsignedapplet", "Autoriser les applets non signées :" }, 
        { "appletprops.choice.unsignedapplet.no", "Non" }, { "appletprops.choice.unsignedapplet.yes", "Oui" }, { "appletprops.button.apply", "Appliquer" }, { "appletprops.button.cancel", "Annuler" }, { "appletprops.button.reset", "Réinitialiser" }, { "appletprops.apply.exception", "Echec de l''enregistrement des propriétés : {0}" }, { "appletprops.title.invalidproxy", "Entrée non valide" }, { "appletprops.label.invalidproxy", "Le port proxy doit être un entier positif." }, { "appletprops.button.ok", "OK" }, { "appletprops.prop.store", "Propriétés utilisateur pour AppletViewer" }, 
        { "appletsecurityexception.checkcreateclassloader", "Exception de sécurité : chargeur de classe" }, { "appletsecurityexception.checkaccess.thread", "Exception de sécurité : thread" }, { "appletsecurityexception.checkaccess.threadgroup", "Exception de sécurité : groupe de threads : {0}" }, { "appletsecurityexception.checkexit", "Exception de sécurité : sortie : {0}" }, { "appletsecurityexception.checkexec", "Exception de sécurité : exécution : {0}" }, { "appletsecurityexception.checklink", "Exception de sécurité : lien : {0}" }, { "appletsecurityexception.checkpropsaccess", "Exception de sécurité : propriétés" }, { "appletsecurityexception.checkpropsaccess.key", "Exception de sécurité : accès aux propriétés {0}" }, { "appletsecurityexception.checkread.exception1", "Exception de sécurité : {0}, {1}" }, { "appletsecurityexception.checkread.exception2", "Exception de sécurité : file.read : {0}" }, 
        { "appletsecurityexception.checkread", "Exception de sécurité : file.read : {0} == {1}" }, { "appletsecurityexception.checkwrite.exception", "Exception de sécurité : {0}, {1}" }, { "appletsecurityexception.checkwrite", "Exception de sécurité : file.write : {0} == {1}" }, { "appletsecurityexception.checkread.fd", "Exception de sécurité : fd.read" }, { "appletsecurityexception.checkwrite.fd", "Exception de sécurité : fd.write" }, { "appletsecurityexception.checklisten", "Exception de sécurité : socket.listen : {0}" }, { "appletsecurityexception.checkaccept", "Exception de sécurité : socket.accept : {0} : {1}" }, { "appletsecurityexception.checkconnect.networknone", "Exception de sécurité : socket.connect : {0} -> {1}" }, { "appletsecurityexception.checkconnect.networkhost1", "Exception de sécurité : impossible de se connecter à {0} dont l''origine est {1}." }, { "appletsecurityexception.checkconnect.networkhost2", "Exception de sécurité : impossible de résoudre l''adresse IP pour l''hôte {0} ou pour {1}. " }, 
        { "appletsecurityexception.checkconnect.networkhost3", "Exception de sécurité : impossible de résoudre l''adresse IP pour l''hôte {0}. Voir la propriété trustProxy." }, { "appletsecurityexception.checkconnect", "Exception de sécurité : connexion : {0} -> {1}" }, { "appletsecurityexception.checkpackageaccess", "Exception de sécurité : impossible d''accéder au package : {0}" }, { "appletsecurityexception.checkpackagedefinition", "Exception de sécurité : impossible de définir le package : {0}" }, { "appletsecurityexception.cannotsetfactory", "Exception de sécurité : impossible de définir la fabrique" }, { "appletsecurityexception.checkmemberaccess", "Exception de sécurité : vérifier l'accès des membres" }, { "appletsecurityexception.checkgetprintjob", "Exception de sécurité : getPrintJob" }, { "appletsecurityexception.checksystemclipboardaccess", "Exception de sécurité : getSystemClipboard" }, { "appletsecurityexception.checkawteventqueueaccess", "Exception de sécurité : getEventQueue" }, { "appletsecurityexception.checksecurityaccess", "Exception de sécurité : opération de sécurité : {0}" }, 
        { "appletsecurityexception.getsecuritycontext.unknown", "type de chargeur de classe inconnu, impossible de rechercher getContext" }, { "appletsecurityexception.checkread.unknown", "type de chargeur de classe inconnu, impossible de rechercher la vérification de lecture {0}" }, { "appletsecurityexception.checkconnect.unknown", "type de chargeur de classe inconnu, impossible de rechercher la vérification de connexion" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\applet\resources\MsgAppletViewer_fr.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */