package sun.management.resources;

import java.util.ListResourceBundle;

public final class agent_fr extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "agent.err.access.file.not.readable", "Fichier d'accès illisible" }, { "agent.err.access.file.notfound", "Fichier d'accès introuvable" }, { "agent.err.access.file.notset", "Le fichier d'accès n'est pas spécifié mais com.sun.management.jmxremote.authenticate=true" }, { "agent.err.access.file.read.failed", "Impossible de lire le fichier d'accès" }, { "agent.err.acl.file.access.notrestricted", "L'accès en lecture au fichier de mots de passe doit être limité" }, { "agent.err.acl.file.not.readable", "Fichier de liste de contrôle d'accès (ACL) SNMP illisible" }, { "agent.err.acl.file.notfound", "Fichier de liste de contrôle d'accès (ACL) SNMP introuvable" }, { "agent.err.acl.file.notset", "Aucun fichier de liste de contrôle d'accès (ACL) SNMP n'est spécifié mais com.sun.management.snmp.acl=true" }, { "agent.err.acl.file.read.failed", "Impossible de lire le fichier de liste de contrôle d'accès (ACL) SNMP" }, { "agent.err.agentclass.access.denied", "Accès à premain(String) refusé" }, 
        { "agent.err.agentclass.failed", "Echec de la classe d'agents de gestion " }, { "agent.err.agentclass.notfound", "Classe d'agents de gestion introuvable" }, { "agent.err.configfile.access.denied", "Accès refusé au fichier de configuration" }, { "agent.err.configfile.closed.failed", "Impossible de fermer le fichier de configuration" }, { "agent.err.configfile.failed", "Impossible de lire le fichier de configuration" }, { "agent.err.configfile.notfound", "Fichier de configuration introuvable" }, { "agent.err.connector.server.io.error", "Erreur de communication avec le serveur du connecteur JMX" }, { "agent.err.error", "Erreur" }, { "agent.err.exception", "Exception envoyée par l'agent " }, { "agent.err.exportaddress.failed", "Impossible d'exporter l'adresse du connecteur JMX dans le tampon d'instrumentation" }, 
        { "agent.err.file.access.not.restricted", "L'accès en lecture au fichier doit être limité" }, { "agent.err.file.not.found", "Fichier introuvable" }, { "agent.err.file.not.readable", "Fichier illisible" }, { "agent.err.file.not.set", "Fichier non spécifié" }, { "agent.err.file.read.failed", "Impossible de lire le fichier" }, { "agent.err.invalid.agentclass", "Valeur de propriété com.sun.management.agent.class incorrecte" }, { "agent.err.invalid.jmxremote.port", "Numéro com.sun.management.jmxremote.port incorrect" }, { "agent.err.invalid.jmxremote.rmi.port", "Numéro com.sun.management.jmxremote.rmi.port non valide" }, { "agent.err.invalid.option", "Option spécifiée non valide" }, { "agent.err.invalid.snmp.port", "Numéro com.sun.management.snmp.port incorrect" }, 
        { "agent.err.invalid.snmp.trap.port", "Numéro com.sun.management.snmp.trap incorrect" }, { "agent.err.invalid.state", "Etat de l''agent non valide : {0}" }, { "agent.err.password.file.access.notrestricted", "L'accès en lecture au fichier de mots de passe doit être limité" }, { "agent.err.password.file.not.readable", "Fichier de mots de passe illisible" }, { "agent.err.password.file.notfound", "Fichier de mots de passe introuvable" }, { "agent.err.password.file.notset", "Le fichier de mots de passe n'est pas spécifié mais com.sun.management.jmxremote.authenticate=true" }, { "agent.err.password.file.read.failed", "Impossible de lire le fichier de mots de passe" }, { "agent.err.premain.notfound", "premain(String) n'existe pas dans la classe d'agents" }, { "agent.err.snmp.adaptor.start.failed", "Impossible de démarrer l'adaptateur SNMP avec l'adresse" }, { "agent.err.snmp.mib.init.failed", "Impossible d'initialiser SNMP MIB avec l'erreur" }, 
        { "agent.err.unknown.snmp.interface", "Interface SNMP inconnue" }, { "agent.err.warning", "Avertissement" }, { "jmxremote.AdaptorBootstrap.getTargetList.adding", "Ajout de la cible : {0}" }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize1", "Adaptateur prêt." }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize2", "Adaptateur SNMP prêt sur : {0}:{1}" }, { "jmxremote.AdaptorBootstrap.getTargetList.processing", "Traitement de la liste de contrôle d'accès (ACL)" }, { "jmxremote.AdaptorBootstrap.getTargetList.starting", "Démarrage du serveur de l'adaptateur :" }, { "jmxremote.AdaptorBootstrap.getTargetList.terminate", "terminer {0}" }, { "jmxremote.ConnectorBootstrap.file.readonly", "L''accès en lecture au fichier doit être limité : {0}" }, { "jmxremote.ConnectorBootstrap.noAuthentication", "Pas d'authentification" }, 
        { "jmxremote.ConnectorBootstrap.password.readonly", "L''accès en lecture au fichier de mots de passe doit être limité : {0}" }, { "jmxremote.ConnectorBootstrap.ready", "Connecteur JMX prêt à : {0}" }, { "jmxremote.ConnectorBootstrap.starting", "Démarrage du serveur du connecteur JMX :" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\management\resources\agent_fr.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */