package sun.management.resources;

import java.util.ListResourceBundle;

public final class agent_pt_BR extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "agent.err.access.file.not.readable", "Arquivo de acesso ilegível" }, { "agent.err.access.file.notfound", "Arquivo de acesso não encontrado" }, { "agent.err.access.file.notset", "O arquivo de acesso não está especificado, mas com.sun.management.jmxremote.authenticate=true" }, { "agent.err.access.file.read.failed", "Falha ao ler o arquivo de acesso" }, { "agent.err.acl.file.access.notrestricted", "O acesso de leitura do arquivo de senha deve ser limitado" }, { "agent.err.acl.file.not.readable", "Arquivo ACL SNMP ilegível" }, { "agent.err.acl.file.notfound", "Arquivo ACL SNMP não encontrado" }, { "agent.err.acl.file.notset", "Não há um arquivo ACL SNMP especificado, mas com.sun.management.snmp.acl=true" }, { "agent.err.acl.file.read.failed", "Falha ao ler o arquivo ACL SNMP" }, { "agent.err.agentclass.access.denied", "Acesso negado a premain(String)" }, 
        { "agent.err.agentclass.failed", "Falha na classe do agente de gerenciamento " }, { "agent.err.agentclass.notfound", "Classe do agente de gerenciamento não encontrada" }, { "agent.err.configfile.access.denied", "Acesso negado ao arquivo de configuração" }, { "agent.err.configfile.closed.failed", "Falha ao fechar o arquivo de configuração" }, { "agent.err.configfile.failed", "Falha ao ler o arquivo de configuração" }, { "agent.err.configfile.notfound", "Arquivo de configuração não encontrado" }, { "agent.err.connector.server.io.error", "Erro de comunicação do servidor do conector JMX" }, { "agent.err.error", "Erro" }, { "agent.err.exception", "Exceção gerada pelo agente " }, { "agent.err.exportaddress.failed", "Falha na exportação do endereço do conector JMX para o buffer de instrumentação" }, 
        { "agent.err.file.access.not.restricted", "O acesso de leitura do arquivo deve ser limitado" }, { "agent.err.file.not.found", "Arquivo não encontrado" }, { "agent.err.file.not.readable", "Arquivo ilegível" }, { "agent.err.file.not.set", "Arquivo não especificado" }, { "agent.err.file.read.failed", "Falha ao ler o arquivo" }, { "agent.err.invalid.agentclass", "Valor inválido da propriedade com.sun.management.agent.class" }, { "agent.err.invalid.jmxremote.port", "Número inválido de com.sun.management.jmxremote.port" }, { "agent.err.invalid.jmxremote.rmi.port", "Número inválido do com.sun.management.jmxremote.rmi.port" }, { "agent.err.invalid.option", "Opção especificada inválida" }, { "agent.err.invalid.snmp.port", "Número inválido de com.sun.management.snmp.port" }, 
        { "agent.err.invalid.snmp.trap.port", "Número inválido de com.sun.management.snmp.trap" }, { "agent.err.invalid.state", "Estado inválido do agente: {0}" }, { "agent.err.password.file.access.notrestricted", "O acesso de leitura do arquivo de senha deve ser limitado" }, { "agent.err.password.file.not.readable", "Arquivo de senha ilegível" }, { "agent.err.password.file.notfound", "Arquivo de senha não encontrado" }, { "agent.err.password.file.notset", "O arquivo de senha não está especificado, mas com.sun.management.jmxremote.authenticate=true" }, { "agent.err.password.file.read.failed", "Falha ao ler o arquivo de senha" }, { "agent.err.premain.notfound", "premain(String) não existe na classe do agente" }, { "agent.err.snmp.adaptor.start.failed", "Falha ao iniciar o adaptador SNMP com endereço" }, { "agent.err.snmp.mib.init.failed", "Falha ao inicializar o MIB SNMP com erro" }, 
        { "agent.err.unknown.snmp.interface", "Interface SNMP desconhecida" }, { "agent.err.warning", "Advertência" }, { "jmxremote.AdaptorBootstrap.getTargetList.adding", "Adicionando destino: {0}" }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize1", "Adaptador pronto." }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize2", "Adaptador SNMP pronto em: {0}:{1}" }, { "jmxremote.AdaptorBootstrap.getTargetList.processing", "Processando ACL" }, { "jmxremote.AdaptorBootstrap.getTargetList.starting", "Iniciando o Servidor do Adaptador:" }, { "jmxremote.AdaptorBootstrap.getTargetList.terminate", "encerrar {0}" }, { "jmxremote.ConnectorBootstrap.file.readonly", "O acesso de leitura do arquivo deve ser limitado: {0}" }, { "jmxremote.ConnectorBootstrap.noAuthentication", "Sem autenticação" }, 
        { "jmxremote.ConnectorBootstrap.password.readonly", "O acesso de leitura do arquivo de senha deve ser limitado: {0}" }, { "jmxremote.ConnectorBootstrap.ready", "Conector JMX pronto em: {0}" }, { "jmxremote.ConnectorBootstrap.starting", "Iniciando o Servidor do Conector JMX:" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\management\resources\agent_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */