package sun.management.resources;

import java.util.ListResourceBundle;

public final class agent_ja extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "agent.err.access.file.not.readable", "アクセス・ファイルを読み取ることができません" }, { "agent.err.access.file.notfound", "アクセス・ファイルが見つかりません" }, { "agent.err.access.file.notset", "アクセス・ファイルが指定されていませんが、com.sun.management.jmxremote.authenticate=trueが設定されています" }, { "agent.err.access.file.read.failed", "アクセス・ファイルの読取りに失敗しました" }, { "agent.err.acl.file.access.notrestricted", "パスワード・ファイルの読取りアクセスは制限する必要があります" }, { "agent.err.acl.file.not.readable", "SNMP ACLファイルを読み取ることができません" }, { "agent.err.acl.file.notfound", "SNMP ACLファイルが見つかりません" }, { "agent.err.acl.file.notset", "SNMP ACLファイルが指定されていませんが、com.sun.management.snmp.acl=trueが設定されています" }, { "agent.err.acl.file.read.failed", "SNMP ACLファイルの読取りに失敗しました" }, { "agent.err.agentclass.access.denied", "premain(String)へのアクセスが拒否されました" }, 
        { "agent.err.agentclass.failed", "管理エージェント・クラスが失敗しました " }, { "agent.err.agentclass.notfound", "管理エージェント・クラスが見つかりません" }, { "agent.err.configfile.access.denied", "構成ファイルへのアクセスが拒否されました" }, { "agent.err.configfile.closed.failed", "構成ファイルを閉じることができませんでした" }, { "agent.err.configfile.failed", "構成ファイルの読取りに失敗しました" }, { "agent.err.configfile.notfound", "構成ファイルが見つかりません" }, { "agent.err.connector.server.io.error", "JMXコネクタ・サーバーの通信エラー" }, { "agent.err.error", "エラー" }, { "agent.err.exception", "エージェントが例外をスローしました " }, { "agent.err.exportaddress.failed", "JMXコネクタ・アドレスの計測バッファへのエクスポートが失敗しました" }, 
        { "agent.err.file.access.not.restricted", "ファイルの読取りアクセスは制限する必要があります" }, { "agent.err.file.not.found", "ファイルが見つかりませんでした" }, { "agent.err.file.not.readable", "ファイルを読み取ることができません" }, { "agent.err.file.not.set", "ファイルが指定されていません" }, { "agent.err.file.read.failed", "ファイルの読取りに失敗しました" }, { "agent.err.invalid.agentclass", "com.sun.management.agent.classプロパティの値が無効です" }, { "agent.err.invalid.jmxremote.port", "com.sun.management.jmxremote.portの番号が無効です" }, { "agent.err.invalid.jmxremote.rmi.port", "com.sun.management.jmxremote.rmi.portの番号が無効です" }, { "agent.err.invalid.option", "無効なオプションが指定されました" }, { "agent.err.invalid.snmp.port", "com.sun.management.snmp.portの番号が無効です" }, 
        { "agent.err.invalid.snmp.trap.port", "com.sun.management.snmp.trapの番号が無効です" }, { "agent.err.invalid.state", "エージェントの状態が無効です: {0}" }, { "agent.err.password.file.access.notrestricted", "パスワード・ファイルの読取りアクセスは制限する必要があります" }, { "agent.err.password.file.not.readable", "パスワード・ファイルを読み取ることができません" }, { "agent.err.password.file.notfound", "パスワード・ファイルが見つかりません" }, { "agent.err.password.file.notset", "パスワード・ファイルが指定されていませんが、com.sun.management.jmxremote.authenticate=trueが設定されています" }, { "agent.err.password.file.read.failed", "パスワード・ファイルの読取りに失敗しました" }, { "agent.err.premain.notfound", "premain(String)がエージェント・クラスに存在しません" }, { "agent.err.snmp.adaptor.start.failed", "このアドレスでSNMPアダプタを開始できませんでした" }, { "agent.err.snmp.mib.init.failed", "エラーでSNMP MIBを初期化できませんでした" }, 
        { "agent.err.unknown.snmp.interface", "不明なSNMPインタフェースです" }, { "agent.err.warning", "警告" }, { "jmxremote.AdaptorBootstrap.getTargetList.adding", "ターゲットを追加しています: {0}" }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize1", "アダプタの準備ができました。" }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize2", "SNMPアダプタの準備ができました: {0}:{1}" }, { "jmxremote.AdaptorBootstrap.getTargetList.processing", "ACLを処理しています" }, { "jmxremote.AdaptorBootstrap.getTargetList.starting", "アダプタ・サーバーを起動しています:" }, { "jmxremote.AdaptorBootstrap.getTargetList.terminate", "{0}を終了します" }, { "jmxremote.ConnectorBootstrap.file.readonly", "ファイルの読取りアクセスは制限する必要があります: {0}" }, { "jmxremote.ConnectorBootstrap.noAuthentication", "認証なし" }, 
        { "jmxremote.ConnectorBootstrap.password.readonly", "パスワード・ファイルの読取りアクセスは制限する必要があります: {0}" }, { "jmxremote.ConnectorBootstrap.ready", "JMXコネクタの準備ができました: {0}" }, { "jmxremote.ConnectorBootstrap.starting", "JMXコネクタ・サーバーを起動しています:" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\management\resources\agent_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */