package sun.management.resources;

import java.util.ListResourceBundle;

public final class agent_es extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "agent.err.access.file.not.readable", "No se puede leer el archivo de acceso" }, { "agent.err.access.file.notfound", "Archivo de acceso no encontrado" }, { "agent.err.access.file.notset", "El archivo de acceso no se ha especificado, pero com.sun.management.jmxremote.authenticate=true" }, { "agent.err.access.file.read.failed", "Fallo al leer el archivo de acceso" }, { "agent.err.acl.file.access.notrestricted", "Se debe restringir el acceso de lectura al archivo de contraseñas" }, { "agent.err.acl.file.not.readable", "No se puede leer el archivo ACL de SNMP" }, { "agent.err.acl.file.notfound", "Archivo ACL de SNMP no encontrado" }, { "agent.err.acl.file.notset", "No se ha especificado ningún archivo ACL de SNMP, pero com.sun.management.snmp.acl=true" }, { "agent.err.acl.file.read.failed", "Fallo al leer el archivo ACL de SNMP" }, { "agent.err.agentclass.access.denied", "Acceso denegado a premain(String)" }, 
        { "agent.err.agentclass.failed", "Fallo de clase de agente de gestión " }, { "agent.err.agentclass.notfound", "Clase de agente de gestión no encontrada" }, { "agent.err.configfile.access.denied", "Acceso denegado al archivo de configuración" }, { "agent.err.configfile.closed.failed", "Fallo al cerrar el archivo de configuración" }, { "agent.err.configfile.failed", "Fallo al leer el archivo de configuración" }, { "agent.err.configfile.notfound", "No se ha encontrado el archivo de configuración" }, { "agent.err.connector.server.io.error", "Error de comunicación con el servidor de conector JMX" }, { "agent.err.error", "Error" }, { "agent.err.exception", "Excepción devuelta por el agente " }, { "agent.err.exportaddress.failed", "Fallo al exportar la dirección del conector JMX al buffer de instrumentación" }, 
        { "agent.err.file.access.not.restricted", "El acceso de lectura al archivo debe ser restringido" }, { "agent.err.file.not.found", "Archivo no encontrado" }, { "agent.err.file.not.readable", "Archivo ilegible" }, { "agent.err.file.not.set", "Archivo no especificado" }, { "agent.err.file.read.failed", "Fallo al leer el archivo" }, { "agent.err.invalid.agentclass", "Valor de propiedad com.sun.management.agent.class no válido" }, { "agent.err.invalid.jmxremote.port", "Número com.sun.management.jmxremote.port no válido" }, { "agent.err.invalid.jmxremote.rmi.port", "Número com.sun.management.jmxremote.rmi.port no válido" }, { "agent.err.invalid.option", "Opción especificada no válida" }, { "agent.err.invalid.snmp.port", "Número de com.sun.management.snmp.port no válido" }, 
        { "agent.err.invalid.snmp.trap.port", "Número de com.sun.management.snmp.trap no válido" }, { "agent.err.invalid.state", "Estado de agente no válido: {0}" }, { "agent.err.password.file.access.notrestricted", "Se debe restringir el acceso de lectura al archivo de contraseñas" }, { "agent.err.password.file.not.readable", "No se puede leer el archivo de contraseñas" }, { "agent.err.password.file.notfound", "Archivo de contraseñas no encontrado" }, { "agent.err.password.file.notset", "El archivo de contraseñas no se ha especificado, pero com.sun.management.jmxremote.authenticate=true" }, { "agent.err.password.file.read.failed", "Fallo al leer el archivo de contraseñas" }, { "agent.err.premain.notfound", "premain(String) no existe en la clase del agente" }, { "agent.err.snmp.adaptor.start.failed", "Fallo al iniciar el adaptador de SNMP con la dirección" }, { "agent.err.snmp.mib.init.failed", "Fallo al inicializar el MIB de SNMP con error" }, 
        { "agent.err.unknown.snmp.interface", "Interfaz SNMP desconocida" }, { "agent.err.warning", "Advertencia" }, { "jmxremote.AdaptorBootstrap.getTargetList.adding", "Agregando destino: {0}" }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize1", "Adaptador listo." }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize2", "Adaptador SNMP listo en: {0}:{1}" }, { "jmxremote.AdaptorBootstrap.getTargetList.processing", "Procesando ACL" }, { "jmxremote.AdaptorBootstrap.getTargetList.starting", "Iniciando servidor de adaptador:" }, { "jmxremote.AdaptorBootstrap.getTargetList.terminate", "terminar {0}" }, { "jmxremote.ConnectorBootstrap.file.readonly", "El acceso de lectura al archivo debe ser restringido: {0}" }, { "jmxremote.ConnectorBootstrap.noAuthentication", "Sin autenticación" }, 
        { "jmxremote.ConnectorBootstrap.password.readonly", "Se debe restringir el acceso de lectura al archivo de contraseñas: {0}" }, { "jmxremote.ConnectorBootstrap.ready", "Conector JMX listo en: {0}" }, { "jmxremote.ConnectorBootstrap.starting", "Iniciando servidor de conector JMX:" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\management\resources\agent_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */