package sun.management.resources;

import java.util.ListResourceBundle;

public final class agent_ko extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "agent.err.access.file.not.readable", "액세스 파일을 읽을 수 없습니다." }, { "agent.err.access.file.notfound", "액세스 파일을 찾을 수 없습니다." }, { "agent.err.access.file.notset", "액세스 파일이 지정되지 않았지만 com.sun.management.jmxremote.authenticate=true입니다." }, { "agent.err.access.file.read.failed", "액세스 파일 읽기를 실패했습니다." }, { "agent.err.acl.file.access.notrestricted", "비밀번호 파일 읽기 액세스는 제한되어야 합니다." }, { "agent.err.acl.file.not.readable", "SNMP ACL 파일을 읽을 수 없습니다." }, { "agent.err.acl.file.notfound", "SNMP ACL 파일을 찾을 수 없습니다." }, { "agent.err.acl.file.notset", "SNMP ACL 파일이 지정되지 않았지만 com.sun.management.snmp.acl=true입니다." }, { "agent.err.acl.file.read.failed", "SNMP ACL 파일 읽기를 실패했습니다." }, { "agent.err.agentclass.access.denied", "premain(문자열)에 대한 액세스가 거부되었습니다." }, 
        { "agent.err.agentclass.failed", "관리 에이전트 클래스를 실패했습니다. " }, { "agent.err.agentclass.notfound", "관리 에이전트 클래스를 찾을 수 없습니다." }, { "agent.err.configfile.access.denied", "구성 파일에 대한 액세스가 거부되었습니다." }, { "agent.err.configfile.closed.failed", "구성 파일 닫기를 실패했습니다." }, { "agent.err.configfile.failed", "구성 파일 읽기를 실패했습니다." }, { "agent.err.configfile.notfound", "구성 파일을 찾을 수 없습니다." }, { "agent.err.connector.server.io.error", "JMX 커넥터 서버 통신 오류" }, { "agent.err.error", "오류" }, { "agent.err.exception", "에이전트에 예외사항이 발생했습니다. " }, { "agent.err.exportaddress.failed", "기기 버퍼로 JMX 커넥터 주소 익스포트를 실패했습니다." }, 
        { "agent.err.file.access.not.restricted", "파일 읽기 액세스는 제한되어야 합니다." }, { "agent.err.file.not.found", "파일을 찾을 수 없습니다." }, { "agent.err.file.not.readable", "파일을 읽을 수 없습니다." }, { "agent.err.file.not.set", "파일이 지정되지 않았습니다." }, { "agent.err.file.read.failed", "파일 읽기를 실패했습니다." }, { "agent.err.invalid.agentclass", "com.sun.management.agent.class 속성 값이 부적합합니다." }, { "agent.err.invalid.jmxremote.port", "com.sun.management.jmxremote.port 번호가 부적합합니다." }, { "agent.err.invalid.jmxremote.rmi.port", "부적합한 com.sun.management.jmxremote.rmi.port 번호" }, { "agent.err.invalid.option", "부적합한 옵션이 지정되었습니다." }, { "agent.err.invalid.snmp.port", "com.sun.management.snmp.port 번호가 부적합합니다." }, 
        { "agent.err.invalid.snmp.trap.port", "com.sun.management.snmp.trap 번호가 부적합합니다." }, { "agent.err.invalid.state", "부적합한 에이전트 상태: {0}" }, { "agent.err.password.file.access.notrestricted", "비밀번호 파일 읽기 액세스는 제한되어야 합니다." }, { "agent.err.password.file.not.readable", "비밀번호 파일을 읽을 수 없습니다." }, { "agent.err.password.file.notfound", "비밀번호 파일을 찾을 수 없습니다." }, { "agent.err.password.file.notset", "비밀번호 파일이 지정되지 않았지만 com.sun.management.jmxremote.authenticate=true입니다." }, { "agent.err.password.file.read.failed", "비밀번호 파일 읽기를 실패했습니다." }, { "agent.err.premain.notfound", "에이전트 클래스에 premain(문자열)이 존재하지 않습니다." }, { "agent.err.snmp.adaptor.start.failed", "주소가 있는 SNMP 어댑터 시작을 실패했습니다." }, { "agent.err.snmp.mib.init.failed", "오류로 인해 SNMP MIB 초기화를 실패했습니다." }, 
        { "agent.err.unknown.snmp.interface", "알 수 없는 SNMP 인터페이스" }, { "agent.err.warning", "경고" }, { "jmxremote.AdaptorBootstrap.getTargetList.adding", "대상을 추가하는 중: {0}" }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize1", "어댑터가 준비되었습니다." }, { "jmxremote.AdaptorBootstrap.getTargetList.initialize2", "{0}:{1}에서 SNMP 어댑터가 준비되었습니다." }, { "jmxremote.AdaptorBootstrap.getTargetList.processing", "ACL을 처리하는 중" }, { "jmxremote.AdaptorBootstrap.getTargetList.starting", "어댑터 서버를 시작하는 중:" }, { "jmxremote.AdaptorBootstrap.getTargetList.terminate", "{0} 종료" }, { "jmxremote.ConnectorBootstrap.file.readonly", "파일 읽기 액세스는 제한되어야 함: {0}" }, { "jmxremote.ConnectorBootstrap.noAuthentication", "인증 없음" }, 
        { "jmxremote.ConnectorBootstrap.password.readonly", "비밀번호 파일 읽기 액세스는 제한되어야 함: {0}" }, { "jmxremote.ConnectorBootstrap.ready", "{0}에서 JMX 커넥터가 준비되었습니다." }, { "jmxremote.ConnectorBootstrap.starting", "JMX 커넥터 서버를 시작하는 중:" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\management\resources\agent_ko.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */