package sun.security.tools.policytool;

import java.util.ListResourceBundle;

public class Resources_pt_BR extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "NEWLINE", "\n" }, { "Warning.A.public.key.for.alias.signers.i.does.not.exist.Make.sure.a.KeyStore.is.properly.configured.", "Advertência: Não existe uma chave pública para o alias {0}. Certifique-se de que um KeyStore esteja configurado adequadamente." }, { "Warning.Class.not.found.class", "Advertência: Classe não encontrada: {0}" }, { "Warning.Invalid.argument.s.for.constructor.arg", "Advertência: Argumento(s) inválido(s) para o construtor: {0}" }, { "Illegal.Principal.Type.type", "Tipo Principal Inválido: {0}" }, { "Illegal.option.option", "Opção inválida: {0}" }, { "Usage.policytool.options.", "Uso: policytool [opções]" }, { ".file.file.policy.file.location", "  [-file <arquivo>]    localização do arquivo de política" }, { "New", "&Novo" }, { "Open", "&Abrir..." }, 
      { "Save", "&Salvar" }, { "Save.As", "Salvar c&omo..." }, { "View.Warning.Log", "E&xibir Log de Advertências" }, { "Exit", "S&air" }, { "Add.Policy.Entry", "&Adicionar Entrada de Política" }, { "Edit.Policy.Entry", "&Editar Entrada de Política" }, { "Remove.Policy.Entry", "&Remover Entrada de Política" }, { "Edit", "&Editar" }, { "Retain", "Reter" }, { "Warning.File.name.may.include.escaped.backslash.characters.It.is.not.necessary.to.escape.backslash.characters.the.tool.escapes", "Advertência: O nome do arquivo pode conter caracteres de escape barra invertida. Não é necessário fazer o escape dos caracteres de barra invertida (a ferramenta faz o escape dos caracteres conforme necessário ao gravar o conteúdo da política no armazenamento persistente).\n\nClique em Reter para reter o nome da entrada ou clique em Editar para editá-lo." }, 
      { "Add.Public.Key.Alias", "Adicionar Alias de Chave Pública" }, { "Remove.Public.Key.Alias", "Remover Alias de Chave Pública" }, { "File", "&Arquivo" }, { "KeyStore", "&KeyStore" }, { "Policy.File.", "Arquivo de Política:" }, { "Could.not.open.policy.file.policyFile.e.toString.", "Não foi possível abrir o arquivo de política: {0}: {1}" }, { "Policy.Tool", "Ferramenta de Política" }, { "Errors.have.occurred.while.opening.the.policy.configuration.View.the.Warning.Log.for.more.information.", "Erros durante a abertura da configuração da política. Consulte o Log de Advertências para obter mais informações." }, { "Error", "Erro" }, { "OK", "OK" }, 
      { "Status", "Status" }, { "Warning", "Advertência" }, { "Permission.", "Permissão:                                                       " }, { "Principal.Type.", "Tipo do Principal:" }, { "Principal.Name.", "Nome do Principal:" }, { "Target.Name.", "Nome do Alvo:                                                    " }, { "Actions.", "Ações:                                                             " }, { "OK.to.overwrite.existing.file.filename.", "Está correto substituir o arquivo existente {0}?" }, { "Cancel", "Cancelar" }, { "CodeBase.", "&CodeBase:" }, 
      { "SignedBy.", "&SignedBy:" }, { "Add.Principal", "&Adicionar Principal" }, { "Edit.Principal", "&Editar Principal" }, { "Remove.Principal", "&Remover Principal" }, { "Principals.", "&Principais:" }, { ".Add.Permission", "  A&dicionar Permissão" }, { ".Edit.Permission", "  Ed&itar Permissão" }, { "Remove.Permission", "Re&mover Permissão" }, { "Done", "Concluído" }, { "KeyStore.URL.", "&URL do KeyStore:" }, 
      { "KeyStore.Type.", "&Tipo de KeyStore:" }, { "KeyStore.Provider.", "&Fornecedor de KeyStore:" }, { "KeyStore.Password.URL.", "URL da Senha do Ke&yStore:" }, { "Principals", "Principais" }, { ".Edit.Principal.", "  Editar Principal:" }, { ".Add.New.Principal.", "  Adicionar Novo Principal:" }, { "Permissions", "Permissões" }, { ".Edit.Permission.", "  Editar Permissão:" }, { ".Add.New.Permission.", "  Adicionar Nova Permissão:" }, { "Signed.By.", "Assinado por:" }, 
      { "Cannot.Specify.Principal.with.a.Wildcard.Class.without.a.Wildcard.Name", "Não é Possível Especificar um Principal com uma Classe de Curinga sem um Nome de Curinga" }, { "Cannot.Specify.Principal.without.a.Name", "Não é Possível Especificar um Principal sem um Nome" }, { "Permission.and.Target.Name.must.have.a.value", "O Nome de Destino e a Permissão devem ter um Valor" }, { "Remove.this.Policy.Entry.", "Remover esta Entrada de Política?" }, { "Overwrite.File", "Substituir Arquivo" }, { "Policy.successfully.written.to.filename", "Política gravada com êxito em {0}" }, { "null.filename", "nome de arquivo nulo" }, { "Save.changes.", "Salvar alterações?" }, { "Yes", "&Sim" }, { "No", "&Não" }, 
      { "Policy.Entry", "Entrada de Política" }, { "Save.Changes", "Salvar Alterações" }, { "No.Policy.Entry.selected", "Nenhuma Entrada de Política Selecionada" }, { "Unable.to.open.KeyStore.ex.toString.", "Não é possível abrir a KeyStore: {0}" }, { "No.principal.selected", "Nenhum principal selecionado" }, { "No.permission.selected", "Nenhuma permissão selecionada" }, { "name", "nome" }, { "configuration.type", "tipo de configuração" }, { "environment.variable.name", "nome da variável de ambiente" }, { "library.name", "nome da biblioteca" }, 
      { "package.name", "nome do pacote" }, { "policy.type", "tipo de política" }, { "property.name", "nome da propriedade" }, { "provider.name", "nome do fornecedor" }, { "url", "url" }, { "method.list", "lista de métodos" }, { "request.headers.list", "solicitar lista de cabeçalhos" }, { "Principal.List", "Lista de Principais" }, { "Permission.List", "Lista de Permissões" }, { "Code.Base", "Base de Código" }, 
      { "KeyStore.U.R.L.", "U R L da KeyStore:" }, { "KeyStore.Password.U.R.L.", "U R L da Senha do KeyStore:" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\security\tools\policytool\Resources_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */