package sun.security.tools.policytool;

import java.util.ListResourceBundle;

public class Resources_es extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "NEWLINE", "\n" }, { "Warning.A.public.key.for.alias.signers.i.does.not.exist.Make.sure.a.KeyStore.is.properly.configured.", "Advertencia: no hay clave pública para el alias {0}. Asegúrese de que se ha configurado correctamente un almacén de claves." }, { "Warning.Class.not.found.class", "Advertencia: no se ha encontrado la clase: {0}" }, { "Warning.Invalid.argument.s.for.constructor.arg", "Advertencia: argumento(s) no válido(s) para el constructor: {0}" }, { "Illegal.Principal.Type.type", "Tipo de principal no permitido: {0}" }, { "Illegal.option.option", "Opción no permitida: {0}" }, { "Usage.policytool.options.", "Sintaxis: policytool [opciones]" }, { ".file.file.policy.file.location", "  [-file <archivo>]    ubicación del archivo de normas" }, { "New", "&Nueva" }, { "Open", "&Abrir..." }, 
      { "Save", "&Guardar" }, { "Save.As", "Guardar &como..." }, { "View.Warning.Log", "Ver &log de advertencias" }, { "Exit", "&Salir" }, { "Add.Policy.Entry", "Agregar &entrada de política" }, { "Edit.Policy.Entry", "E&ditar entrada de política" }, { "Remove.Policy.Entry", "&Eliminar entrada de política" }, { "Edit", "&Editar" }, { "Retain", "Mantener" }, { "Warning.File.name.may.include.escaped.backslash.characters.It.is.not.necessary.to.escape.backslash.characters.the.tool.escapes", "Advertencia: el nombre del archivo puede contener caracteres de barra invertida de escape. No es necesario utilizar barras invertidas de escape (la herramienta aplica caracteres de escape según sea necesario al escribir el contenido de las políticas en el almacén persistente).\n\nHaga clic en Mantener para conservar el nombre introducido o en Editar para modificarlo." }, 
      { "Add.Public.Key.Alias", "Agregar Alias de Clave Público" }, { "Remove.Public.Key.Alias", "Eliminar Alias de Clave Público" }, { "File", "&Archivo" }, { "KeyStore", "Al&macén de claves" }, { "Policy.File.", "Archivo de Política:" }, { "Could.not.open.policy.file.policyFile.e.toString.", "No se ha podido abrir el archivo de política: {0}: {1}" }, { "Policy.Tool", "Herramienta de Políticas" }, { "Errors.have.occurred.while.opening.the.policy.configuration.View.the.Warning.Log.for.more.information.", "Ha habido errores al abrir la configuración de políticas. Véase el log de advertencias para obtener más información." }, { "Error", "Error" }, { "OK", "Aceptar" }, 
      { "Status", "Estado" }, { "Warning", "Advertencia" }, { "Permission.", "Permiso:                                                       " }, { "Principal.Type.", "Tipo de Principal:" }, { "Principal.Name.", "Nombre de Principal:" }, { "Target.Name.", "Nombre de Destino:                                                    " }, { "Actions.", "Acciones:                                                             " }, { "OK.to.overwrite.existing.file.filename.", "¿Sobrescribir el archivo existente {0}?" }, { "Cancel", "Cancelar" }, { "CodeBase.", "&CodeBase:" }, 
      { "SignedBy.", "&SignedBy:" }, { "Add.Principal", "&Agregar principal" }, { "Edit.Principal", "&Editar principal" }, { "Remove.Principal", "Elimina&r principal" }, { "Principals.", "&Principales:" }, { ".Add.Permission", "A&gregar permiso" }, { ".Edit.Permission", "Ed&itar permiso" }, { "Remove.Permission", "Eli&minar permiso" }, { "Done", "Listo" }, { "KeyStore.URL.", "&URL de almacén de claves:" }, 
      { "KeyStore.Type.", "&Tipo de almacén de claves:" }, { "KeyStore.Provider.", "&Proveedor de almacén de claves:" }, { "KeyStore.Password.URL.", "URL de Contra&seña de almacén de claves:" }, { "Principals", "Principales" }, { ".Edit.Principal.", "  Editar Principal:" }, { ".Add.New.Principal.", "  Agregar Nuevo Principal:" }, { "Permissions", "Permisos" }, { ".Edit.Permission.", "  Editar Permiso:" }, { ".Add.New.Permission.", "  Agregar Permiso Nuevo:" }, { "Signed.By.", "Firmado Por:" }, 
      { "Cannot.Specify.Principal.with.a.Wildcard.Class.without.a.Wildcard.Name", "No se puede especificar un principal con una clase de comodín sin un nombre de comodín" }, { "Cannot.Specify.Principal.without.a.Name", "No se puede especificar el principal sin un nombre" }, { "Permission.and.Target.Name.must.have.a.value", "Permiso y Nombre de Destino deben tener un valor" }, { "Remove.this.Policy.Entry.", "¿Eliminar esta entrada de política?" }, { "Overwrite.File", "Sobrescribir Archivo" }, { "Policy.successfully.written.to.filename", "Política escrita correctamente en {0}" }, { "null.filename", "nombre de archivo nulo" }, { "Save.changes.", "¿Guardar los cambios?" }, { "Yes", "&Sí" }, { "No", "&No" }, 
      { "Policy.Entry", "Entrada de Política" }, { "Save.Changes", "Guardar Cambios" }, { "No.Policy.Entry.selected", "No se ha seleccionado la entrada de política" }, { "Unable.to.open.KeyStore.ex.toString.", "No se ha podido abrir el almacén de claves: {0}" }, { "No.principal.selected", "No se ha seleccionado un principal" }, { "No.permission.selected", "No se ha seleccionado un permiso" }, { "name", "nombre" }, { "configuration.type", "tipo de configuración" }, { "environment.variable.name", "nombre de variable de entorno" }, { "library.name", "nombre de la biblioteca" }, 
      { "package.name", "nombre del paquete" }, { "policy.type", "tipo de política" }, { "property.name", "nombre de la propiedad" }, { "provider.name", "nombre del proveedor" }, { "url", "url" }, { "method.list", "lista de métodos" }, { "request.headers.list", "lista de cabeceras de solicitudes" }, { "Principal.List", "Lista de Principales" }, { "Permission.List", "Lista de Permisos" }, { "Code.Base", "Base de Código" }, 
      { "KeyStore.U.R.L.", "URL de Almacén de Claves:" }, { "KeyStore.Password.U.R.L.", "URL de Contraseña de Almacén de Claves:" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\security\tools\policytool\Resources_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */