package sun.tools.jar.resources;

import java.util.ListResourceBundle;

public final class jar_es extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "error.bad.cflag", "El indicador 'c' necesita la especificación de archivos de manifiesto o de entrada." }, { "error.bad.eflag", "El indicador 'e' y el manifiesto con el atributo 'Main-Class' no pueden especificarse \na la vez." }, { "error.bad.option", "Se debe especificar una de las opciones -{ctxu}." }, { "error.bad.uflag", "El indicador 'u' necesita la especificación de archivos de manifiesto, de entrada o indicador 'e'." }, { "error.cant.open", "no se puede abrir: {0} " }, { "error.create.dir", "{0} : no se ha podido crear el directorio" }, { "error.create.tempfile", "No se ha podido crear el archivo temporal" }, { "error.illegal.option", "Opción no permitida: {0}" }, { "error.incorrect.length", "longitud incorrecta al procesar: {0}" }, { "error.nosuch.fileordir", "{0} : no existe tal archivo o directorio" }, 
        { "error.write.file", "Error al escribir un archivo jar existente" }, { "out.added.manifest", "manifiesto agregado" }, { "out.adding", "agregando: {0}" }, { "out.create", "  creado: {0}" }, { "out.deflated", "(desinflado {0}%)" }, { "out.extracted", "extraído: {0}" }, { "out.ignore.entry", "ignorando entrada {0}" }, { "out.inflated", " inflado: {0}" }, { "out.size", "(entrada = {0}) (salida = {1})" }, { "out.stored", "(almacenado 0%)" }, 
        { "out.update.manifest", "manifiesto actualizado" }, { "usage", "Sintaxis: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files ...\nOpciones:\n    -c  crear nuevo archivo\n    -t  crear la tabla de contenido del archivo\n    -x   extraer el archivo mencionado (o todos) del archivo\n    -u  actualizar archivo existente\n    -v  generar salida detallada de los datos de salida estándar\n    -f  especificar nombre de archivo de almacenamiento\n    -m  incluir información de manifiesto del archivo de manifiesto especificado\n    -e  especificar punto de entrada de la aplicación para la aplicación autónoma \n        que se incluye dentro de un archivo jar ejecutable\n    -0  sólo almacenar; no utilizar compresión ZIP\n    -P  conservar componentes iniciales '/' (ruta absoluta) y \"..\" (directorio principal) en los nombres de archivo\n    -M  no crear un archivo de manifiesto para las entradas\n    -i  generar información de índice para los archivos jar especificados\n    -C  cambiar al directorio especificado e incluir el archivo siguiente\nSi algún archivo es un directorio, se procesará de forma recurrente.\nEl nombre del archivo de manifiesto, el nombre del archivo de almacenamiento y el nombre del punto de entrada se\nespecifican en el mismo orden que los indicadores 'm', 'f' y 'e'.\n\nEjemplo 1: para archivar archivos de dos clases en un archivo llamado classes.jar: \n       jar cvf classes.jar Foo.class Bar.class \nEjemplo 2: utilice un archivo de manifiesto existente 'mymanifest' y archive todos los\n           archivos del directorio foo/ en 'classes.jar': \n       jar cvfm classes.jar mymanifest -C foo/ .\n" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\tools\jar\resources\jar_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */