package sun.security.util;

import java.util.ListResourceBundle;

public class AuthResources_de extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "invalid.null.input.value", "Ungültige Nulleingabe: {0}" }, { "NTDomainPrincipal.name", "NTDomainPrincipal: {0}" }, { "NTNumericCredential.name", "NTNumericCredential: {0}" }, { "Invalid.NTSid.value", "Ungültiger NTSid-Wert" }, { "NTSid.name", "NTSid: {0}" }, { "NTSidDomainPrincipal.name", "NTSidDomainPrincipal: {0}" }, { "NTSidGroupPrincipal.name", "NTSidGroupPrincipal: {0}" }, { "NTSidPrimaryGroupPrincipal.name", "NTSidPrimaryGroupPrincipal: {0}" }, { "NTSidUserPrincipal.name", "NTSidUserPrincipal: {0}" }, { "NTUserPrincipal.name", "NTUserPrincipal: {0}" }, 
      { "UnixNumericGroupPrincipal.Primary.Group.name", "UnixNumericGroupPrincipal [Primärgruppe]: {0}" }, { "UnixNumericGroupPrincipal.Supplementary.Group.name", "UnixNumericGroupPrincipal [Zusatzgruppe]: {0}" }, { "UnixNumericUserPrincipal.name", "UnixNumericUserPrincipal: {0}" }, { "UnixPrincipal.name", "UnixPrincipal: {0}" }, { "Unable.to.properly.expand.config", "{0} kann nicht ordnungsgemäß erweitert werden" }, { "extra.config.No.such.file.or.directory.", "{0} (Datei oder Verzeichnis nicht vorhanden)" }, { "Configuration.Error.No.such.file.or.directory", "Konfigurationsfehler:\n\tDatei oder Verzeichnis nicht vorhanden" }, { "Configuration.Error.Invalid.control.flag.flag", "Konfigurationsfehler:\n\tUngültiges Steuerkennzeichen {0}" }, { "Configuration.Error.Can.not.specify.multiple.entries.for.appName", "Konfigurationsfehler:\n\tEs können nicht mehrere Angaben für {0} gemacht werden." }, { "Configuration.Error.expected.expect.read.end.of.file.", "Konfigurationsfehler:\n\t[{0}] erwartet, [Dateiende] gelesen" }, 
      { "Configuration.Error.Line.line.expected.expect.found.value.", "Konfigurationsfehler:\n\tZeile {0}: [{1}] erwartet, [{2}] gefunden" }, { "Configuration.Error.Line.line.expected.expect.", "Konfigurationsfehler:\n\tZeile {0}: [{1}] erwartet" }, { "Configuration.Error.Line.line.system.property.value.expanded.to.empty.value", "Konfigurationsfehler:\n\tZeile {0}: Systemeigenschaft [{1}] auf leeren Wert erweitert" }, { "username.", "Benutzername: " }, { "password.", "Kennwort: " }, { "Please.enter.keystore.information", "Geben Sie die Keystore-Informationen ein" }, { "Keystore.alias.", "Keystore-Alias: " }, { "Keystore.password.", "Keystore-Kennwort: " }, { "Private.key.password.optional.", "Private Key-Kennwort (optional): " }, { "Kerberos.username.defUsername.", "Kerberos-Benutzername [{0}]: " }, 
      { "Kerberos.password.for.username.", "Kerberos-Kennwort für {0}: " }, { ".error.parsing.", ": Parsefehler " }, { "COLON", ": " }, { ".error.adding.Permission.", ": Fehler beim Hinzufügen der Berechtigung " }, { "SPACE", " " }, { ".error.adding.Entry.", ": Fehler beim Hinzufügen des Eintrags " }, { "LPARAM", "(" }, { "RPARAM", ")" }, { "attempt.to.add.a.Permission.to.a.readonly.PermissionCollection", "Es wurde versucht, eine Berechtigung zu einer schreibgeschützten PermissionCollection hinzuzufügen" }, { "expected.keystore.type", "Keystore-Typ erwartet" }, 
      { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "Principal kann nicht mit einer Platzhalterklasse ohne Platzhalternamen angegeben werden" }, { "expected.codeBase.or.SignedBy", "codeBase oder SignedBy erwartet" }, { "only.Principal.based.grant.entries.permitted", "Nur Principal-basierte Berechtigungseinträge zulässig" }, { "expected.permission.entry", "Berechtigungseintrag erwartet" }, { "number.", "Nummer " }, { "expected.expect.read.end.of.file.", "{0} erwartet, Dateiende gelesen" }, { "expected.read.end.of.file", "\";\" erwartet, Dateiende gelesen" }, { "line.", "Zeile " }, { ".expected.", ": erwartet: \"" }, { ".found.", "\", gefunden: \"" }, 
      { "QUOTE", "'" }, { "SolarisNumericGroupPrincipal.Primary.Group.", "SolarisNumericGroupPrincipal [Primärgruppe]: " }, { "SolarisNumericGroupPrincipal.Supplementary.Group.", "SolarisNumericGroupPrincipal [Zusatzgruppe]: " }, { "SolarisNumericUserPrincipal.", "SolarisNumericUserPrincipal: " }, { "SolarisPrincipal.", "SolarisPrincipal: " }, { "provided.null.name", "Nullname angegeben" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\securit\\util\AuthResources_de.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */