package sun.security.util;

import java.util.ListResourceBundle;

public class AuthResources_pt_BR extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "invalid.null.input.value", "entrada nula inválida: {0}" }, { "NTDomainPrincipal.name", "NTDomainPrincipal: {0}" }, { "NTNumericCredential.name", "NTNumericCredential: {0}" }, { "Invalid.NTSid.value", "Valor de NTSid inválido" }, { "NTSid.name", "NTSid: {0}" }, { "NTSidDomainPrincipal.name", "NTSidDomainPrincipal: {0}" }, { "NTSidGroupPrincipal.name", "NTSidGroupPrincipal: {0}" }, { "NTSidPrimaryGroupPrincipal.name", "NTSidPrimaryGroupPrincipal: {0}" }, { "NTSidUserPrincipal.name", "NTSidUserPrincipal: {0}" }, { "NTUserPrincipal.name", "NTUserPrincipal: {0}" }, 
      { "UnixNumericGroupPrincipal.Primary.Group.name", "UnixNumericGroupPrincipal [Grupo Principal]: {0}" }, { "UnixNumericGroupPrincipal.Supplementary.Group.name", "UnixNumericGroupPrincipal [Grupo Complementar]: {0}" }, { "UnixNumericUserPrincipal.name", "UnixNumericUserPrincipal: {0}" }, { "UnixPrincipal.name", "UnixPrincipal: {0}" }, { "Unable.to.properly.expand.config", "Não é possível expandir corretamente {0}" }, { "extra.config.No.such.file.or.directory.", "{0} (tal arquivo ou diretório não existe)" }, { "Configuration.Error.No.such.file.or.directory", "Erro de Configuração:\n\tNão há tal arquivo ou diretório" }, { "Configuration.Error.Invalid.control.flag.flag", "Erro de Configuração:\n\tFlag de controle inválido, {0}" }, { "Configuration.Error.Can.not.specify.multiple.entries.for.appName", "Erro de Configuração:\n\tNão é possível especificar várias entradas para {0}" }, { "Configuration.Error.expected.expect.read.end.of.file.", "Erro de Configuração:\n\tesperado [{0}], lido [fim do arquivo]" }, 
      { "Configuration.Error.Line.line.expected.expect.found.value.", "Erro de Configuração:\n\tLinha {0}: esperada [{1}], encontrada [{2}]" }, { "Configuration.Error.Line.line.expected.expect.", "Erro de Configuração:\n\tLinha {0}: esperada [{1}]" }, { "Configuration.Error.Line.line.system.property.value.expanded.to.empty.value", "Erro de Configuração:\n\tLinha {0}: propriedade do sistema [{1}] expandida para valor vazio" }, { "username.", "nome do usuário: " }, { "password.", "senha: " }, { "Please.enter.keystore.information", "Especifique as informações do armazenamento de chaves" }, { "Keystore.alias.", "Alias do armazenamento de chaves: " }, { "Keystore.password.", "Senha do armazenamento de chaves: " }, { "Private.key.password.optional.", "Senha da chave privada (opcional): " }, { "Kerberos.username.defUsername.", "Nome do usuário de Kerberos [{0}]: " }, 
      { "Kerberos.password.for.username.", "Senha de Kerberos de {0}: " }, { ".error.parsing.", ": erro de parsing " }, { "COLON", ": " }, { ".error.adding.Permission.", ": erro ao adicionar a Permissão " }, { "SPACE", " " }, { ".error.adding.Entry.", ": erro ao adicionar a Entrada " }, { "LPARAM", "(" }, { "RPARAM", ")" }, { "attempt.to.add.a.Permission.to.a.readonly.PermissionCollection", "tentativa de adicionar uma Permissão a um PermissionCollection somente para leitura" }, { "expected.keystore.type", "tipo de armazenamento de chaves esperado" }, 
      { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "não é possível especificar um principal com uma classe curinga sem um nome curinga" }, { "expected.codeBase.or.SignedBy", "CodeBase ou SignedBy esperado" }, { "only.Principal.based.grant.entries.permitted", "somente é permitido conceder entradas com base no Principal" }, { "expected.permission.entry", "entrada de permissão esperada" }, { "number.", "número " }, { "expected.expect.read.end.of.file.", "esperado {0}, ler fim do arquivo" }, { "expected.read.end.of.file", "esperado ';', fim de arquivo lido" }, { "line.", "linha " }, { ".expected.", ": esperado '" }, { ".found.", "', encontrado '" }, 
      { "QUOTE", "'" }, { "SolarisNumericGroupPrincipal.Primary.Group.", "SolarisNumericGroupPrincipal [Grupo Principal]: " }, { "SolarisNumericGroupPrincipal.Supplementary.Group.", "SolarisNumericGroupPrincipal [Grupo Complementar]: " }, { "SolarisNumericUserPrincipal.", "SolarisNumericUserPrincipal: " }, { "SolarisPrincipal.", "SolarisPrincipal: " }, { "provided.null.name", "nome nulo fornecido" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\securit\\util\AuthResources_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */