package sun.security.util;

import java.util.ListResourceBundle;

public class AuthResources_es extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "invalid.null.input.value", "entrada nula no válida: {0}" }, { "NTDomainPrincipal.name", "NTDomainPrincipal: {0}" }, { "NTNumericCredential.name", "NTNumericCredential: {0}" }, { "Invalid.NTSid.value", "Valor de NTSid no válido" }, { "NTSid.name", "NTSid: {0}" }, { "NTSidDomainPrincipal.name", "NTSidDomainPrincipal: {0}" }, { "NTSidGroupPrincipal.name", "NTSidGroupPrincipal: {0}" }, { "NTSidPrimaryGroupPrincipal.name", "NTSidPrimaryGroupPrincipal: {0}" }, { "NTSidUserPrincipal.name", "NTSidUserPrincipal: {0}" }, { "NTUserPrincipal.name", "NTUserPrincipal: {0}" }, 
      { "UnixNumericGroupPrincipal.Primary.Group.name", "UnixNumericGroupPrincipal [Grupo Principal] {0}" }, { "UnixNumericGroupPrincipal.Supplementary.Group.name", "UnixNumericGroupPrincipal [Grupo Adicional] {0}" }, { "UnixNumericUserPrincipal.name", "UnixNumericUserPrincipal: {0}" }, { "UnixPrincipal.name", "UnixPrincipal: {0}" }, { "Unable.to.properly.expand.config", "No se ha podido ampliar correctamente {0}" }, { "extra.config.No.such.file.or.directory.", "{0} (No existe tal archivo o directorio)" }, { "Configuration.Error.No.such.file.or.directory", "Error de Configuración:\n\tNo existe tal archivo o directorio" }, { "Configuration.Error.Invalid.control.flag.flag", "Error de Configuración:\n\tIndicador de control no válido, {0}" }, { "Configuration.Error.Can.not.specify.multiple.entries.for.appName", "Error de Configuración:\n\tNo se pueden especificar varias entradas para {0}" }, { "Configuration.Error.expected.expect.read.end.of.file.", "Error de configuración:\n\tse esperaba [{0}], se ha leído [final de archivo]" }, 
      { "Configuration.Error.Line.line.expected.expect.found.value.", "Error de configuración:\n\tLínea {0}: se esperaba [{1}], se ha encontrado [{2}]" }, { "Configuration.Error.Line.line.expected.expect.", "Error de configuración:\n\tLínea {0}: se esperaba [{1}]" }, { "Configuration.Error.Line.line.system.property.value.expanded.to.empty.value", "Error de configuración:\n\tLínea {0}: propiedad de sistema [{1}] ampliada a valor vacío" }, { "username.", "nombre de usuario: " }, { "password.", "contraseña: " }, { "Please.enter.keystore.information", "Introduzca la información del almacén de claves" }, { "Keystore.alias.", "Alias de Almacén de Claves: " }, { "Keystore.password.", "Contraseña de Almacén de Claves: " }, { "Private.key.password.optional.", "Contraseña de Clave Privada (opcional): " }, { "Kerberos.username.defUsername.", "Nombre de usuario de Kerberos [{0}]: " }, 
      { "Kerberos.password.for.username.", "Contraseña de Kerberos de {0}: " }, { ".error.parsing.", ": error de análisis " }, { "COLON", ": " }, { ".error.adding.Permission.", ": error al agregar el permiso " }, { "SPACE", " " }, { ".error.adding.Entry.", ": error al agregar la entrada " }, { "LPARAM", "(" }, { "RPARAM", ")" }, { "attempt.to.add.a.Permission.to.a.readonly.PermissionCollection", "se ha intentado agregar un permiso a una recopilación de permisos de sólo lectura" }, { "expected.keystore.type", "se esperaba un tipo de almacén de claves" }, 
      { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "no se puede especificar Principal con una clase de comodín sin un nombre de comodín" }, { "expected.codeBase.or.SignedBy", "se esperaba codeBase o SignedBy" }, { "only.Principal.based.grant.entries.permitted", "sólo se permite otorgar entradas basadas en Principal" }, { "expected.permission.entry", "se esperaba un permiso de entrada" }, { "number.", "número " }, { "expected.expect.read.end.of.file.", "se esperaba [{0}], se ha leído final de archivo" }, { "expected.read.end.of.file", "se esperaba ';', se ha leído el final de archivo" }, { "line.", "línea " }, { ".expected.", ": se esperaba '" }, { ".found.", "', se ha encontrado '" }, 
      { "QUOTE", "'" }, { "SolarisNumericGroupPrincipal.Primary.Group.", "SolarisNumericGroupPrincipal [Grupo Principal]: " }, { "SolarisNumericGroupPrincipal.Supplementary.Group.", "SolarisNumericGroupPrincipal [Grupo Adicional]: " }, { "SolarisNumericUserPrincipal.", "SolarisNumericUserPrincipal: " }, { "SolarisPrincipal.", "SolarisPrincipal: " }, { "provided.null.name", "se ha proporcionado un nombre nulo" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\securit\\util\AuthResources_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */