package sun.security.util;

import java.util.ListResourceBundle;

public class AuthResources_it extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "invalid.null.input.value", "input nullo non valido: {0}" }, { "NTDomainPrincipal.name", "NTDomainPrincipal: {0}" }, { "NTNumericCredential.name", "NTNumericCredential: {0}" }, { "Invalid.NTSid.value", "Valore NTSid non valido" }, { "NTSid.name", "NTSid: {0}" }, { "NTSidDomainPrincipal.name", "NTSidDomainPrincipal: {0}" }, { "NTSidGroupPrincipal.name", "NTSidGroupPrincipal: {0}" }, { "NTSidPrimaryGroupPrincipal.name", "NTSidPrimaryGroupPrincipal: {0}" }, { "NTSidUserPrincipal.name", "NTSidUserPrincipal: {0}" }, { "NTUserPrincipal.name", "NTUserPrincipal: {0}" }, 
      { "UnixNumericGroupPrincipal.Primary.Group.name", "UnixNumericGroupPrincipal [gruppo primario]: {0}" }, { "UnixNumericGroupPrincipal.Supplementary.Group.name", "UnixNumericGroupPrincipal [gruppo supplementare]: {0}" }, { "UnixNumericUserPrincipal.name", "UnixNumericUserPrincipal: {0}" }, { "UnixPrincipal.name", "UnixPrincipal: {0}" }, { "Unable.to.properly.expand.config", "Impossibile espandere correttamente {0}" }, { "extra.config.No.such.file.or.directory.", "{0} (file o directory inesistente)" }, { "Configuration.Error.No.such.file.or.directory", "Errore di configurazione:\n\tFile o directory inesistente" }, { "Configuration.Error.Invalid.control.flag.flag", "Errore di configurazione:\n\tflag di controllo non valido, {0}" }, { "Configuration.Error.Can.not.specify.multiple.entries.for.appName", "Errore di configurazione:\n\timpossibile specificare più valori per {0}" }, { "Configuration.Error.expected.expect.read.end.of.file.", "Errore di configurazione:\n\tprevisto [{0}], letto [end of file]" }, 
      { "Configuration.Error.Line.line.expected.expect.found.value.", "Errore di configurazione:\n\triga {0}: previsto [{1}], trovato [{2}]" }, { "Configuration.Error.Line.line.expected.expect.", "Errore di configurazione:\n\triga {0}: previsto [{1}]" }, { "Configuration.Error.Line.line.system.property.value.expanded.to.empty.value", "Errore di configurazione:\n\triga {0}: proprietà di sistema [{1}] espansa a valore vuoto" }, { "username.", "Nome utente: " }, { "password.", "Password: " }, { "Please.enter.keystore.information", "Immettere le informazioni per il keystore" }, { "Keystore.alias.", "Alias keystore: " }, { "Keystore.password.", "Password keystore: " }, { "Private.key.password.optional.", "Password chiave privata (opzionale): " }, { "Kerberos.username.defUsername.", "Nome utente Kerberos [{0}]: " }, 
      { "Kerberos.password.for.username.", "Password Kerberos per {0}: " }, { ".error.parsing.", ": errore durante l'analisi " }, { "COLON", ": " }, { ".error.adding.Permission.", ": errore durante l'aggiunta dell'autorizzazione " }, { "SPACE", " " }, { ".error.adding.Entry.", ": errore durante l'aggiunta della voce " }, { "LPARAM", "(" }, { "RPARAM", ")" }, { "attempt.to.add.a.Permission.to.a.readonly.PermissionCollection", "tentativo di aggiungere un'autorizzazione a una PermissionCollection di sola lettura" }, { "expected.keystore.type", "tipo keystore previsto" }, 
      { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "impossibile specificare un principal con una classe carattere jolly senza un nome carattere jolly" }, { "expected.codeBase.or.SignedBy", "previsto codeBase o SignedBy" }, { "only.Principal.based.grant.entries.permitted", "sono consentiti solo valori garantiti basati sul principal" }, { "expected.permission.entry", "prevista voce di autorizzazione" }, { "number.", "numero " }, { "expected.expect.read.end.of.file.", "previsto {0}, letto end of file" }, { "expected.read.end.of.file", "previsto ';', letto end of file" }, { "line.", "riga " }, { ".expected.", ": previsto '" }, { ".found.", "', trovato '" }, 
      { "QUOTE", "'" }, { "SolarisNumericGroupPrincipal.Primary.Group.", "SolarisNumericGroupPrincipal [gruppo primario]: " }, { "SolarisNumericGroupPrincipal.Supplementary.Group.", "SolarisNumericGroupPrincipal [gruppo supplementare]: " }, { "SolarisNumericUserPrincipal.", "SolarisNumericUserPrincipal: " }, { "SolarisPrincipal.", "SolarisPrincipal: " }, { "provided.null.name", "il nome fornito è nullo" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\securit\\util\AuthResources_it.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */