package sun.security.util;

import java.util.ListResourceBundle;

public class AuthResources_fr extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "invalid.null.input.value", "entrée NULL non valide : {0}" }, { "NTDomainPrincipal.name", "NTDomainPrincipal : {0}" }, { "NTNumericCredential.name", "NTNumericCredential : {0}" }, { "Invalid.NTSid.value", "Valeur de NTSid non valide" }, { "NTSid.name", "NTSid : {0}" }, { "NTSidDomainPrincipal.name", "NTSidDomainPrincipal : {0}" }, { "NTSidGroupPrincipal.name", "NTSidGroupPrincipal : {0}" }, { "NTSidPrimaryGroupPrincipal.name", "NTSidPrimaryGroupPrincipal : {0}" }, { "NTSidUserPrincipal.name", "NTSidUserPrincipal : {0}" }, { "NTUserPrincipal.name", "NTUserPrincipal : {0}" }, 
      { "UnixNumericGroupPrincipal.Primary.Group.name", "UnixNumericGroupPrincipal [groupe principal] : {0}" }, { "UnixNumericGroupPrincipal.Supplementary.Group.name", "UnixNumericGroupPrincipal [groupe supplémentaire] : {0}" }, { "UnixNumericUserPrincipal.name", "UnixNumericUserPrincipal : {0}" }, { "UnixPrincipal.name", "UnixPrincipal : {0}" }, { "Unable.to.properly.expand.config", "Impossible de développer {0} correctement" }, { "extra.config.No.such.file.or.directory.", "{0} (fichier ou répertoire inexistant)" }, { "Configuration.Error.No.such.file.or.directory", "Erreur de configuration :\n\tCe fichier ou répertoire n'existe pas" }, { "Configuration.Error.Invalid.control.flag.flag", "Erreur de configuration :\n\tIndicateur de contrôle non valide, {0}" }, { "Configuration.Error.Can.not.specify.multiple.entries.for.appName", "Erreur de configuration :\n\tImpossible de spécifier des entrées multiples pour {0}" }, { "Configuration.Error.expected.expect.read.end.of.file.", "Erreur de configuration :\n\tAttendu : [{0}], lu : [fin de fichier]" }, 
      { "Configuration.Error.Line.line.expected.expect.found.value.", "Erreur de configuration :\n\tLigne {0} : attendu [{1}], trouvé [{2}]" }, { "Configuration.Error.Line.line.expected.expect.", "Erreur de configuration :\n\tLigne {0} : attendu [{1}]" }, { "Configuration.Error.Line.line.system.property.value.expanded.to.empty.value", "Erreur de configuration :\n\tLigne {0} : propriété système [{1}] développée en valeur vide" }, { "username.", "nom utilisateur : " }, { "password.", "mot de passe : " }, { "Please.enter.keystore.information", "Entrez les informations du fichier de clés" }, { "Keystore.alias.", "Alias du fichier de clés : " }, { "Keystore.password.", "Mot de passe pour fichier de clés : " }, { "Private.key.password.optional.", "Mot de passe de la clé privée (facultatif) : " }, { "Kerberos.username.defUsername.", "Nom utilisateur Kerberos [{0}] : " }, 
      { "Kerberos.password.for.username.", "Mot de passe Kerberos pour {0} : " }, { ".error.parsing.", ": erreur d'analyse " }, { "COLON", ": " }, { ".error.adding.Permission.", ": erreur d'ajout de droit " }, { "SPACE", " " }, { ".error.adding.Entry.", ": erreur d'ajout d'entrée " }, { "LPARAM", "(" }, { "RPARAM", ")" }, { "attempt.to.add.a.Permission.to.a.readonly.PermissionCollection", "tentative d'ajout de droit à un ensemble de droits en lecture seule" }, { "expected.keystore.type", "type de fichier de clés attendu" }, 
      { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "impossible de spécifier le principal avec une classe générique sans nom générique" }, { "expected.codeBase.or.SignedBy", "codeBase ou SignedBy attendu" }, { "only.Principal.based.grant.entries.permitted", "seules les entrées basées sur Principal sont autorisées" }, { "expected.permission.entry", "entrée de droit attendue" }, { "number.", "nombre " }, { "expected.expect.read.end.of.file.", "attendu {0}, lecture de fin de fichier" }, { "expected.read.end.of.file", "attendu ';', lecture de fin de fichier" }, { "line.", "ligne " }, { ".expected.", ": attendu '" }, { ".found.", "', trouvé '" }, 
      { "QUOTE", "'" }, { "SolarisNumericGroupPrincipal.Primary.Group.", "SolarisNumericGroupPrincipal [groupe principal] : " }, { "SolarisNumericGroupPrincipal.Supplementary.Group.", "SolarisNumericGroupPrincipal [groupe supplémentaire] : " }, { "SolarisNumericUserPrincipal.", "SolarisNumericUserPrincipal : " }, { "SolarisPrincipal.", "SolarisPrincipal : " }, { "provided.null.name", "nom NULL fourni" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\securit\\util\AuthResources_fr.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */