package sun.security.util;

import java.util.ListResourceBundle;

public class AuthResources_sv extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "invalid.null.input.value", "ogiltiga null-indata: {0}" }, { "NTDomainPrincipal.name", "NTDomainPrincipal: {0}" }, { "NTNumericCredential.name", "NTNumericCredential: {0}" }, { "Invalid.NTSid.value", "Ogiltigt NTSid-värde" }, { "NTSid.name", "NTSid: {0}" }, { "NTSidDomainPrincipal.name", "NTSidDomainPrincipal: {0}" }, { "NTSidGroupPrincipal.name", "NTSidGroupPrincipal: {0}" }, { "NTSidPrimaryGroupPrincipal.name", "NTSidPrimaryGroupPrincipal: {0}" }, { "NTSidUserPrincipal.name", "NTSidUserPrincipal: {0}" }, { "NTUserPrincipal.name", "NTUserPrincipal: {0}" }, 
      { "UnixNumericGroupPrincipal.Primary.Group.name", "UnixNumericGroupPrincipal [primär grupp]: {0}" }, { "UnixNumericGroupPrincipal.Supplementary.Group.name", "UnixNumericGroupPrincipal [tilläggsgrupp]: {0}" }, { "UnixNumericUserPrincipal.name", "UnixNumericUserPrincipal: {0}" }, { "UnixPrincipal.name", "UnixPrincipal: {0}" }, { "Unable.to.properly.expand.config", "Kan inte utöka korrekt {0}" }, { "extra.config.No.such.file.or.directory.", "{0} (det finns ingen sådan fil eller katalog)" }, { "Configuration.Error.No.such.file.or.directory", "Konfigurationsfel:\n\tFilen eller katalogen finns inte" }, { "Configuration.Error.Invalid.control.flag.flag", "Konfigurationsfel:\n\tOgiltig kontrollflagga, {0}" }, { "Configuration.Error.Can.not.specify.multiple.entries.for.appName", "Konfigurationsfel:\n\tKan inte ange flera poster för {0}" }, { "Configuration.Error.expected.expect.read.end.of.file.", "Konfigurationsfel:\n\tförväntade [{0}], läste [filslut]" }, 
      { "Configuration.Error.Line.line.expected.expect.found.value.", "Konfigurationsfel:\n\tRad {0}: förväntade [{1}], hittade [{2}]" }, { "Configuration.Error.Line.line.expected.expect.", "Konfigurationsfel:\n\tRad {0}: förväntade [{1}]" }, { "Configuration.Error.Line.line.system.property.value.expanded.to.empty.value", "Konfigurationsfel:\n\tRad {0}: systemegenskapen [{1}] utökad till tomt värde" }, { "username.", "användarnamn: " }, { "password.", "lösenord: " }, { "Please.enter.keystore.information", "Ange nyckellagerinformation" }, { "Keystore.alias.", "Nyckellageralias: " }, { "Keystore.password.", "Nyckellagerlösenord: " }, { "Private.key.password.optional.", "Lösenord för privat nyckel (valfritt): " }, { "Kerberos.username.defUsername.", "Kerberos-användarnamn [{0}]: " }, 
      { "Kerberos.password.for.username.", "Kerberos-lösenord för {0}: " }, { ".error.parsing.", ": tolkningsfel " }, { "COLON", ": " }, { ".error.adding.Permission.", ": fel vid tillägg av behörighet " }, { "SPACE", " " }, { ".error.adding.Entry.", ": fel vid tillägg av post " }, { "LPARAM", "(" }, { "RPARAM", ")" }, { "attempt.to.add.a.Permission.to.a.readonly.PermissionCollection", "försök att lägga till behörighet till skrivskyddad PermissionCollection" }, { "expected.keystore.type", "förväntad nyckellagertyp" }, 
      { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "kan inte ange identitetshavare med en jokerteckenklass utan ett jokerteckennamn" }, { "expected.codeBase.or.SignedBy", "förväntade codeBase eller SignedBy" }, { "only.Principal.based.grant.entries.permitted", "endast identitetshavarbaserade poster tillåts" }, { "expected.permission.entry", "förväntade behörighetspost" }, { "number.", "nummer" }, { "expected.expect.read.end.of.file.", "förväntade {0}, läste filslut" }, { "expected.read.end.of.file", "förväntade ';', läste filslut" }, { "line.", "rad " }, { ".expected.", ": förväntade '" }, { ".found.", "', hittade '" }, 
      { "QUOTE", "'" }, { "SolarisNumericGroupPrincipal.Primary.Group.", "SolarisNumericGroupPrincipal [primär grupp]: " }, { "SolarisNumericGroupPrincipal.Supplementary.Group.", "SolarisNumericGroupPrincipal [tilläggsgrupp]: " }, { "SolarisNumericUserPrincipal.", "SolarisNumericUserPrincipal: " }, { "SolarisPrincipal.", "SolarisPrincipal: " }, { "provided.null.name", "null-namn angavs" } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\securit\\util\AuthResources_sv.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */