package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_es extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AWT.CompositionWindowTitle", "Ventana de Entrada" }, { "AWT.CrosshairCursor", "Cursor de Punto de Mira" }, { "AWT.DefaultCursor", "Cursor Por defecto" }, { "AWT.DefaultDragCursor", "Cursor de Arrastrar Por defecto" }, { "AWT.DefaultDropCursor", "Cursor de Soltar Por Defecto" }, { "AWT.DefaultNoDropCursor", "Cursor de No Arrastrar Por Defecto" }, { "AWT.EResizeCursor", "Cursor de Cambio de Tamaño este" }, { "AWT.HandCursor", "Cursor de Mano" }, { "AWT.HostInputMethodDisplayName", "Métodos de Entrada del Sistema" }, { "AWT.InconsistentDLLsWarning", "Puede que las operaciones textuales no funcionen correctamente debido a un juego incoherente de bibliotecas de enlaces dinámicos (DLL) instaladas en su sistema. Para obtener más información acerca de este problema y de la solución alternativa sugerida, consulte Java(TM) 2 SDK, Standard Edition Release Notes en java.sun.com." }, 
        { "AWT.InputMethodCreationFailed", "No se ha podido crear {0}. Motivo: {1}" }, { "AWT.InputMethodLanguage.ja", "Japonés" }, { "AWT.InputMethodLanguage.ko", "Coreano" }, { "AWT.InputMethodLanguage.zh", "chino" }, { "AWT.InputMethodLanguage.zh_CN", "Chino Simplificado" }, { "AWT.InputMethodLanguage.zh_TW", "Chino Tradicional" }, { "AWT.InputMethodSelectionMenu", "Seleccionar Método de Entrada" }, { "AWT.Less", "Menor que" }, { "AWT.MoveCursor", "Cursor de Movimiento" }, { "AWT.NEResizeCursor", "Cursor de Cambio de Tamaño Nordeste" }, 
        { "AWT.NResizeCursor", "Cursor de Cambio de Tamaño Norte" }, { "AWT.NWResizeCursor", "Cursor de Cambio de Tamaño Noroeste" }, { "AWT.SEResizeCursor", "Cursor de Cambio de Tamaño Sudeste" }, { "AWT.SResizeCursor", "Cursor de Cambio de Tamaño Sur" }, { "AWT.SWResizeCursor", "Cursor de Cambio de Tamaño Suroeste" }, { "AWT.TextCursor", "Cursor de Texto" }, { "AWT.WResizeCursor", "Cursor de Cambio de Tamaño Oeste" }, { "AWT.WaitCursor", "Cursor de Espera" }, { "AWT.accept", "Aceptar" }, { "AWT.add", "+ de Teclado Numérico" }, 
        { "AWT.again", "Repetir" }, { "AWT.allCandidates", "Todos los Candidatos" }, { "AWT.alphanumeric", "Alfanumérico" }, { "AWT.alt", "Alt" }, { "AWT.altGraph", "Alt Gr" }, { "AWT.ampersand", "Ampersand" }, { "AWT.asterisk", "Asterisco" }, { "AWT.at", "Arroba" }, { "AWT.backQuote", "Comilla Invertida" }, { "AWT.backSlash", "Barra Invertida" }, 
        { "AWT.backSpace", "Retroceso" }, { "AWT.begin", "Inicio" }, { "AWT.braceLeft", "Llave de Apertura" }, { "AWT.braceRight", "Llave de Cierre" }, { "AWT.cancel", "Cancelar" }, { "AWT.capsLock", "Bloqueo de Mayúsculas" }, { "AWT.circumflex", "Circunflejo" }, { "AWT.clear", "Borrar" }, { "AWT.closeBracket", "Paréntesis de Cierre" }, { "AWT.codeInput", "Entrada de Código" }, 
        { "AWT.colon", "Dos puntos" }, { "AWT.comma", "Coma" }, { "AWT.compose", "Componer" }, { "AWT.context", "Menú Contextual" }, { "AWT.control", "Ctrl" }, { "AWT.convert", "Convertir" }, { "AWT.copy", "Copiar" }, { "AWT.cut", "Cortar" }, { "AWT.deadAboveDot", "Punto Superior (Tecla Muerta)" }, { "AWT.deadAboveRing", "Círculo Superior (Tecla Muerta)" }, 
        { "AWT.deadAcute", "Acento Agudo Muerto" }, { "AWT.deadBreve", "Acento Breve (Tecla Muerta)" }, { "AWT.deadCaron", "Acento Articircunflejo (Tecla Muerta)" }, { "AWT.deadCedilla", "Cedilla (Tecla Muerta)" }, { "AWT.deadCircumflex", "Circunflejo (Tecla Muerta)" }, { "AWT.deadDiaeresis", "Diéresis (Tecla Muerta)" }, { "AWT.deadDoubleAcute", "Acento Agudo Doble (Tecla Muerta)" }, { "AWT.deadGrave", "Acento Grave (Tecla Muerta)" }, { "AWT.deadIota", "Iota (Tecla Muerta)" }, { "AWT.deadMacron", "Macrón (Tecla Muerta)" }, 
        { "AWT.deadOgonek", "Espíritu Áspero (Tecla Muerta)" }, { "AWT.deadSemivoicedSound", "Sonido Semisonoro (Tecla Muerta)" }, { "AWT.deadTilde", "Tilde (Tecla Muerta)" }, { "AWT.deadVoicedSound", "Sonido Sonoro (Tecla Muerta)" }, { "AWT.decimal", ". de Teclado Numérico" }, { "AWT.delete", "Suprimir" }, { "AWT.divide", "/ de Teclado Numérico" }, { "AWT.dollar", "Dólar" }, { "AWT.down", "Abajo" }, { "AWT.end", "Fin" }, 
        { "AWT.enter", "Intro" }, { "AWT.equals", "Igual" }, { "AWT.escape", "Escape" }, { "AWT.euro", "Euro" }, { "AWT.exclamationMark", "Signo de Exclamación de Cierre" }, { "AWT.f1", "F1" }, { "AWT.f10", "F10" }, { "AWT.f11", "F11" }, { "AWT.f12", "F12" }, { "AWT.f13", "F13" }, 
        { "AWT.f14", "F14" }, { "AWT.f15", "F15" }, { "AWT.f16", "F16" }, { "AWT.f17", "F17" }, { "AWT.f18", "F18" }, { "AWT.f19", "F19" }, { "AWT.f2", "F2" }, { "AWT.f20", "F20" }, { "AWT.f21", "F21" }, { "AWT.f22", "F22" }, 
        { "AWT.f23", "F23" }, { "AWT.f24", "F24" }, { "AWT.f3", "F3" }, { "AWT.f4", "F4" }, { "AWT.f5", "F5" }, { "AWT.f6", "F6" }, { "AWT.f7", "F7" }, { "AWT.f8", "F8" }, { "AWT.f9", "F9" }, { "AWT.final", "Final" }, 
        { "AWT.find", "Buscar" }, { "AWT.fullWidth", "Anchura Completa" }, { "AWT.greater", "Mayor que" }, { "AWT.halfWidth", "Media Anchura" }, { "AWT.help", "Ayuda" }, { "AWT.hiragana", "Hiragana" }, { "AWT.home", "Inicio" }, { "AWT.inputMethodOnOff", "Activar/Desactivar Método de Entrada" }, { "AWT.insert", "Insertar" }, { "AWT.invertedExclamationMark", "Signo de Exclamación de Apertura" }, 
        { "AWT.japaneseHiragana", "Caracteres Hiragana Japoneses" }, { "AWT.japaneseKatakana", "Caracteres Katakana Japoneses" }, { "AWT.japaneseRoman", "Caracteres Romanos Japoneses" }, { "AWT.kana", "Kana" }, { "AWT.kanaLock", "Bloqueo Kana" }, { "AWT.kanji", "Kanji" }, { "AWT.katakana", "Katakana" }, { "AWT.left", "Izquierda" }, { "AWT.leftParenthesis", "Paréntesis Izquierdo" }, { "AWT.meta", "Meta" }, 
        { "AWT.minus", "Menos" }, { "AWT.modechange", "Cambio de Modo" }, { "AWT.multiply", "* de Teclado Numérico" }, { "AWT.noconvert", "No Convertir" }, { "AWT.numLock", "Bloqueo Numérico" }, { "AWT.numberSign", "Signo de Número" }, { "AWT.numpad", "Teclado Numérico" }, { "AWT.openBracket", "Paréntesis de Apertura" }, { "AWT.paste", "Pegar" }, { "AWT.pause", "Pausa" }, 
        { "AWT.period", "Punto" }, { "AWT.pgdn", "AvPág" }, { "AWT.pgup", "RePág" }, { "AWT.plus", "Más" }, { "AWT.previousCandidate", "Candidato Anterior" }, { "AWT.printScreen", "Imprimir Pantalla" }, { "AWT.props", "Propiedades" }, { "AWT.quote", "Comilla" }, { "AWT.quoteDbl", "Dobles Comillas" }, { "AWT.right", "Derecha" }, 
        { "AWT.rightParenthesis", "Paréntesis Derecho" }, { "AWT.romanCharacters", "Caracteres Romanos" }, { "AWT.scrollLock", "Bloqueo de Desplazamiento" }, { "AWT.semicolon", "Punto y coma" }, { "AWT.separater", ", de Teclado Numérico" }, { "AWT.separator", ", de Teclado Numérico" }, { "AWT.shift", "Mayús" }, { "AWT.slash", "Barra" }, { "AWT.space", "Espacio" }, { "AWT.stop", "Parar" }, 
        { "AWT.subtract", "- de Teclado Numérico" }, { "AWT.tab", "Tabulador" }, { "AWT.undefined", "No Definido" }, { "AWT.underscore", "Subrayado" }, { "AWT.undo", "Deshacer" }, { "AWT.unknown", "Desconocido" }, { "AWT.up", "Arriba" }, { "AWT.windows", "Windows" }, { "java.awt.def.delay", "30" }, { "java.awt.im.style", "en el lugar" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\awt\resources\awt_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */