package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_pt_BR extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AWT.CompositionWindowTitle", "Janela de Entrada" }, { "AWT.CrosshairCursor", "Cursor em Forma de Cruz" }, { "AWT.DefaultCursor", "Cursor Padrão" }, { "AWT.DefaultDragCursor", "Cursor Padrão de Arrastar" }, { "AWT.DefaultDropCursor", "Cursor Padrão de Soltar" }, { "AWT.DefaultNoDropCursor", "Cursor Padrão sem Arrastar" }, { "AWT.EResizeCursor", "Cursor de Seta Que Aponta à Direita" }, { "AWT.HandCursor", "Cursor em Forma de Mão" }, { "AWT.HostInputMethodDisplayName", "Métodos de Entrada do Sistema" }, { "AWT.InconsistentDLLsWarning", "Pode ser que as operações baseadas em texto não funcionem corretamente devido a um conjunto incoerente de bibliotecas de vinculação dinâmica (DLLs) instalado no seu sistema. Para obter mais informações sobre este problema e uma solução recomendada, consulte as Notas de Versão do Java(TM) 2 SDK, Standard Edition, em java.sun.com." }, 
        { "AWT.InputMethodCreationFailed", "Não foi possível criar {0}. Motivo: {1}" }, { "AWT.InputMethodLanguage.ja", "Japonês" }, { "AWT.InputMethodLanguage.ko", "Coreano" }, { "AWT.InputMethodLanguage.zh", "Chinês" }, { "AWT.InputMethodLanguage.zh_CN", "Chinês Simplificado" }, { "AWT.InputMethodLanguage.zh_TW", "Chinês Tradicional" }, { "AWT.InputMethodSelectionMenu", "Selecionar Método de Entrada" }, { "AWT.Less", "Menos" }, { "AWT.MoveCursor", "Cursor de Movimento" }, { "AWT.NEResizeCursor", "Cursor de Seta Que Aponta para Nordeste" }, 
        { "AWT.NResizeCursor", "Cursor de Seta Que Aponta para Cima" }, { "AWT.NWResizeCursor", "Cursor de Seta Que Aponta para Noroeste" }, { "AWT.SEResizeCursor", "Cursor de Seta Que Aponta para Sudeste" }, { "AWT.SResizeCursor", "Cursor de Seta Que Aponta para Baixo" }, { "AWT.SWResizeCursor", "Cursor de Seta Que Aponta para Sudoeste" }, { "AWT.TextCursor", "Cursor de Texto" }, { "AWT.WResizeCursor", "Cursor de Seta Que Aponta à Esquerda" }, { "AWT.WaitCursor", "Cursor em Forma de Ampulheta" }, { "AWT.accept", "Aceitar" }, { "AWT.add", "Teclado Numérico +" }, 
        { "AWT.again", "Novamente" }, { "AWT.allCandidates", "Todos os Candidatos" }, { "AWT.alphanumeric", "Alfanumérico" }, { "AWT.alt", "Alt" }, { "AWT.altGraph", "Alt Graph" }, { "AWT.ampersand", "E Comercial" }, { "AWT.asterisk", "Asterisco" }, { "AWT.at", "Arroba" }, { "AWT.backQuote", "Crase" }, { "AWT.backSlash", "Barra Invertida" }, 
        { "AWT.backSpace", "Backspace" }, { "AWT.begin", "Começar" }, { "AWT.braceLeft", "Chave Esquerda" }, { "AWT.braceRight", "Chave Direta" }, { "AWT.cancel", "Cancelar" }, { "AWT.capsLock", "Caps Lock" }, { "AWT.circumflex", "Circunflexo" }, { "AWT.clear", "Limpar" }, { "AWT.closeBracket", "Parêntese de Fechamento" }, { "AWT.codeInput", "Entrada de Código" }, 
        { "AWT.colon", "Vírgula" }, { "AWT.comma", "Vírgula" }, { "AWT.compose", "Compor" }, { "AWT.context", "Menu de Contexto" }, { "AWT.control", "Ctrl" }, { "AWT.convert", "Converter" }, { "AWT.copy", "Copiar" }, { "AWT.cut", "Recortar" }, { "AWT.deadAboveDot", "Ponto em Cima" }, { "AWT.deadAboveRing", "Símbolo de Grau" }, 
        { "AWT.deadAcute", "Acento Agudo" }, { "AWT.deadBreve", "Braquia" }, { "AWT.deadCaron", "Acento Circunflexo Invertido" }, { "AWT.deadCedilla", "Cedilha" }, { "AWT.deadCircumflex", "Acento Circunflexo" }, { "AWT.deadDiaeresis", "Trema" }, { "AWT.deadDoubleAcute", "Acento Agudo Duplo" }, { "AWT.deadGrave", "Acento Grave" }, { "AWT.deadIota", "Lota" }, { "AWT.deadMacron", "Mácron" }, 
        { "AWT.deadOgonek", "Gancho Polonês" }, { "AWT.deadSemivoicedSound", "Surdo (Som)" }, { "AWT.deadTilde", "Til" }, { "AWT.deadVoicedSound", "Sonoro (Som)" }, { "AWT.decimal", "Teclado Numérico ." }, { "AWT.delete", "Excluir" }, { "AWT.divide", "Teclado Numérico /" }, { "AWT.dollar", "Dólar" }, { "AWT.down", "Abaixo" }, { "AWT.end", "Fim" }, 
        { "AWT.enter", "Enter" }, { "AWT.equals", "Igual" }, { "AWT.escape", "Escape" }, { "AWT.euro", "Euro" }, { "AWT.exclamationMark", "Ponto de Exclamação" }, { "AWT.f1", "F1" }, { "AWT.f10", "F10" }, { "AWT.f11", "F11" }, { "AWT.f12", "F12" }, { "AWT.f13", "F13" }, 
        { "AWT.f14", "F14" }, { "AWT.f15", "F15" }, { "AWT.f16", "F16" }, { "AWT.f17", "F17" }, { "AWT.f18", "F18" }, { "AWT.f19", "F19" }, { "AWT.f2", "F2" }, { "AWT.f20", "F20" }, { "AWT.f21", "F21" }, { "AWT.f22", "F22" }, 
        { "AWT.f23", "F23" }, { "AWT.f24", "F24" }, { "AWT.f3", "F3" }, { "AWT.f4", "F4" }, { "AWT.f5", "F5" }, { "AWT.f6", "F6" }, { "AWT.f7", "F7" }, { "AWT.f8", "F8" }, { "AWT.f9", "F9" }, { "AWT.final", "Final" }, 
        { "AWT.find", "Localizar" }, { "AWT.fullWidth", "Largura Total" }, { "AWT.greater", "Maior" }, { "AWT.halfWidth", "Meia Largura" }, { "AWT.help", "Ajuda" }, { "AWT.hiragana", "Hiragana" }, { "AWT.home", "Início" }, { "AWT.inputMethodOnOff", "Método de Entrada Ativado/Desativado" }, { "AWT.insert", "Insert" }, { "AWT.invertedExclamationMark", "Ponto de Exclamação Invertido" }, 
        { "AWT.japaneseHiragana", "Hiragana Japonês" }, { "AWT.japaneseKatakana", "Katakana Japonês" }, { "AWT.japaneseRoman", "Romano Japonês" }, { "AWT.kana", "Kana" }, { "AWT.kanaLock", "Kana Lock" }, { "AWT.kanji", "Kanji" }, { "AWT.katakana", "Katakana" }, { "AWT.left", "Esquerda" }, { "AWT.leftParenthesis", "Parêntese Esquerdo" }, { "AWT.meta", "Meta" }, 
        { "AWT.minus", "Menos" }, { "AWT.modechange", "Alteração de Modo" }, { "AWT.multiply", "Teclado Numérico *" }, { "AWT.noconvert", "Não Converter" }, { "AWT.numLock", "Num Lock" }, { "AWT.numberSign", "Sinal Numérico" }, { "AWT.numpad", "Teclado Numérico" }, { "AWT.openBracket", "Parêntese de Abertura" }, { "AWT.paste", "Colar" }, { "AWT.pause", "Pausar" }, 
        { "AWT.period", "Ponto Final" }, { "AWT.pgdn", "Página Abaixo" }, { "AWT.pgup", "Página Acima" }, { "AWT.plus", "Mais" }, { "AWT.previousCandidate", "Candidato Anterior" }, { "AWT.printScreen", "Print Screen" }, { "AWT.props", "Sustentar" }, { "AWT.quote", "Aspas" }, { "AWT.quoteDbl", "Aspas Duplas" }, { "AWT.right", "Direita" }, 
        { "AWT.rightParenthesis", "Parêntese Direito" }, { "AWT.romanCharacters", "Caracteres Romanos" }, { "AWT.scrollLock", "Scroll Lock" }, { "AWT.semicolon", "Ponto-e-Vírgula" }, { "AWT.separater", "Teclado Numérico ," }, { "AWT.separator", "Teclado Numérico ," }, { "AWT.shift", "Shift" }, { "AWT.slash", "Barra" }, { "AWT.space", "Espaço" }, { "AWT.stop", "Interromper" }, 
        { "AWT.subtract", "Teclado Numérico -" }, { "AWT.tab", "Guia" }, { "AWT.undefined", "Indefinido" }, { "AWT.underscore", "Sublinhado" }, { "AWT.undo", "Desfazer" }, { "AWT.unknown", "Desconhecido" }, { "AWT.up", "Acima" }, { "AWT.windows", "Janelas" }, { "java.awt.def.delay", "30" }, { "java.awt.im.style", "no momento" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\awt\resources\awt_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */