package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_fr extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AWT.CompositionWindowTitle", "Fenêtre d'entrée" }, { "AWT.CrosshairCursor", "Curseur réticulaire" }, { "AWT.DefaultCursor", "Curseur par défaut" }, { "AWT.DefaultDragCursor", "Curseur de déplacement par défaut" }, { "AWT.DefaultDropCursor", "Curseur de pose par défaut" }, { "AWT.DefaultNoDropCursor", "Curseur non déplaçant par défaut" }, { "AWT.EResizeCursor", "Curseur de redimensionnement est" }, { "AWT.HandCursor", "Curseur en forme de main" }, { "AWT.HostInputMethodDisplayName", "Méthodes d'entrée système" }, { "AWT.InconsistentDLLsWarning", "Il se peut que les opérations liées au texte ne fonctionnent pas correctement lorsqu'un ensemble incohérent de DLL est installé sur le système. Vous trouverez plus de détails sur ce problème et sur sa solution dans le document Java(TM) 2 SDK, Standard Edition Release Notes sur java.sun.com." }, 
        { "AWT.InputMethodCreationFailed", "Impossible de créer {0}.  Raison : {1}" }, { "AWT.InputMethodLanguage.ja", "Japonais" }, { "AWT.InputMethodLanguage.ko", "Coréen" }, { "AWT.InputMethodLanguage.zh", "Chinois" }, { "AWT.InputMethodLanguage.zh_CN", "Chinois simplifié" }, { "AWT.InputMethodLanguage.zh_TW", "Chinois traditionnel" }, { "AWT.InputMethodSelectionMenu", "Sélectionner la méthode d'entrée" }, { "AWT.Less", "Inférieur à" }, { "AWT.MoveCursor", "Curseur de déplacement" }, { "AWT.NEResizeCursor", "Curseur de redimensionnement nord-est" }, 
        { "AWT.NResizeCursor", "Curseur de redimensionnement nord" }, { "AWT.NWResizeCursor", "Curseur de redimensionnement nord-ouest" }, { "AWT.SEResizeCursor", "Curseur de redimensionnement sud-est" }, { "AWT.SResizeCursor", "Curseur de redimensionnement sud" }, { "AWT.SWResizeCursor", "Curseur de redimensionnement sud-ouest" }, { "AWT.TextCursor", "Curseur de texte" }, { "AWT.WResizeCursor", "Curseur de redimensionnement ouest" }, { "AWT.WaitCursor", "Curseur d'attente" }, { "AWT.accept", "Accepter" }, { "AWT.add", "Pavé numérique +" }, 
        { "AWT.again", "Répéter" }, { "AWT.allCandidates", "Tous les candidats" }, { "AWT.alphanumeric", "Alphanumérique" }, { "AWT.alt", "Alt" }, { "AWT.altGraph", "Alt graphique" }, { "AWT.ampersand", "Esperluette" }, { "AWT.asterisk", "Astérisque" }, { "AWT.at", "A commercial" }, { "AWT.backQuote", "Accent grave avec chasse" }, { "AWT.backSlash", "Barre oblique inverse" }, 
        { "AWT.backSpace", "Retour arrière" }, { "AWT.begin", "Début" }, { "AWT.braceLeft", "Accolade ouvrante" }, { "AWT.braceRight", "Accolade fermante" }, { "AWT.cancel", "Annuler" }, { "AWT.capsLock", "Verrouillage des majuscules" }, { "AWT.circumflex", "Circonflexe" }, { "AWT.clear", "Effacer" }, { "AWT.closeBracket", "Crochet fermant" }, { "AWT.codeInput", "Entrée de code" }, 
        { "AWT.colon", "Deux-points" }, { "AWT.comma", "Virgule" }, { "AWT.compose", "Composer" }, { "AWT.context", "Menu contextuel" }, { "AWT.control", "Ctrl" }, { "AWT.convert", "Convertir" }, { "AWT.copy", "Copier" }, { "AWT.cut", "Couper" }, { "AWT.deadAboveDot", "Point en chef" }, { "AWT.deadAboveRing", "Anneau en chef" }, 
        { "AWT.deadAcute", "Accent aigu" }, { "AWT.deadBreve", "Dead Breve" }, { "AWT.deadCaron", "Caron" }, { "AWT.deadCedilla", "Cédille" }, { "AWT.deadCircumflex", "Accent circonflexe" }, { "AWT.deadDiaeresis", "Tréma" }, { "AWT.deadDoubleAcute", "Double accent aigu" }, { "AWT.deadGrave", "Accent grave" }, { "AWT.deadIota", "Iota" }, { "AWT.deadMacron", "Macron" }, 
        { "AWT.deadOgonek", "Ogonek" }, { "AWT.deadSemivoicedSound", "Son semi-voisé" }, { "AWT.deadTilde", "Tilde" }, { "AWT.deadVoicedSound", "Son voisé" }, { "AWT.decimal", "Pavé numérique ." }, { "AWT.delete", "Supprimer" }, { "AWT.divide", "Pavé numérique /" }, { "AWT.dollar", "Dollar" }, { "AWT.down", "Bas" }, { "AWT.end", "Fin" }, 
        { "AWT.enter", "Entrée" }, { "AWT.equals", "Egal" }, { "AWT.escape", "Echap" }, { "AWT.euro", "Euro" }, { "AWT.exclamationMark", "Point d'exclamation" }, { "AWT.f1", "F1" }, { "AWT.f10", "F10" }, { "AWT.f11", "F11" }, { "AWT.f12", "F12" }, { "AWT.f13", "F13" }, 
        { "AWT.f14", "F14" }, { "AWT.f15", "F15" }, { "AWT.f16", "F16" }, { "AWT.f17", "F17" }, { "AWT.f18", "F18" }, { "AWT.f19", "F19" }, { "AWT.f2", "F2" }, { "AWT.f20", "F20" }, { "AWT.f21", "F21" }, { "AWT.f22", "F22" }, 
        { "AWT.f23", "F23" }, { "AWT.f24", "F24" }, { "AWT.f3", "F3" }, { "AWT.f4", "F4" }, { "AWT.f5", "F5" }, { "AWT.f6", "F6" }, { "AWT.f7", "F7" }, { "AWT.f8", "F8" }, { "AWT.f9", "F9" }, { "AWT.final", "Final" }, 
        { "AWT.find", "Rechercher" }, { "AWT.fullWidth", "Pleine largeur" }, { "AWT.greater", "Supérieur à" }, { "AWT.halfWidth", "Demi-largeur" }, { "AWT.help", "Aide" }, { "AWT.hiragana", "Hiragana" }, { "AWT.home", "Origine" }, { "AWT.inputMethodOnOff", "Activation/désactivation de la méthode d'entrée" }, { "AWT.insert", "Insérer" }, { "AWT.invertedExclamationMark", "Point d'exclamation inversé" }, 
        { "AWT.japaneseHiragana", "Japonais Hiragana" }, { "AWT.japaneseKatakana", "Japonais Katakana" }, { "AWT.japaneseRoman", "Japonais romain" }, { "AWT.kana", "Kana" }, { "AWT.kanaLock", "Verrouiller Kana" }, { "AWT.kanji", "Kanji" }, { "AWT.katakana", "Katakana" }, { "AWT.left", "Gauche" }, { "AWT.leftParenthesis", "Parenthèse ouvrante" }, { "AWT.meta", "Méta" }, 
        { "AWT.minus", "Moins" }, { "AWT.modechange", "Changement de mode" }, { "AWT.multiply", "Pavé numérique *" }, { "AWT.noconvert", "Ne pas convertir" }, { "AWT.numLock", "Verrouillage du pavé numérique" }, { "AWT.numberSign", "Dièse" }, { "AWT.numpad", "Pavé numérique" }, { "AWT.openBracket", "Crochet ouvrant" }, { "AWT.paste", "Coller" }, { "AWT.pause", "Pause" }, 
        { "AWT.period", "Point" }, { "AWT.pgdn", "Page suivante" }, { "AWT.pgup", "Page précédente" }, { "AWT.plus", "Plus" }, { "AWT.previousCandidate", "Candidat précédent" }, { "AWT.printScreen", "Impression d'écran" }, { "AWT.props", "Props" }, { "AWT.quote", "Apostrophe" }, { "AWT.quoteDbl", "Guillemets" }, { "AWT.right", "Droite" }, 
        { "AWT.rightParenthesis", "Parenthèse fermante" }, { "AWT.romanCharacters", "Caractères romains" }, { "AWT.scrollLock", "Verrouillage du défilement" }, { "AWT.semicolon", "Point-virgule" }, { "AWT.separater", "Pavé numérique ," }, { "AWT.separator", "Pavé numérique ," }, { "AWT.shift", "Maj" }, { "AWT.slash", "Barre oblique" }, { "AWT.space", "Espace" }, { "AWT.stop", "Arrêter" }, 
        { "AWT.subtract", "Pavé numérique -" }, { "AWT.tab", "Tab" }, { "AWT.undefined", "Non défini" }, { "AWT.underscore", "Trait de soulignement" }, { "AWT.undo", "Annuler" }, { "AWT.unknown", "Inconnu" }, { "AWT.up", "Haut" }, { "AWT.windows", "Windows" }, { "java.awt.def.delay", "30" }, { "java.awt.im.style", "sur place" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\awt\resources\awt_fr.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */