package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_ja extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AWT.CompositionWindowTitle", "入力ウィンドウ" }, { "AWT.CrosshairCursor", "十字カーソル" }, { "AWT.DefaultCursor", "デフォルトのカーソル" }, { "AWT.DefaultDragCursor", "デフォルトのドラッグ・カーソル" }, { "AWT.DefaultDropCursor", "デフォルトのドロップ・カーソル" }, { "AWT.DefaultNoDropCursor", "デフォルトのドラッグ禁止カーソル" }, { "AWT.EResizeCursor", "東方向のリサイズ・カーソル" }, { "AWT.HandCursor", "指型カーソル" }, { "AWT.HostInputMethodDisplayName", "システム入力メソッド" }, { "AWT.InconsistentDLLsWarning", "システムにインストールされている一連のダイナミック・リンク・ライブラリ(DLL)に矛盾があるため、テキスト・ベースの操作が正しく動作しません。この問題の詳細と回避策は、java.sun.com上にあるJava(TM) 2 SDK, Standard Editionのリリース・ノートを参照してください。" }, 
        { "AWT.InputMethodCreationFailed", "{0}を作成できませんでした。理由: {1}" }, { "AWT.InputMethodLanguage.ja", "日本語" }, { "AWT.InputMethodLanguage.ko", "韓国語" }, { "AWT.InputMethodLanguage.zh", "中国語" }, { "AWT.InputMethodLanguage.zh_CN", "中国語(簡体字)" }, { "AWT.InputMethodLanguage.zh_TW", "中国語(繁体字)" }, { "AWT.InputMethodSelectionMenu", "入力メソッドの選択" }, { "AWT.Less", "より小さい" }, { "AWT.MoveCursor", "移動カーソル" }, { "AWT.NEResizeCursor", "北東方向のリサイズ・カーソル" }, 
        { "AWT.NResizeCursor", "北方向のリサイズ・カーソル" }, { "AWT.NWResizeCursor", "北西方向のリサイズ・カーソル" }, { "AWT.SEResizeCursor", "南東方向のリサイズ・カーソル" }, { "AWT.SResizeCursor", "南方向のリサイズ・カーソル" }, { "AWT.SWResizeCursor", "南西方向のリサイズ・カーソル" }, { "AWT.TextCursor", "テキスト・カーソル" }, { "AWT.WResizeCursor", "西方向のリサイズ・カーソル" }, { "AWT.WaitCursor", "待機カーソル" }, { "AWT.accept", "確定" }, { "AWT.add", "NumPad +" }, 
        { "AWT.again", "再度" }, { "AWT.allCandidates", "全候補" }, { "AWT.alphanumeric", "英数字" }, { "AWT.alt", "Alt" }, { "AWT.altGraph", "Altグラフ" }, { "AWT.ampersand", "アンパサンド" }, { "AWT.asterisk", "アスタリスク" }, { "AWT.at", "アット" }, { "AWT.backQuote", "逆引用符" }, { "AWT.backSlash", "バックスラッシュ" }, 
        { "AWT.backSpace", "Backspace" }, { "AWT.begin", "開始" }, { "AWT.braceLeft", "左中カッコ" }, { "AWT.braceRight", "右中カッコ" }, { "AWT.cancel", "取消" }, { "AWT.capsLock", "Caps Lock" }, { "AWT.circumflex", "曲折アクセント記号" }, { "AWT.clear", "クリア" }, { "AWT.closeBracket", "右大カッコ" }, { "AWT.codeInput", "コード入力" }, 
        { "AWT.colon", "コロン" }, { "AWT.comma", "カンマ" }, { "AWT.compose", "作成" }, { "AWT.context", "コンテキスト・メニュー" }, { "AWT.control", "Ctrl" }, { "AWT.convert", "変換" }, { "AWT.copy", "コピー" }, { "AWT.cut", "切取り" }, { "AWT.deadAboveDot", "Dead Above Dot" }, { "AWT.deadAboveRing", "Dead Above Ring" }, 
        { "AWT.deadAcute", "Dead Acute" }, { "AWT.deadBreve", "Dead Breve" }, { "AWT.deadCaron", "Dead Caron" }, { "AWT.deadCedilla", "Dead Cedilla" }, { "AWT.deadCircumflex", "Dead Circumflex" }, { "AWT.deadDiaeresis", "Dead Diaeresis" }, { "AWT.deadDoubleAcute", "Dead Double Acute" }, { "AWT.deadGrave", "Dead Grave" }, { "AWT.deadIota", "Dead Iota" }, { "AWT.deadMacron", "Dead Macron" }, 
        { "AWT.deadOgonek", "Dead Ogonek" }, { "AWT.deadSemivoicedSound", "Dead Semivoiced Sound" }, { "AWT.deadTilde", "Dead Tilde" }, { "AWT.deadVoicedSound", "Dead Voiced Sound" }, { "AWT.decimal", "NumPad ." }, { "AWT.delete", "Delete" }, { "AWT.divide", "NumPad /" }, { "AWT.dollar", "ドル" }, { "AWT.down", "下" }, { "AWT.end", "End" }, 
        { "AWT.enter", "Enter" }, { "AWT.equals", "等号" }, { "AWT.escape", "Esc" }, { "AWT.euro", "ユーロ" }, { "AWT.exclamationMark", "感嘆符" }, { "AWT.f1", "F1" }, { "AWT.f10", "F10" }, { "AWT.f11", "F11" }, { "AWT.f12", "F12" }, { "AWT.f13", "F13" }, 
        { "AWT.f14", "F14" }, { "AWT.f15", "F15" }, { "AWT.f16", "F16" }, { "AWT.f17", "F17" }, { "AWT.f18", "F18" }, { "AWT.f19", "F19" }, { "AWT.f2", "F2" }, { "AWT.f20", "F20" }, { "AWT.f21", "F21" }, { "AWT.f22", "F22" }, 
        { "AWT.f23", "F23" }, { "AWT.f24", "F24" }, { "AWT.f3", "F3" }, { "AWT.f4", "F4" }, { "AWT.f5", "F5" }, { "AWT.f6", "F6" }, { "AWT.f7", "F7" }, { "AWT.f8", "F8" }, { "AWT.f9", "F9" }, { "AWT.final", "最終" }, 
        { "AWT.find", "検索" }, { "AWT.fullWidth", "全角" }, { "AWT.greater", "より大きい" }, { "AWT.halfWidth", "半角" }, { "AWT.help", "ヘルプ" }, { "AWT.hiragana", "ひらがな" }, { "AWT.home", "Home" }, { "AWT.inputMethodOnOff", "入力メソッドOn-Off" }, { "AWT.insert", "Insert" }, { "AWT.invertedExclamationMark", "逆感嘆符" }, 
        { "AWT.japaneseHiragana", "日本語のひらがな" }, { "AWT.japaneseKatakana", "日本語のカタカナ" }, { "AWT.japaneseRoman", "日本語のローマ字" }, { "AWT.kana", "かな" }, { "AWT.kanaLock", "カナ・ロック" }, { "AWT.kanji", "漢字" }, { "AWT.katakana", "カタカナ" }, { "AWT.left", "左" }, { "AWT.leftParenthesis", "左丸カッコ" }, { "AWT.meta", "メタ" }, 
        { "AWT.minus", "マイナス" }, { "AWT.modechange", "モード変更" }, { "AWT.multiply", "NumPad *" }, { "AWT.noconvert", "無変換" }, { "AWT.numLock", "Num Lock" }, { "AWT.numberSign", "番号記号" }, { "AWT.numpad", "NumPad" }, { "AWT.openBracket", "左大カッコ" }, { "AWT.paste", "貼付け" }, { "AWT.pause", "一時停止" }, 
        { "AWT.period", "ピリオド" }, { "AWT.pgdn", "Page Down" }, { "AWT.pgup", "Page Up" }, { "AWT.plus", "プラス" }, { "AWT.previousCandidate", "前候補" }, { "AWT.printScreen", "Print Screen" }, { "AWT.props", "プロパティ" }, { "AWT.quote", "引用符" }, { "AWT.quoteDbl", "二重引用符" }, { "AWT.right", "右" }, 
        { "AWT.rightParenthesis", "右丸カッコ" }, { "AWT.romanCharacters", "ローマ字" }, { "AWT.scrollLock", "Scroll Lock" }, { "AWT.semicolon", "セミコロン" }, { "AWT.separater", "NumPad ," }, { "AWT.separator", "NumPad ," }, { "AWT.shift", "Shift" }, { "AWT.slash", "スラッシュ" }, { "AWT.space", "スペース" }, { "AWT.stop", "停止" }, 
        { "AWT.subtract", "NumPad -" }, { "AWT.tab", "Tab" }, { "AWT.undefined", "未定義" }, { "AWT.underscore", "アンダースコア" }, { "AWT.undo", "元に戻す" }, { "AWT.unknown", "不明" }, { "AWT.up", "上" }, { "AWT.windows", "Windows" }, { "java.awt.def.delay", "30" }, { "java.awt.im.style", "即座" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\awt\resources\awt_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */