package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_sv extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AWT.CompositionWindowTitle", "Inmatningsfönster" }, { "AWT.CrosshairCursor", "Hårkorsmarkör" }, { "AWT.DefaultCursor", "Standardmarkör" }, { "AWT.DefaultDragCursor", "Standarddragmarkör" }, { "AWT.DefaultDropCursor", "Standardsläppmarkör" }, { "AWT.DefaultNoDropCursor", "Standardmarkör (ej drag)" }, { "AWT.EResizeCursor", "Markör för storleksändring (öst)" }, { "AWT.HandCursor", "Handmarkör" }, { "AWT.HostInputMethodDisplayName", "Systeminmatningsmetoder" }, { "AWT.InconsistentDLLsWarning", "Textbaserade åtgärder kanske inte fungerar korrekt på grund av en inkonsekvent uppsättning dynamiskt länkade bibliotek (DLL) som är installerade i systemet. För mer information om detta problem och en tillfällig lösning, se Java(TM) 2 SDK, Standard Edition Release Notes på java.sun.com." }, 
        { "AWT.InputMethodCreationFailed", "Kan inte skapa {0}.  Orsak: {1}" }, { "AWT.InputMethodLanguage.ja", "Japanska" }, { "AWT.InputMethodLanguage.ko", "Koreanska" }, { "AWT.InputMethodLanguage.zh", "Kinesiska" }, { "AWT.InputMethodLanguage.zh_CN", "Förenklad kinesiska" }, { "AWT.InputMethodLanguage.zh_TW", "Traditionell kinesiska" }, { "AWT.InputMethodSelectionMenu", "Välj inmatningsmetod" }, { "AWT.Less", "Mindre" }, { "AWT.MoveCursor", "Flyttmarkör" }, { "AWT.NEResizeCursor", "Markör för storleksändring (nordost)" }, 
        { "AWT.NResizeCursor", "Markör för storleksändring (nord)" }, { "AWT.NWResizeCursor", "Markör för storleksändring (nordväst)" }, { "AWT.SEResizeCursor", "Markör för storleksändring (sydost)" }, { "AWT.SResizeCursor", "Markör för storleksändring (syd)" }, { "AWT.SWResizeCursor", "Markör för storleksändring (sydväst)" }, { "AWT.TextCursor", "Textmarkör" }, { "AWT.WResizeCursor", "Markör för storleksändring (väst)" }, { "AWT.WaitCursor", "Väntemarkör" }, { "AWT.accept", "Acceptera" }, { "AWT.add", "NUM +" }, 
        { "AWT.again", "Upprepa" }, { "AWT.allCandidates", "Alla kandidater" }, { "AWT.alphanumeric", "Alfanumerisk" }, { "AWT.alt", "Alt" }, { "AWT.altGraph", "Alt Graph" }, { "AWT.ampersand", "Et-tecken" }, { "AWT.asterisk", "Asterisk" }, { "AWT.at", "Vid" }, { "AWT.backQuote", "Vänster citattecken" }, { "AWT.backSlash", "Omvänt snedstreck" }, 
        { "AWT.backSpace", "Backsteg" }, { "AWT.begin", "Begin" }, { "AWT.braceLeft", "Vänster klammerparentes" }, { "AWT.braceRight", "Höger klammerparentes" }, { "AWT.cancel", "Avbryt" }, { "AWT.capsLock", "Caps Lock" }, { "AWT.circumflex", "Cirkumflex" }, { "AWT.clear", "Rensa" }, { "AWT.closeBracket", "Hakparentes" }, { "AWT.codeInput", "Kodindata" }, 
        { "AWT.colon", "Kolon" }, { "AWT.comma", "Kommatecken" }, { "AWT.compose", "Skriv" }, { "AWT.context", "Snabbmeny" }, { "AWT.control", "Ctrl" }, { "AWT.convert", "Konvertera" }, { "AWT.copy", "Kopiera" }, { "AWT.cut", "Klipp ut" }, { "AWT.deadAboveDot", "Dead Above Dot" }, { "AWT.deadAboveRing", "Dead Above Ring" }, 
        { "AWT.deadAcute", "Dead Acute" }, { "AWT.deadBreve", "Dead Breve" }, { "AWT.deadCaron", "Dead Caron" }, { "AWT.deadCedilla", "Dead Cedilla" }, { "AWT.deadCircumflex", "Dead Circumflex" }, { "AWT.deadDiaeresis", "Dead Diaeresis" }, { "AWT.deadDoubleAcute", "Dead Double Acute" }, { "AWT.deadGrave", "Dead Grave" }, { "AWT.deadIota", "Dead Iota" }, { "AWT.deadMacron", "Dead Macron" }, 
        { "AWT.deadOgonek", "Dead Ogonek" }, { "AWT.deadSemivoicedSound", "Dead Semivoiced Sound" }, { "AWT.deadTilde", "Dead Tilde" }, { "AWT.deadVoicedSound", "Dead Voiced Sound" }, { "AWT.decimal", "NUM ." }, { "AWT.delete", "Ta bort" }, { "AWT.divide", "NUM /" }, { "AWT.dollar", "Dollar" }, { "AWT.down", "Nedpil" }, { "AWT.end", "End" }, 
        { "AWT.enter", "Enter" }, { "AWT.equals", "Lika med" }, { "AWT.escape", "Esc" }, { "AWT.euro", "Euro" }, { "AWT.exclamationMark", "Utropstecken" }, { "AWT.f1", "F1" }, { "AWT.f10", "F10" }, { "AWT.f11", "F11" }, { "AWT.f12", "F12" }, { "AWT.f13", "F13" }, 
        { "AWT.f14", "F14" }, { "AWT.f15", "F15" }, { "AWT.f16", "F16" }, { "AWT.f17", "F17" }, { "AWT.f18", "F18" }, { "AWT.f19", "F19" }, { "AWT.f2", "F2" }, { "AWT.f20", "F20" }, { "AWT.f21", "F21" }, { "AWT.f22", "F22" }, 
        { "AWT.f23", "F23" }, { "AWT.f24", "F24" }, { "AWT.f3", "F3" }, { "AWT.f4", "F4" }, { "AWT.f5", "F5" }, { "AWT.f6", "F6" }, { "AWT.f7", "F7" }, { "AWT.f8", "F8" }, { "AWT.f9", "F9" }, { "AWT.final", "Slutlig" }, 
        { "AWT.find", "Sök" }, { "AWT.fullWidth", "Full bredd" }, { "AWT.greater", "Större" }, { "AWT.halfWidth", "Halv bredd" }, { "AWT.help", "Hjälp" }, { "AWT.hiragana", "Hiragana" }, { "AWT.home", "Hem" }, { "AWT.inputMethodOnOff", "Indatametod på/av" }, { "AWT.insert", "Insert" }, { "AWT.invertedExclamationMark", "Inverterat utropstecken" }, 
        { "AWT.japaneseHiragana", "Japansk Hiragana" }, { "AWT.japaneseKatakana", "Japansk Katakana" }, { "AWT.japaneseRoman", "Japanska-latinska" }, { "AWT.kana", "Kana" }, { "AWT.kanaLock", "Kana-lås" }, { "AWT.kanji", "Kanji" }, { "AWT.katakana", "Katakana" }, { "AWT.left", "Vänster" }, { "AWT.leftParenthesis", "Vänsterparentes" }, { "AWT.meta", "Meta" }, 
        { "AWT.minus", "Minus" }, { "AWT.modechange", "Ändring av läge" }, { "AWT.multiply", "NUM *" }, { "AWT.noconvert", "Ingen konvertering" }, { "AWT.numLock", "Num Lock" }, { "AWT.numberSign", "Nummertecken" }, { "AWT.numpad", "NumPad" }, { "AWT.openBracket", "Parentes" }, { "AWT.paste", "Klistra in" }, { "AWT.pause", "Paus" }, 
        { "AWT.period", "Punkt" }, { "AWT.pgdn", "Sida ned" }, { "AWT.pgup", "Sida upp" }, { "AWT.plus", "Plus" }, { "AWT.previousCandidate", "Föregående kandidat" }, { "AWT.printScreen", "Skärmutskrift" }, { "AWT.props", "Egenskaper" }, { "AWT.quote", "Citattecken" }, { "AWT.quoteDbl", "Dubbelt citattecken" }, { "AWT.right", "Höger" }, 
        { "AWT.rightParenthesis", "Högerparentes" }, { "AWT.romanCharacters", "Latinska tecken" }, { "AWT.scrollLock", "Scroll Lock" }, { "AWT.semicolon", "Semikolon" }, { "AWT.separater", "NUM ," }, { "AWT.separator", "NUM ," }, { "AWT.shift", "Skift" }, { "AWT.slash", "Snedstreck" }, { "AWT.space", "Blanksteg" }, { "AWT.stop", "Stopp" }, 
        { "AWT.subtract", "NUM -" }, { "AWT.tab", "Tabb" }, { "AWT.undefined", "Odefinierad" }, { "AWT.underscore", "Understreck" }, { "AWT.undo", "Ångra" }, { "AWT.unknown", "Okänd" }, { "AWT.up", "Upp" }, { "AWT.windows", "Windows" }, { "java.awt.def.delay", "30" }, { "java.awt.im.style", "på stället" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\awt\resources\awt_sv.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */