package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awt_ko extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "AWT.CompositionWindowTitle", "입력 창" }, { "AWT.CrosshairCursor", "십자 커서" }, { "AWT.DefaultCursor", "기본 커서" }, { "AWT.DefaultDragCursor", "기본 끌기 커서" }, { "AWT.DefaultDropCursor", "기본 놓기 커서" }, { "AWT.DefaultNoDropCursor", "기본 NoDrag 커서" }, { "AWT.EResizeCursor", "동쪽 방향 크기 조정 커서" }, { "AWT.HandCursor", "손 커서" }, { "AWT.HostInputMethodDisplayName", "시스템 입력 방법" }, { "AWT.InconsistentDLLsWarning", "시스템에 설치된 DLL(Dynamic Linking Libraries) 집합이 일치하지 않아 텍스트 기반 작업이 제대로 작동하지 않을 수 있습니다. 이 문제에 대한 자세한 내용과 해결 방법 제안 사항은 java.sun.com의 Java(TM) 2 SDK, Standard Edition Release Notes를 참조하십시오." }, 
        { "AWT.InputMethodCreationFailed", "{0}을(를) 생성할 수 없습니다. 원인: {1}" }, { "AWT.InputMethodLanguage.ja", "일본어" }, { "AWT.InputMethodLanguage.ko", "한국어" }, { "AWT.InputMethodLanguage.zh", "중국어" }, { "AWT.InputMethodLanguage.zh_CN", "중국어 간체" }, { "AWT.InputMethodLanguage.zh_TW", "중국어 번체" }, { "AWT.InputMethodSelectionMenu", "입력 방법 선택" }, { "AWT.Less", "Less" }, { "AWT.MoveCursor", "이동 커서" }, { "AWT.NEResizeCursor", "북동 방향 크기 조정 커서" }, 
        { "AWT.NResizeCursor", "북쪽 방향 크기 조정 커서" }, { "AWT.NWResizeCursor", "북서 방향 크기 조정 커서" }, { "AWT.SEResizeCursor", "남동 방향 크기 조정 커서" }, { "AWT.SResizeCursor", "남쪽 방향 크기 조정 커서" }, { "AWT.SWResizeCursor", "남서 방향 크기 조정 커서" }, { "AWT.TextCursor", "텍스트 커서" }, { "AWT.WResizeCursor", "서쪽 방향 크기 조정 커서" }, { "AWT.WaitCursor", "대기 커서" }, { "AWT.accept", "동의" }, { "AWT.add", "NumPad +" }, 
        { "AWT.again", "다시" }, { "AWT.allCandidates", "모든 후보" }, { "AWT.alphanumeric", "영숫자" }, { "AWT.alt", "Alt" }, { "AWT.altGraph", "Alt Graph" }, { "AWT.ampersand", "Ampersand" }, { "AWT.asterisk", "Asterisk" }, { "AWT.at", "At" }, { "AWT.backQuote", "Back Quote" }, { "AWT.backSlash", "Back Slash" }, 
        { "AWT.backSpace", "Backspace" }, { "AWT.begin", "Begin" }, { "AWT.braceLeft", "Left Brace" }, { "AWT.braceRight", "Right Brace" }, { "AWT.cancel", "취소" }, { "AWT.capsLock", "Caps Lock" }, { "AWT.circumflex", "Circumflex" }, { "AWT.clear", "Clear" }, { "AWT.closeBracket", "Close Bracket" }, { "AWT.codeInput", "코드 입력" }, 
        { "AWT.colon", "Colon" }, { "AWT.comma", "Comma" }, { "AWT.compose", "구성" }, { "AWT.context", "Context Menu" }, { "AWT.control", "Ctrl" }, { "AWT.convert", "변환" }, { "AWT.copy", "복사" }, { "AWT.cut", "잘라내기" }, { "AWT.deadAboveDot", "Dead Above Dot" }, { "AWT.deadAboveRing", "Dead Above Ring" }, 
        { "AWT.deadAcute", "Dead Acute" }, { "AWT.deadBreve", "Dead Breve" }, { "AWT.deadCaron", "Dead Caron" }, { "AWT.deadCedilla", "Dead Cedilla" }, { "AWT.deadCircumflex", "Dead Circumflex" }, { "AWT.deadDiaeresis", "Dead Diaeresis" }, { "AWT.deadDoubleAcute", "Dead Double Acute" }, { "AWT.deadGrave", "Dead Grave" }, { "AWT.deadIota", "Dead Iota" }, { "AWT.deadMacron", "Dead Macron" }, 
        { "AWT.deadOgonek", "Dead Ogonek" }, { "AWT.deadSemivoicedSound", "Dead Semivoiced Sound" }, { "AWT.deadTilde", "Dead Tilde" }, { "AWT.deadVoicedSound", "Dead Voiced Sound" }, { "AWT.decimal", "NumPad ." }, { "AWT.delete", "Delete" }, { "AWT.divide", "NumPad /" }, { "AWT.dollar", "Dollar" }, { "AWT.down", "Down" }, { "AWT.end", "End" }, 
        { "AWT.enter", "Enter" }, { "AWT.equals", "Equals" }, { "AWT.escape", "Escape" }, { "AWT.euro", "Euro" }, { "AWT.exclamationMark", "Exclamation Mark" }, { "AWT.f1", "F1" }, { "AWT.f10", "F10" }, { "AWT.f11", "F11" }, { "AWT.f12", "F12" }, { "AWT.f13", "F13" }, 
        { "AWT.f14", "F14" }, { "AWT.f15", "F15" }, { "AWT.f16", "F16" }, { "AWT.f17", "F17" }, { "AWT.f18", "F18" }, { "AWT.f19", "F19" }, { "AWT.f2", "F2" }, { "AWT.f20", "F20" }, { "AWT.f21", "F21" }, { "AWT.f22", "F22" }, 
        { "AWT.f23", "F23" }, { "AWT.f24", "F24" }, { "AWT.f3", "F3" }, { "AWT.f4", "F4" }, { "AWT.f5", "F5" }, { "AWT.f6", "F6" }, { "AWT.f7", "F7" }, { "AWT.f8", "F8" }, { "AWT.f9", "F9" }, { "AWT.final", "Final" }, 
        { "AWT.find", "찾기" }, { "AWT.fullWidth", "Full-Width" }, { "AWT.greater", "Greater" }, { "AWT.halfWidth", "Half-Width" }, { "AWT.help", "Help" }, { "AWT.hiragana", "히라가나" }, { "AWT.home", "Home" }, { "AWT.inputMethodOnOff", "입력 방법 설정/해제" }, { "AWT.insert", "Insert" }, { "AWT.invertedExclamationMark", "Inverted Exclamation Mark" }, 
        { "AWT.japaneseHiragana", "일본어 히라가나" }, { "AWT.japaneseKatakana", "일본어 가타카나" }, { "AWT.japaneseRoman", "일본어 로마 문자" }, { "AWT.kana", "가나" }, { "AWT.kanaLock", "가나 잠금" }, { "AWT.kanji", "간지" }, { "AWT.katakana", "가타카나" }, { "AWT.left", "Left" }, { "AWT.leftParenthesis", "Left Parenthesis" }, { "AWT.meta", "Meta" }, 
        { "AWT.minus", "Minus" }, { "AWT.modechange", "모드 변경" }, { "AWT.multiply", "NumPad *" }, { "AWT.noconvert", "변환 안함" }, { "AWT.numLock", "Num Lock" }, { "AWT.numberSign", "Number Sign" }, { "AWT.numpad", "NumPad" }, { "AWT.openBracket", "Open Bracket" }, { "AWT.paste", "붙여넣기" }, { "AWT.pause", "Pause" }, 
        { "AWT.period", "Period" }, { "AWT.pgdn", "Page Down" }, { "AWT.pgup", "Page Up" }, { "AWT.plus", "Plus" }, { "AWT.previousCandidate", "이전 후보" }, { "AWT.printScreen", "Print Screen" }, { "AWT.props", "Props" }, { "AWT.quote", "Quote" }, { "AWT.quoteDbl", "Double Quote" }, { "AWT.right", "Right" }, 
        { "AWT.rightParenthesis", "Right Parenthesis" }, { "AWT.romanCharacters", "로마 문자" }, { "AWT.scrollLock", "Scroll Lock" }, { "AWT.semicolon", "Semicolon" }, { "AWT.separater", "NumPad ," }, { "AWT.separator", "NumPad ," }, { "AWT.shift", "Shift" }, { "AWT.slash", "Slash" }, { "AWT.space", "Space" }, { "AWT.stop", "정지" }, 
        { "AWT.subtract", "NumPad -" }, { "AWT.tab", "Tab" }, { "AWT.undefined", "정의되지 않음" }, { "AWT.underscore", "Underscore" }, { "AWT.undo", "실행 취소" }, { "AWT.unknown", "알 수 없음" }, { "AWT.up", "Up" }, { "AWT.windows", "Windows" }, { "java.awt.def.delay", "30" }, { "java.awt.im.style", "on-the-spot" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\awt\resources\awt_ko.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */