package sun.security.tools.keytool;

import java.util.ListResourceBundle;

public class Resources_ja extends ListResourceBundle {
  private static final Object[][] contents = { 
      { "NEWLINE", "\n" }, { "STAR", "*******************************************" }, { "STARNN", "*******************************************\n\n" }, { ".OPTION.", " [OPTION]..." }, { "Options.", "オプション:" }, { "Use.keytool.help.for.all.available.commands", "使用可能なすべてのコマンドについては\"keytool -help\"を使用してください" }, { "Key.and.Certificate.Management.Tool", "キーおよび証明書管理ツール" }, { "Commands.", "コマンド:" }, { "Use.keytool.command.name.help.for.usage.of.command.name", "command_nameの使用方法については\"keytool -command_name -help\"を使用してください" }, { "Generates.a.certificate.request", "証明書リクエストを生成します" }, 
      { "Changes.an.entry.s.alias", "エントリの別名を変更します" }, { "Deletes.an.entry", "エントリを削除します" }, { "Exports.certificate", "証明書をエクスポートします" }, { "Generates.a.key.pair", "鍵ペアを生成します" }, { "Generates.a.secret.key", "秘密鍵を生成します" }, { "Generates.certificate.from.a.certificate.request", "証明書リクエストから証明書を生成します" }, { "Generates.CRL", "CRLを生成します" }, { "Generated.keyAlgName.secret.key", "{0}秘密鍵を生成しました" }, { "Generated.keysize.bit.keyAlgName.secret.key", "{0}ビット{1}秘密鍵を生成しました" }, { "Imports.entries.from.a.JDK.1.1.x.style.identity.database", "JDK 1.1.x-styleアイデンティティ・データベースからエントリをインポートします" }, 
      { "Imports.a.certificate.or.a.certificate.chain", "証明書または証明書チェーンをインポートします" }, { "Imports.a.password", "パスワードをインポートします" }, { "Imports.one.or.all.entries.from.another.keystore", "別のキーストアから1つまたはすべてのエントリをインポートします" }, { "Clones.a.key.entry", "鍵エントリのクローンを作成します" }, { "Changes.the.key.password.of.an.entry", "エントリの鍵パスワードを変更します" }, { "Lists.entries.in.a.keystore", "キーストア内のエントリをリストします" }, { "Prints.the.content.of.a.certificate", "証明書の内容を出力します" }, { "Prints.the.content.of.a.certificate.request", "証明書リクエストの内容を出力します" }, { "Prints.the.content.of.a.CRL.file", "CRLファイルの内容を出力します" }, { "Generates.a.self.signed.certificate", "自己署名型証明書を生成します" }, 
      { "Changes.the.store.password.of.a.keystore", "キーストアのストア・パスワードを変更します" }, { "alias.name.of.the.entry.to.process", "処理するエントリの別名" }, { "destination.alias", "出力先の別名" }, { "destination.key.password", "出力先キーのパスワード" }, { "destination.keystore.name", "出力先キーストア名" }, { "destination.keystore.password.protected", "出力先キーストアの保護対象パスワード" }, { "destination.keystore.provider.name", "出力先キーストア・プロバイダ名" }, { "destination.keystore.password", "出力先キーストアのパスワード" }, { "destination.keystore.type", "出力先キーストアのタイプ" }, { "distinguished.name", "識別名" }, 
      { "X.509.extension", "X.509拡張" }, { "output.file.name", "出力ファイル名" }, { "input.file.name", "入力ファイル名" }, { "key.algorithm.name", "鍵アルゴリズム名" }, { "key.password", "鍵のパスワード" }, { "key.bit.size", "鍵のビット・サイズ" }, { "keystore.name", "キーストア名" }, { "new.password", "新規パスワード" }, { "do.not.prompt", "プロンプトを表示しない" }, { "password.through.protected.mechanism", "保護メカニズムによるパスワード" }, 
      { "provider.argument", "プロバイダ引数" }, { "provider.class.name", "プロバイダ・クラス名" }, { "provider.name", "プロバイダ名" }, { "provider.classpath", "プロバイダ・クラスパス" }, { "output.in.RFC.style", "RFCスタイルの出力" }, { "signature.algorithm.name", "署名アルゴリズム名" }, { "source.alias", "ソース別名" }, { "source.key.password", "ソース・キーのパスワード" }, { "source.keystore.name", "ソース・キーストア名" }, { "source.keystore.password.protected", "ソース・キーストアの保護対象パスワード" }, 
      { "source.keystore.provider.name", "ソース・キーストア・プロバイダ名" }, { "source.keystore.password", "ソース・キーストアのパスワード" }, { "source.keystore.type", "ソース・キーストアのタイプ" }, { "SSL.server.host.and.port", "SSLサーバーのホストとポート" }, { "signed.jar.file", "署名付きJARファイル" }, { "certificate.validity.start.date.time", "証明書の有効開始日時" }, { "keystore.password", "キーストアのパスワード" }, { "keystore.type", "キーストアのタイプ" }, { "trust.certificates.from.cacerts", "cacertsからの証明書を信頼する" }, { "verbose.output", "詳細出力" }, 
      { "validity.number.of.days", "妥当性日数" }, { "Serial.ID.of.cert.to.revoke", "失効する証明書のシリアルID" }, { "keytool.error.", "keytoolエラー: " }, { "Illegal.option.", "不正なオプション:  " }, { "Illegal.value.", "不正な値: " }, { "Unknown.password.type.", "不明なパスワード・タイプ: " }, { "Cannot.find.environment.variable.", "環境変数が見つかりません: " }, { "Cannot.find.file.", "ファイルが見つかりません: " }, { "Command.option.flag.needs.an.argument.", "コマンド・オプション{0}には引数が必要です。" }, { "Warning.Different.store.and.key.passwords.not.supported.for.PKCS12.KeyStores.Ignoring.user.specified.command.value.", "警告: PKCS12キーストアでは、ストアのパスワードと鍵のパスワードが異なる状況はサポートされません。ユーザーが指定した{0}の値は無視します。" }, 
      { ".keystore.must.be.NONE.if.storetype.is.{0}", "-storetypeが{0}の場合、-keystoreはNONEである必要があります" }, { "Too.many.retries.program.terminated", "再試行が多すぎます。プログラムが終了しました" }, { ".storepasswd.and.keypasswd.commands.not.supported.if.storetype.is.{0}", "-storetypeが{0}の場合、-storepasswdコマンドおよび-keypasswdコマンドはサポートされません" }, { ".keypasswd.commands.not.supported.if.storetype.is.PKCS12", "-storetypeがPKCS12の場合、-keypasswdコマンドはサポートされません" }, { ".keypass.and.new.can.not.be.specified.if.storetype.is.{0}", "-storetypeが{0}の場合、-keypassと-newは指定できません" }, { "if.protected.is.specified.then.storepass.keypass.and.new.must.not.be.specified", "-protectedが指定されている場合、-storepass、-keypassおよび-newは指定できません" }, { "if.srcprotected.is.specified.then.srcstorepass.and.srckeypass.must.not.be.specified", "-srcprotectedが指定されている場合、-srcstorepassおよび-srckeypassは指定できません" }, { "if.keystore.is.not.password.protected.then.storepass.keypass.and.new.must.not.be.specified", "キーストアがパスワードで保護されていない場合、-storepass、-keypassおよび-newは指定できません" }, { "if.source.keystore.is.not.password.protected.then.srcstorepass.and.srckeypass.must.not.be.specified", "ソース・キーストアがパスワードで保護されていない場合、-srcstorepassおよび-srckeypassは指定できません" }, { "Illegal.startdate.value", "startdate値が無効です" }, 
      { "Validity.must.be.greater.than.zero", "妥当性はゼロより大きい必要があります" }, { "provName.not.a.provider", "{0}はプロバイダではありません" }, { "Usage.error.no.command.provided", "使用エラー: コマンドが指定されていません" }, { "Source.keystore.file.exists.but.is.empty.", "ソース・キーストア・ファイルは、存在しますが空です: " }, { "Please.specify.srckeystore", "-srckeystoreを指定してください" }, { "Must.not.specify.both.v.and.rfc.with.list.command", "'list'コマンドに-vと-rfcの両方を指定することはできません" }, { "Key.password.must.be.at.least.6.characters", "鍵のパスワードは6文字以上である必要があります" }, { "New.password.must.be.at.least.6.characters", "新規パスワードは6文字以上である必要があります" }, { "Keystore.file.exists.but.is.empty.", "キーストア・ファイルは存在しますが、空です: " }, { "Keystore.file.does.not.exist.", "キーストア・ファイルは存在しません: " }, 
      { "Must.specify.destination.alias", "出力先の別名を指定する必要があります" }, { "Must.specify.alias", "別名を指定する必要があります" }, { "Keystore.password.must.be.at.least.6.characters", "キーストアのパスワードは6文字以上である必要があります" }, { "Enter.the.password.to.be.stored.", "保存するパスワードを入力してください:  " }, { "Enter.keystore.password.", "キーストアのパスワードを入力してください:  " }, { "Enter.source.keystore.password.", "ソース・キーストアのパスワードを入力してください:  " }, { "Enter.destination.keystore.password.", "出力先キーストアのパスワードを入力してください:  " }, { "Keystore.password.is.too.short.must.be.at.least.6.characters", "キーストアのパスワードが短すぎます - 6文字以上にしてください" }, { "Unknown.Entry.Type", "不明なエントリ・タイプ" }, { "Too.many.failures.Alias.not.changed", "障害が多すぎます。別名は変更されません" }, 
      { "Entry.for.alias.alias.successfully.imported.", "別名{0}のエントリのインポートに成功しました。" }, { "Entry.for.alias.alias.not.imported.", "別名{0}のエントリはインポートされませんでした。" }, { "Problem.importing.entry.for.alias.alias.exception.Entry.for.alias.alias.not.imported.", "別名{0}のエントリのインポート中に問題が発生しました: {1}。\n別名{0}のエントリはインポートされませんでした。" }, { "Import.command.completed.ok.entries.successfully.imported.fail.entries.failed.or.cancelled", "インポート・コマンドが完了しました: {0}件のエントリのインポートが成功しました。{1}件のエントリのインポートが失敗したか取り消されました" }, { "Warning.Overwriting.existing.alias.alias.in.destination.keystore", "警告: 出力先キーストア内の既存の別名{0}を上書きしています" }, { "Existing.entry.alias.alias.exists.overwrite.no.", "既存のエントリの別名{0}が存在しています。上書きしますか。[いいえ]:  " }, { "Too.many.failures.try.later", "障害が多すぎます - 後で実行してください" }, { "Certification.request.stored.in.file.filename.", "認証リクエストがファイル<{0}>に保存されました" }, { "Submit.this.to.your.CA", "これをCAに提出してください" }, { "if.alias.not.specified.destalias.and.srckeypass.must.not.be.specified", "別名を指定しない場合、出力先キーストアの別名およびソース・キーストアのパスワードは指定できません" }, 
      { "The.destination.pkcs12.keystore.has.different.storepass.and.keypass.Please.retry.with.destkeypass.specified.", "出力先pkcs12キーストアに、異なるstorepassおよびkeypassがあります。-destkeypassを指定して再試行してください。" }, { "Certificate.stored.in.file.filename.", "証明書がファイル<{0}>に保存されました" }, { "Certificate.reply.was.installed.in.keystore", "証明書応答がキーストアにインストールされました" }, { "Certificate.reply.was.not.installed.in.keystore", "証明書応答がキーストアにインストールされませんでした" }, { "Certificate.was.added.to.keystore", "証明書がキーストアに追加されました" }, { "Certificate.was.not.added.to.keystore", "証明書がキーストアに追加されませんでした" }, { ".Storing.ksfname.", "[{0}を格納中]" }, { "alias.has.no.public.key.certificate.", "{0}には公開鍵(証明書)がありません" }, { "Cannot.derive.signature.algorithm", "署名アルゴリズムを取得できません" }, { "Alias.alias.does.not.exist", "別名<{0}>は存在しません" }, 
      { "Alias.alias.has.no.certificate", "別名<{0}>には証明書がありません" }, { "Key.pair.not.generated.alias.alias.already.exists", "鍵ペアは生成されませんでした。別名<{0}>はすでに存在します" }, { "Generating.keysize.bit.keyAlgName.key.pair.and.self.signed.certificate.sigAlgName.with.a.validity.of.validality.days.for", "{3}日間有効な{0}ビットの{1}の鍵ペアと自己署名型証明書({2})を生成しています\n\tディレクトリ名: {4}" }, { "Enter.key.password.for.alias.", "<{0}>の鍵パスワードを入力してください" }, { ".RETURN.if.same.as.keystore.password.", "\t(キーストアのパスワードと同じ場合はRETURNを押してください):  " }, { "Key.password.is.too.short.must.be.at.least.6.characters", "鍵のパスワードが短すぎます - 6文字以上を指定してください" }, { "Too.many.failures.key.not.added.to.keystore", "障害が多すぎます - 鍵はキーストアに追加されませんでした" }, { "Destination.alias.dest.already.exists", "出力先の別名<{0}>はすでに存在します" }, { "Password.is.too.short.must.be.at.least.6.characters", "パスワードが短すぎます - 6文字以上を指定してください" }, { "Too.many.failures.Key.entry.not.cloned", "障害が多すぎます。鍵エントリのクローンは作成されませんでした" }, 
      { "key.password.for.alias.", "<{0}>の鍵のパスワード" }, { "Keystore.entry.for.id.getName.already.exists", "<{0}>のキーストア・エントリはすでに存在します" }, { "Creating.keystore.entry.for.id.getName.", "<{0}>のキーストア・エントリを作成中..." }, { "No.entries.from.identity.database.added", "アイデンティティ・データベースから追加されたエントリはありません" }, { "Alias.name.alias", "別名: {0}" }, { "Creation.date.keyStore.getCreationDate.alias.", "作成日: {0,date}" }, { "alias.keyStore.getCreationDate.alias.", "{0},{1,date}, " }, { "alias.", "{0}, " }, { "Entry.type.type.", "エントリ・タイプ: {0}" }, { "Certificate.chain.length.", "証明書チェーンの長さ: " }, 
      { "Certificate.i.1.", "証明書[{0,number,integer}]:" }, { "Certificate.fingerprint.SHA1.", "証明書のフィンガプリント(SHA1): " }, { "Keystore.type.", "キーストアのタイプ: " }, { "Keystore.provider.", "キーストア・プロバイダ: " }, { "Your.keystore.contains.keyStore.size.entry", "キーストアには{0,number,integer}エントリが含まれます" }, { "Your.keystore.contains.keyStore.size.entries", "キーストアには{0,number,integer}エントリが含まれます" }, { "Failed.to.parse.input", "入力の構文解析に失敗しました" }, { "Empty.input", "入力がありません" }, { "Not.X.509.certificate", "X.509証明書ではありません" }, { "alias.has.no.public.key", "{0}には公開鍵がありません" }, 
      { "alias.has.no.X.509.certificate", "{0}にはX.509証明書がありません" }, { "New.certificate.self.signed.", "新しい証明書(自己署名型):" }, { "Reply.has.no.certificates", "応答には証明書がありません" }, { "Certificate.not.imported.alias.alias.already.exists", "証明書はインポートされませんでした。別名<{0}>はすでに存在します" }, { "Input.not.an.X.509.certificate", "入力はX.509証明書ではありません" }, { "Certificate.already.exists.in.keystore.under.alias.trustalias.", "証明書は、別名<{0}>のキーストアにすでに存在します" }, { "Do.you.still.want.to.add.it.no.", "追加しますか。[いいえ]:  " }, { "Certificate.already.exists.in.system.wide.CA.keystore.under.alias.trustalias.", "証明書は、別名<{0}>のシステム規模のCAキーストア内にすでに存在します" }, { "Do.you.still.want.to.add.it.to.your.own.keystore.no.", "キーストアに追加しますか。 [いいえ]:  " }, { "Trust.this.certificate.no.", "この証明書を信頼しますか。 [いいえ]:  " }, 
      { "YES", "はい" }, { "New.prompt.", "新規{0}: " }, { "Passwords.must.differ", "パスワードは異なっている必要があります" }, { "Re.enter.new.prompt.", "新規{0}を再入力してください: " }, { "Re.enter.password.", "パスワードを再入力してください: " }, { "Re.enter.new.password.", "新規パスワードを再入力してください: " }, { "They.don.t.match.Try.again", "一致しません。もう一度実行してください" }, { "Enter.prompt.alias.name.", "{0}の別名を入力してください:  " }, { "Enter.new.alias.name.RETURN.to.cancel.import.for.this.entry.", "新しい別名を入力してください\t(このエントリのインポートを取り消す場合はRETURNを押してください):  " }, { "Enter.alias.name.", "別名を入力してください:  " }, 
      { ".RETURN.if.same.as.for.otherAlias.", "\t(<{0}>と同じ場合はRETURNを押してください)" }, { "What.is.your.first.and.last.name.", "姓名は何ですか。" }, { "What.is.the.name.of.your.organizational.unit.", "組織単位名は何ですか。" }, { "What.is.the.name.of.your.organization.", "組織名は何ですか。" }, { "What.is.the.name.of.your.City.or.Locality.", "都市名または地域名は何ですか。" }, { "What.is.the.name.of.your.State.or.Province.", "都道府県名または州名は何ですか。" }, { "What.is.the.two.letter.country.code.for.this.unit.", "この単位に該当する2文字の国コードは何ですか。" }, { "Is.name.correct.", "{0}でよろしいですか。" }, { "no", "いいえ" }, { "yes", "はい" }, 
      { "y", "y" }, { ".defaultValue.", "  [{0}]:  " }, { "Alias.alias.has.no.key", "別名<{0}>には鍵がありません" }, { "Alias.alias.references.an.entry.type.that.is.not.a.private.key.entry.The.keyclone.command.only.supports.cloning.of.private.key", "別名<{0}>が参照しているエントリ・タイプは秘密鍵エントリではありません。-keycloneコマンドは秘密鍵エントリのクローン作成のみをサポートします" }, { ".WARNING.WARNING.WARNING.", "*****************  WARNING WARNING WARNING  *****************" }, { "Signer.d.", "署名者番号%d:" }, { "Timestamp.", "タイムスタンプ:" }, { "Signature.", "署名:" }, { "CRLs.", "CRL:" }, { "Certificate.owner.", "証明書の所有者: " }, 
      { "Not.a.signed.jar.file", "署名付きJARファイルではありません" }, { "No.certificate.from.the.SSL.server", "SSLサーバーからの証明書がありません" }, { ".The.integrity.of.the.information.stored.in.your.keystore.", "*キーストアに保存された情報の整合性は*\n*検証されていません。整合性を検証するには*\n*キーストアのパスワードを入力する必要があります。*" }, { ".The.integrity.of.the.information.stored.in.the.srckeystore.", "*ソース・キーストアに保存された情報の整合性は*\n*検証されていません。整合性を検証するには*\n*ソース・キーストアのパスワードを入力する必要があります。*" }, { "Certificate.reply.does.not.contain.public.key.for.alias.", "証明書応答には、<{0}>の公開鍵は含まれません" }, { "Incomplete.certificate.chain.in.reply", "応答した証明書チェーンは不完全です" }, { "Certificate.chain.in.reply.does.not.verify.", "応答した証明書チェーンは検証されていません: " }, { "Top.level.certificate.in.reply.", "応答したトップレベルの証明書:\n" }, { ".is.not.trusted.", "... は信頼されていません。 " }, { "Install.reply.anyway.no.", "応答をインストールしますか。[いいえ]:  " }, 
      { "NO", "いいえ" }, { "Public.keys.in.reply.and.keystore.don.t.match", "応答した公開鍵とキーストアが一致しません" }, { "Certificate.reply.and.certificate.in.keystore.are.identical", "証明書応答とキーストア内の証明書が同じです" }, { "Failed.to.establish.chain.from.reply", "応答から連鎖を確立できませんでした" }, { "n", "n" }, { "Wrong.answer.try.again", "応答が間違っています。もう一度実行してください" }, { "Secret.key.not.generated.alias.alias.already.exists", "秘密鍵は生成されませんでした。別名<{0}>はすでに存在します" }, { "Please.provide.keysize.for.secret.key.generation", "秘密鍵の生成時には -keysizeを指定してください" }, { "warning.not.verified.make.sure.keystore.is.correct", "警告: 検証されていません。-keystoreが正しいことを確認してください。" }, { "Extensions.", "拡張: " }, 
      { ".Empty.value.", "(空の値)" }, { "Extension.Request.", "拡張リクエスト:" }, { "Unknown.keyUsage.type.", "不明なkeyUsageタイプ: " }, { "Unknown.extendedkeyUsage.type.", "不明なextendedkeyUsageタイプ: " }, { "Unknown.AccessDescription.type.", "不明なAccessDescriptionタイプ: " }, { "Unrecognized.GeneralName.type.", "認識されないGeneralNameタイプ: " }, { "This.extension.cannot.be.marked.as.critical.", "この拡張はクリティカルとしてマーク付けできません。 " }, { "Odd.number.of.hex.digits.found.", "奇数の16進数が見つかりました: " }, { "Unknown.extension.type.", "不明な拡張タイプ: " }, { "command.{0}.is.ambiguous.", "コマンド{0}はあいまいです:" }, 
      { "the.certificate.request", "証明書リクエスト" }, { "the.issuer", "発行者" }, { "the.generated.certificate", "生成された証明書" }, { "the.generated.crl", "生成されたCRL" }, { "the.generated.certificate.request", "生成された証明書リクエスト" }, { "the.certificate", "証明書" }, { "the.crl", "CRL" }, { "the.tsa.certificate", "TSA証明書" }, { "the.input", "入力" }, { "reply", "応答" }, 
      { "one.in.many", "%1$s #%2$d / %3$d" }, { "alias.in.cacerts", "cacerts内の発行者<%s>" }, { "alias.in.keystore", "発行者<%s>" }, { "with.weak", "%s (弱)" }, { "key.bit", "%1$dビット%2$s鍵" }, { "key.bit.weak", "%1$dビット%2$s鍵(弱)" }, { ".PATTERN.printX509Cert.with.weak", "所有者: {0}\n発行者: {1}\nシリアル番号: {2}\n有効期間の開始日: {3} 終了日: {4}\n証明書のフィンガプリント:\n\t MD5:  {5}\n\t SHA1: {6}\n\t SHA256: {7}\n署名アルゴリズム名: {8}\nサブジェクト公開鍵アルゴリズム: {9}\nバージョン: {10}" }, { "PKCS.10.with.weak", "PKCS #10証明書リクエスト(バージョン1.0)\nサブジェクト: %1$s\nフォーマット: %2$s\n公開鍵: %3$s\n署名アルゴリズム: %4$s\n" }, { "verified.by.s.in.s.weak", "%2$s内の%1$sにより%3$sで検証されました" }, { "whose.sigalg.risk", "%1$sは%2$s署名アルゴリズムを使用しており、これはセキュリティ・リスクとみなされます。" }, 
      { "whose.key.risk", "%1$sは%2$sを使用しており、これはセキュリティ・リスクとみなされます。" }, { "jks.storetype.warning", "%1$sキーストアは独自の形式を使用しています。\"keytool -importkeystore -srckeystore %2$s -destkeystore %2$s -deststoretype pkcs12\"を使用する業界標準の形式であるPKCS12に移行することをお薦めします。" }, { "migrate.keystore.warning", "\"%1$s\"が%4$sに移行されました。%2$sキーストアは\"%3$s\"としてバックアップされます。" }, { "backup.keystore.warning", "元のキーストア\"%1$s\"は\"%3$s\"としてバックアップされます..." }, { "importing.keystore.status", "キーストア%1$sを%2$sにインポートしています..." } };
  
  public Object[][] getContents() { return contents; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\security\tools\keytool\Resources_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */