package com.sun.imageio.plugins.common;

import java.util.ArrayList;
import javax.imageio.ImageTypeSpecifier;
import javax.imageio.metadata.IIOMetadataFormatImpl;

public class StandardMetadataFormat extends IIOMetadataFormatImpl {
  private void addSingleAttributeElement(String paramString1, String paramString2, int paramInt) {
    addElement(paramString1, paramString2, 0);
    addAttribute(paramString1, "value", paramInt, true, null);
  }
  
  public StandardMetadataFormat() {
    super("javax_imageio_1.0", 2);
    addElement("Chroma", "javax_imageio_1.0", 2);
    addElement("ColorSpaceType", "Chroma", 0);
    ArrayList arrayList = new ArrayList();
    arrayList.add("XYZ");
    arrayList.add("Lab");
    arrayList.add("Luv");
    arrayList.add("YCbCr");
    arrayList.add("Yxy");
    arrayList.add("YCCK");
    arrayList.add("PhotoYCC");
    arrayList.add("RGB");
    arrayList.add("GRAY");
    arrayList.add("HSV");
    arrayList.add("HLS");
    arrayList.add("CMYK");
    arrayList.add("CMY");
    arrayList.add("2CLR");
    arrayList.add("3CLR");
    arrayList.add("4CLR");
    arrayList.add("5CLR");
    arrayList.add("6CLR");
    arrayList.add("7CLR");
    arrayList.add("8CLR");
    arrayList.add("9CLR");
    arrayList.add("ACLR");
    arrayList.add("BCLR");
    arrayList.add("CCLR");
    arrayList.add("DCLR");
    arrayList.add("ECLR");
    arrayList.add("FCLR");
    addAttribute("ColorSpaceType", "name", 0, true, null, arrayList);
    addElement("NumChannels", "Chroma", 0);
    addAttribute("NumChannels", "value", 2, true, 0, 2147483647);
    addElement("Gamma", "Chroma", 0);
    addAttribute("Gamma", "value", 3, true, null);
    addElement("BlackIsZero", "Chroma", 0);
    addBooleanAttribute("BlackIsZero", "value", true, true);
    addElement("Palette", "Chroma", 0, 2147483647);
    addElement("PaletteEntry", "Palette", 0);
    addAttribute("PaletteEntry", "index", 2, true, null);
    addAttribute("PaletteEntry", "red", 2, true, null);
    addAttribute("PaletteEntry", "green", 2, true, null);
    addAttribute("PaletteEntry", "blue", 2, true, null);
    addAttribute("PaletteEntry", "alpha", 2, false, "255");
    addElement("BackgroundIndex", "Chroma", 0);
    addAttribute("BackgroundIndex", "value", 2, true, null);
    addElement("BackgroundColor", "Chroma", 0);
    addAttribute("BackgroundColor", "red", 2, true, null);
    addAttribute("BackgroundColor", "green", 2, true, null);
    addAttribute("BackgroundColor", "blue", 2, true, null);
    addElement("Compression", "javax_imageio_1.0", 2);
    addSingleAttributeElement("CompressionTypeName", "Compression", 0);
    addElement("Lossless", "Compression", 0);
    addBooleanAttribute("Lossless", "value", true, true);
    addSingleAttributeElement("NumProgressiveScans", "Compression", 2);
    addSingleAttributeElement("BitRate", "Compression", 3);
    addElement("Data", "javax_imageio_1.0", 2);
    addElement("PlanarConfiguration", "Data", 0);
    arrayList = new ArrayList();
    arrayList.add("PixelInterleaved");
    arrayList.add("PlaneInterleaved");
    arrayList.add("LineInterleaved");
    arrayList.add("TileInterleaved");
    addAttribute("PlanarConfiguration", "value", 0, true, null, arrayList);
    addElement("SampleFormat", "Data", 0);
    arrayList = new ArrayList();
    arrayList.add("SignedIntegral");
    arrayList.add("UnsignedIntegral");
    arrayList.add("Real");
    arrayList.add("Index");
    addAttribute("SampleFormat", "value", 0, true, null, arrayList);
    addElement("BitsPerSample", "Data", 0);
    addAttribute("BitsPerSample", "value", 2, true, 1, 2147483647);
    addElement("SignificantBitsPerSample", "Data", 0);
    addAttribute("SignificantBitsPerSample", "value", 2, true, 1, 2147483647);
    addElement("SampleMSB", "Data", 0);
    addAttribute("SampleMSB", "value", 2, true, 1, 2147483647);
    addElement("Dimension", "javax_imageio_1.0", 2);
    addSingleAttributeElement("PixelAspectRatio", "Dimension", 3);
    addElement("ImageOrientation", "Dimension", 0);
    arrayList = new ArrayList();
    arrayList.add("Normal");
    arrayList.add("Rotate90");
    arrayList.add("Rotate180");
    arrayList.add("Rotate270");
    arrayList.add("FlipH");
    arrayList.add("FlipV");
    arrayList.add("FlipHRotate90");
    arrayList.add("FlipVRotate90");
    addAttribute("ImageOrientation", "value", 0, true, null, arrayList);
    addSingleAttributeElement("HorizontalPixelSize", "Dimension", 3);
    addSingleAttributeElement("VerticalPixelSize", "Dimension", 3);
    addSingleAttributeElement("HorizontalPhysicalPixelSpacing", "Dimension", 3);
    addSingleAttributeElement("VerticalPhysicalPixelSpacing", "Dimension", 3);
    addSingleAttributeElement("HorizontalPosition", "Dimension", 3);
    addSingleAttributeElement("VerticalPosition", "Dimension", 3);
    addSingleAttributeElement("HorizontalPixelOffset", "Dimension", 2);
    addSingleAttributeElement("VerticalPixelOffset", "Dimension", 2);
    addSingleAttributeElement("HorizontalScreenSize", "Dimension", 2);
    addSingleAttributeElement("VerticalScreenSize", "Dimension", 2);
    addElement("Document", "javax_imageio_1.0", 2);
    addElement("FormatVersion", "Document", 0);
    addAttribute("FormatVersion", "value", 0, true, null);
    addElement("SubimageInterpretation", "Document", 0);
    arrayList = new ArrayList();
    arrayList.add("Standalone");
    arrayList.add("SinglePage");
    arrayList.add("FullResolution");
    arrayList.add("ReducedResolution");
    arrayList.add("PyramidLayer");
    arrayList.add("Preview");
    arrayList.add("VolumeSlice");
    arrayList.add("ObjectView");
    arrayList.add("Panorama");
    arrayList.add("AnimationFrame");
    arrayList.add("TransparencyMask");
    arrayList.add("CompositingLayer");
    arrayList.add("SpectralSlice");
    arrayList.add("Unknown");
    addAttribute("SubimageInterpretation", "value", 0, true, null, arrayList);
    addElement("ImageCreationTime", "Document", 0);
    addAttribute("ImageCreationTime", "year", 2, true, null);
    addAttribute("ImageCreationTime", "month", 2, true, null, "1", "12", true, true);
    addAttribute("ImageCreationTime", "day", 2, true, null, "1", "31", true, true);
    addAttribute("ImageCreationTime", "hour", 2, false, "0", "0", "23", true, true);
    addAttribute("ImageCreationTime", "minute", 2, false, "0", "0", "59", true, true);
    addAttribute("ImageCreationTime", "second", 2, false, "0", "0", "60", true, true);
    addElement("ImageModificationTime", "Document", 0);
    addAttribute("ImageModificationTime", "year", 2, true, null);
    addAttribute("ImageModificationTime", "month", 2, true, null, "1", "12", true, true);
    addAttribute("ImageModificationTime", "day", 2, true, null, "1", "31", true, true);
    addAttribute("ImageModificationTime", "hour", 2, false, "0", "0", "23", true, true);
    addAttribute("ImageModificationTime", "minute", 2, false, "0", "0", "59", true, true);
    addAttribute("ImageModificationTime", "second", 2, false, "0", "0", "60", true, true);
    addElement("Text", "javax_imageio_1.0", 0, 2147483647);
    addElement("TextEntry", "Text", 0);
    addAttribute("TextEntry", "keyword", 0, false, null);
    addAttribute("TextEntry", "value", 0, true, null);
    addAttribute("TextEntry", "language", 0, false, null);
    addAttribute("TextEntry", "encoding", 0, false, null);
    arrayList = new ArrayList();
    arrayList.add("none");
    arrayList.add("lzw");
    arrayList.add("zip");
    arrayList.add("bzip");
    arrayList.add("other");
    addAttribute("TextEntry", "compression", 0, false, "none", arrayList);
    addElement("Transparency", "javax_imageio_1.0", 2);
    addElement("Alpha", "Transparency", 0);
    arrayList = new ArrayList();
    arrayList.add("none");
    arrayList.add("premultiplied");
    arrayList.add("nonpremultiplied");
    addAttribute("Alpha", "value", 0, false, "none", arrayList);
    addSingleAttributeElement("TransparentIndex", "Transparency", 2);
    addElement("TransparentColor", "Transparency", 0);
    addAttribute("TransparentColor", "value", 2, true, 0, 2147483647);
    addElement("TileTransparencies", "Transparency", 0, 2147483647);
    addElement("TransparentTile", "TileTransparencies", 0);
    addAttribute("TransparentTile", "x", 2, true, null);
    addAttribute("TransparentTile", "y", 2, true, null);
    addElement("TileOpacities", "Transparency", 0, 2147483647);
    addElement("OpaqueTile", "TileOpacities", 0);
    addAttribute("OpaqueTile", "x", 2, true, null);
    addAttribute("OpaqueTile", "y", 2, true, null);
  }
  
  public boolean canNodeAppear(String paramString, ImageTypeSpecifier paramImageTypeSpecifier) { return true; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\com\sun\imageio\plugins\common\StandardMetadataFormat.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */