package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_zh_TW extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "Automatic-Feeder", "自動饋紙器" }, { "Cassette", "卡式磁帶機" }, { "Form-Source", "表格來源" }, { "Large-Format", "大格式" }, { "Manual-Envelope", "手送封套" }, { "Small-Format", "小格式" }, { "Tractor-Feeder", "拖曳饋紙器" }, { "a", "工程 A" }, { "accepting-jobs", "接受的工作" }, { "auto-select", "自動選取" }, 
        { "b", "工程 B" }, { "border.chromaticity", "色彩外觀" }, { "border.copies", "份數" }, { "border.jobattributes", "工作屬性" }, { "border.margins", "邊距" }, { "border.media", "媒體" }, { "border.orientation", "方向" }, { "border.printrange", "列印範圍" }, { "border.printservice", "列印服務" }, { "border.quality", "品質" }, 
        { "border.sides", "邊" }, { "bottom", "下" }, { "button.cancel", "取消" }, { "button.ok", "確定" }, { "button.print", "列印" }, { "button.properties", "特性(&R)..." }, { "c", "工程 C" }, { "checkbox.collate", "理序(&C)" }, { "checkbox.jobsheets", "標題頁(&B)" }, { "checkbox.printtofile", "列印至檔案(&F)" }, 
        { "d", "工程 D" }, { "dialog.noprintermsg", "找不到列印服務。" }, { "dialog.overwrite", "這個檔案已經存在。您要覆寫已存在的檔案嗎？" }, { "dialog.owtitle", "列印至檔案" }, { "dialog.printtitle", "列印" }, { "dialog.printtofile", "列印至檔案" }, { "dialog.pstitle", "頁面設定" }, { "dialog.writeerror", "無法寫入至檔案:" }, { "e", "工程 E" }, { "envelope", "封套" }, 
        { "error.destination", "無效的檔名; 請再試一次" }, { "error.pagerange", "無效的頁面範圍; 請重新輸入數值 (例如 1-3,5,7-10)" }, { "executive", "Executive" }, { "folio", "Folio" }, { "invite-envelope", "Invitation Envelope" }, { "invoice", "Invoice" }, { "iso-2a0", "2A0 (ISO/DIN & JIS)" }, { "iso-4a0", "4A0 (ISO/DIN & JIS)" }, { "iso-a0", "A0 (ISO/DIN & JIS)" }, { "iso-a1", "A1 (ISO/DIN & JIS)" }, 
        { "iso-a10", "A10 (ISO/DIN & JIS)" }, { "iso-a2", "A2 (ISO/DIN & JIS)" }, { "iso-a3", "A3 (ISO/DIN & JIS)" }, { "iso-a4", "A4 (ISO/DIN & JIS)" }, { "iso-a5", "A5 (ISO/DIN & JIS)" }, { "iso-a6", "A6 (ISO/DIN & JIS)" }, { "iso-a7", "A7 (ISO/DIN & JIS)" }, { "iso-a8", "A8 (ISO/DIN & JIS)" }, { "iso-a9", "A9 (ISO/DIN & JIS)" }, { "iso-b0", "B0 (ISO/DIN)" }, 
        { "iso-b1", "B1 (ISO/DIN)" }, { "iso-b10", "B10 (ISO/DIN)" }, { "iso-b2", "B2 (ISO/DIN)" }, { "iso-b3", "B3 (ISO/DIN)" }, { "iso-b4", "B4 (ISO/DIN)" }, { "iso-b5", "B5 (ISO/DIN)" }, { "iso-b6", "B6 (ISO/DIN)" }, { "iso-b7", "B7 (ISO/DIN)" }, { "iso-b8", "B8 (ISO/DIN)" }, { "iso-b9", "B9 (ISO/DIN)" }, 
        { "iso-c0", "C0 (ISO/DIN)" }, { "iso-c1", "C1 (ISO/DIN)" }, { "iso-c10", "C10 (ISO/DIN)" }, { "iso-c2", "C2 (ISO/DIN)" }, { "iso-c3", "C3 (ISO/DIN)" }, { "iso-c4", "C4 (ISO/DIN)" }, { "iso-c5", "C5 (ISO/DIN)" }, { "iso-c6", "C6 (ISO/DIN)" }, { "iso-c7", "C7 (ISO/DIN)" }, { "iso-c8", "C8 (ISO/DIN)" }, 
        { "iso-c9", "C9 (ISO/DIN)" }, { "iso-designated-long", "ISO Designated Long" }, { "italian-envelope", "Italy Envelope" }, { "italy-envelope", "Italy Envelope" }, { "japanese-postcard", "Postcard (JIS)" }, { "jis-b0", "B0 (JIS)" }, { "jis-b1", "B1 (JIS)" }, { "jis-b10", "B10 (JIS)" }, { "jis-b2", "B2 (JIS)" }, { "jis-b3", "B3 (JIS)" }, 
        { "jis-b4", "B4 (JIS)" }, { "jis-b5", "B5 (JIS)" }, { "jis-b6", "B6 (JIS)" }, { "jis-b7", "B7 (JIS)" }, { "jis-b8", "B8 (JIS)" }, { "jis-b9", "B9 (JIS)" }, { "label.bottommargin", "底部邊距(&B)" }, { "label.inches", "(in)" }, { "label.info", "資訊: " }, { "label.jobname", "工作名稱(&J):" }, 
        { "label.leftmargin", "左邊距(&F)" }, { "label.millimetres", "(mm)" }, { "label.numcopies", "列印份數(&O): " }, { "label.priority", "優先權(&R):" }, { "label.psname", "名稱(&N):" }, { "label.pstype", "類型: " }, { "label.rangeto", "至" }, { "label.rightmargin", "右邊距(&R)" }, { "label.size", "大小(&Z):" }, { "label.source", "來源(&C): " }, 
        { "label.status", "狀態: " }, { "label.topmargin", "頂端邊距(&T)" }, { "label.username", "使用者名稱(&U):" }, { "large-capacity", "大容量" }, { "ledger", "Ledger" }, { "main", "主" }, { "manual", "手送" }, { "middle", "中" }, { "monarch-envelope", "Monarch Envelope" }, { "na-10x13-envelope", "10x15 Envelope" }, 
        { "na-10x14-envelope", "10x15 Envelope" }, { "na-10x15-envelope", "10x15 Envelope" }, { "na-5x7", "5\" x 7\" Paper" }, { "na-6x9-envelope", "6x9 Envelope" }, { "na-7x9-envelope", "6x7 Envelope" }, { "na-8x10", "8\" x 10\" Paper" }, { "na-9x11-envelope", "9x11 Envelope" }, { "na-9x12-envelope", "9x12 Envelope" }, { "na-legal", "Legal" }, { "na-letter", "Letter" }, 
        { "na-number-10-envelope", "No. 10 Envelope" }, { "na-number-11-envelope", "No. 11 Envelope" }, { "na-number-12-envelope", "No. 12 Envelope" }, { "na-number-14-envelope", "No. 14 Envelope" }, { "na-number-9-envelope", "No. 9 Envelope" }, { "not-accepting-jobs", "不接受的工作" }, { "oufuko-postcard", "Double Postcard (JIS)" }, { "personal-envelope", "Personal Envelope" }, { "quarto", "Quarto" }, { "radiobutton.color", "顏色(&C)" }, 
        { "radiobutton.draftq", "草稿(&F)" }, { "radiobutton.duplex", "雙面列印(&D)" }, { "radiobutton.highq", "高(&H)" }, { "radiobutton.landscape", "橫向(&L)" }, { "radiobutton.monochrome", "單色(&M)" }, { "radiobutton.normalq", "正常(&N)" }, { "radiobutton.oneside", "單面(&O)" }, { "radiobutton.portrait", "直向(&P)" }, { "radiobutton.rangeall", "全部(&L)" }, { "radiobutton.rangepages", "頁面(&E)" }, 
        { "radiobutton.revlandscape", "反向橫印(&N)" }, { "radiobutton.revportrait", "反向直印(&I)" }, { "radiobutton.tumble", "翻轉(&T)" }, { "side", "邊" }, { "tab.appearance", "外觀(&A)" }, { "tab.general", "一般(&G)" }, { "tab.pagesetup", "頁面設定(&S)" }, { "tabloid", "Tabloid" }, { "top", "上" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\print\resources\serviceui_zh_TW.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */