package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_ko extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "Automatic-Feeder", "자동 공급기" }, { "Cassette", "카세트" }, { "Form-Source", "양식 소스" }, { "Large-Format", "큰 형식" }, { "Manual-Envelope", "수동 봉투" }, { "Small-Format", "작은 형식" }, { "Tractor-Feeder", "트랙터 공급기" }, { "a", "Engineering A" }, { "accepting-jobs", "작업 승인" }, { "auto-select", "자동 선택" }, 
        { "b", "Engineering B" }, { "border.chromaticity", "색상 모양" }, { "border.copies", "복사" }, { "border.jobattributes", "작업 속성" }, { "border.margins", "여백" }, { "border.media", "매체" }, { "border.orientation", "방향" }, { "border.printrange", "인쇄 범위" }, { "border.printservice", "인쇄 서비스" }, { "border.quality", "품질" }, 
        { "border.sides", "측면" }, { "bottom", "아래쪽" }, { "button.cancel", "취소" }, { "button.ok", "확인" }, { "button.print", "인쇄" }, { "button.properties", "속성(&R)..." }, { "c", "Engineering C" }, { "checkbox.collate", "한 부씩 인쇄(&C)" }, { "checkbox.jobsheets", "배너 페이지(&B)" }, { "checkbox.printtofile", "파일로 인쇄(&F)" }, 
        { "d", "Engineering D" }, { "dialog.noprintermsg", "인쇄 서비스를 찾을 수 없습니다." }, { "dialog.overwrite", "이 파일이 존재합니다. 기존 파일을 겹쳐 쓰겠습니까?" }, { "dialog.owtitle", "파일로 인쇄" }, { "dialog.printtitle", "인쇄" }, { "dialog.printtofile", "파일로 인쇄" }, { "dialog.pstitle", "페이지 설정" }, { "dialog.writeerror", "파일에 쓸 수 없음:" }, { "e", "Engineering E" }, { "envelope", "Envelope" }, 
        { "error.destination", "부적합한 파일 이름: 다시 시도하십시오." }, { "error.pagerange", "부적합한 페이지 범위: 값을 다시 입력하십시오(예: 1-3,5,7-10)." }, { "executive", "Executive" }, { "folio", "Folio" }, { "invite-envelope", "Invitation Envelope" }, { "invoice", "Invoice" }, { "iso-2a0", "2A0 (ISO/DIN & JIS)" }, { "iso-4a0", "4A0 (ISO/DIN & JIS)" }, { "iso-a0", "A0 (ISO/DIN & JIS)" }, { "iso-a1", "A1 (ISO/DIN & JIS)" }, 
        { "iso-a10", "A10 (ISO/DIN & JIS)" }, { "iso-a2", "A2 (ISO/DIN & JIS)" }, { "iso-a3", "A3 (ISO/DIN & JIS)" }, { "iso-a4", "A4 (ISO/DIN & JIS)" }, { "iso-a5", "A5 (ISO/DIN & JIS)" }, { "iso-a6", "A6 (ISO/DIN & JIS)" }, { "iso-a7", "A7 (ISO/DIN & JIS)" }, { "iso-a8", "A8 (ISO/DIN & JIS)" }, { "iso-a9", "A9 (ISO/DIN & JIS)" }, { "iso-b0", "B0 (ISO/DIN)" }, 
        { "iso-b1", "B1 (ISO/DIN)" }, { "iso-b10", "B10 (ISO/DIN)" }, { "iso-b2", "B2 (ISO/DIN)" }, { "iso-b3", "B3 (ISO/DIN)" }, { "iso-b4", "B4 (ISO/DIN)" }, { "iso-b5", "B5 (ISO/DIN)" }, { "iso-b6", "B6 (ISO/DIN)" }, { "iso-b7", "B7 (ISO/DIN)" }, { "iso-b8", "B8 (ISO/DIN)" }, { "iso-b9", "B9 (ISO/DIN)" }, 
        { "iso-c0", "C0 (ISO/DIN)" }, { "iso-c1", "C1 (ISO/DIN)" }, { "iso-c10", "C10 (ISO/DIN)" }, { "iso-c2", "C2 (ISO/DIN)" }, { "iso-c3", "C3 (ISO/DIN)" }, { "iso-c4", "C4 (ISO/DIN)" }, { "iso-c5", "C5 (ISO/DIN)" }, { "iso-c6", "C6 (ISO/DIN)" }, { "iso-c7", "C7 (ISO/DIN)" }, { "iso-c8", "C8 (ISO/DIN)" }, 
        { "iso-c9", "C9 (ISO/DIN)" }, { "iso-designated-long", "ISO Designated Long" }, { "italian-envelope", "Italy Envelope" }, { "italy-envelope", "Italy Envelope" }, { "japanese-postcard", "Postcard (JIS)" }, { "jis-b0", "B0 (JIS)" }, { "jis-b1", "B1 (JIS)" }, { "jis-b10", "B10 (JIS)" }, { "jis-b2", "B2 (JIS)" }, { "jis-b3", "B3 (JIS)" }, 
        { "jis-b4", "B4 (JIS)" }, { "jis-b5", "B5 (JIS)" }, { "jis-b6", "B6 (JIS)" }, { "jis-b7", "B7 (JIS)" }, { "jis-b8", "B8 (JIS)" }, { "jis-b9", "B9 (JIS)" }, { "label.bottommargin", "아래쪽(&B)" }, { "label.inches", "(인치)" }, { "label.info", "정보:" }, { "label.jobname", "작업 이름(&J):" }, 
        { "label.leftmargin", "왼쪽(&F)" }, { "label.millimetres", "(mm)" }, { "label.numcopies", "매수(&O):" }, { "label.priority", "우선순위(&R):" }, { "label.psname", "이름(&N):" }, { "label.pstype", "유형:" }, { "label.rangeto", "종료" }, { "label.rightmargin", "오른쪽(&R)" }, { "label.size", "크기(&Z):" }, { "label.source", "소스(&C):" }, 
        { "label.status", "상태:" }, { "label.topmargin", "위쪽(&T)" }, { "label.username", "사용자 이름(&U):" }, { "large-capacity", "큰 용량" }, { "ledger", "Ledger" }, { "main", "주" }, { "manual", "수동" }, { "middle", "가운데" }, { "monarch-envelope", "Monarch Envelope" }, { "na-10x13-envelope", "10x15 Envelope" }, 
        { "na-10x14-envelope", "10x15 Envelope" }, { "na-10x15-envelope", "10x15 Envelope" }, { "na-5x7", "5\" x 7\" 용지" }, { "na-6x9-envelope", "6x9 Envelope" }, { "na-7x9-envelope", "6x7 Envelope" }, { "na-8x10", "8\" x 10\" 용지" }, { "na-9x11-envelope", "9x11 Envelope" }, { "na-9x12-envelope", "9x12 Envelope" }, { "na-legal", "Legal" }, { "na-letter", "Letter" }, 
        { "na-number-10-envelope", "No. 10 Envelope" }, { "na-number-11-envelope", "No. 11 Envelope" }, { "na-number-12-envelope", "No. 12 Envelope" }, { "na-number-14-envelope", "No. 14 Envelope" }, { "na-number-9-envelope", "No. 9 Envelope" }, { "not-accepting-jobs", "작업 승인 안함" }, { "oufuko-postcard", "Double Postcard (JIS)" }, { "personal-envelope", "Personal Envelope" }, { "quarto", "Quarto" }, { "radiobutton.color", "색상(&C)" }, 
        { "radiobutton.draftq", "초안(&F)" }, { "radiobutton.duplex", "양면(&D)" }, { "radiobutton.highq", "높음(&H)" }, { "radiobutton.landscape", "가로(&L)" }, { "radiobutton.monochrome", "단색(&M)" }, { "radiobutton.normalq", "보통(&N)" }, { "radiobutton.oneside", "단면(&O)" }, { "radiobutton.portrait", "세로(&P)" }, { "radiobutton.rangeall", "전체(&L)" }, { "radiobutton.rangepages", "페이지(&E)" }, 
        { "radiobutton.revlandscape", "가로 반전(&N)" }, { "radiobutton.revportrait", "세로 반전(&I)" }, { "radiobutton.tumble", "회전식(&T)" }, { "side", "측면" }, { "tab.appearance", "모양(&A)" }, { "tab.general", "일반 사항(&G)" }, { "tab.pagesetup", "페이지 설정(&S)" }, { "tabloid", "Tabloid" }, { "top", "위쪽" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\print\resources\serviceui_ko.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */