package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_ja extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "Automatic-Feeder", "自動フィーダ" }, { "Cassette", "カセット" }, { "Form-Source", "フォーム・ソース" }, { "Large-Format", "ラージ・フォーマット" }, { "Manual-Envelope", "マニュアル封筒" }, { "Small-Format", "スモール・フォーマット" }, { "Tractor-Feeder", "トラクタ・フィーダ" }, { "a", "エンジニアリングA" }, { "accepting-jobs", "ジョブを受け付けています" }, { "auto-select", "自動選択" }, 
        { "b", "エンジニアリングB" }, { "border.chromaticity", "色の表現" }, { "border.copies", "印刷部数" }, { "border.jobattributes", "ジョブの属性" }, { "border.margins", "マージン" }, { "border.media", "メディア" }, { "border.orientation", "用紙の向き" }, { "border.printrange", "印刷範囲" }, { "border.printservice", "印刷サービス" }, { "border.quality", "品質" }, 
        { "border.sides", "面" }, { "bottom", "下部" }, { "button.cancel", "取消" }, { "button.ok", "OK" }, { "button.print", "印刷" }, { "button.properties", "プロパティ(&R)..." }, { "c", "エンジニアリングC" }, { "checkbox.collate", "丁合い(&C)" }, { "checkbox.jobsheets", "バナー・ページ(&B)" }, { "checkbox.printtofile", "ファイルに出力(&F)" }, 
        { "d", "エンジニアリングD" }, { "dialog.noprintermsg", "印刷サービスが見つかりません。" }, { "dialog.overwrite", "このファイルはすでに存在します。既存のファイルに上書きしますか。" }, { "dialog.owtitle", "ファイルに出力" }, { "dialog.printtitle", "印刷" }, { "dialog.printtofile", "ファイルに出力" }, { "dialog.pstitle", "ページ設定" }, { "dialog.writeerror", "ファイルに書き込めません:" }, { "e", "エンジニアリングE" }, { "envelope", "封筒" }, 
        { "error.destination", "無効なファイル名。ファイル名を再入力してください" }, { "error.pagerange", "無効なページ範囲。値を再入力してください(例、1-3,5,7-10)" }, { "executive", "エグゼクティブ" }, { "folio", "フォリオ" }, { "invite-envelope", "招待封筒" }, { "invoice", "インボイス" }, { "iso-2a0", "2A0 (ISO/DIN & JIS)" }, { "iso-4a0", "4A0 (ISO/DIN & JIS)" }, { "iso-a0", "A0 (ISO/DIN & JIS)" }, { "iso-a1", "A1 (ISO/DIN & JIS)" }, 
        { "iso-a10", "A10 (ISO/DIN & JIS)" }, { "iso-a2", "A2 (ISO/DIN & JIS)" }, { "iso-a3", "A3 (ISO/DIN & JIS)" }, { "iso-a4", "A4 (ISO/DIN & JIS)" }, { "iso-a5", "A5 (ISO/DIN & JIS)" }, { "iso-a6", "A6 (ISO/DIN & JIS)" }, { "iso-a7", "A7 (ISO/DIN & JIS)" }, { "iso-a8", "A8 (ISO/DIN & JIS)" }, { "iso-a9", "A9 (ISO/DIN & JIS)" }, { "iso-b0", "B0 (ISO/DIN)" }, 
        { "iso-b1", "B1 (ISO/DIN)" }, { "iso-b10", "B10 (ISO/DIN)" }, { "iso-b2", "B2 (ISO/DIN)" }, { "iso-b3", "B3 (ISO/DIN)" }, { "iso-b4", "B4 (ISO/DIN)" }, { "iso-b5", "B5 (ISO/DIN)" }, { "iso-b6", "B6 (ISO/DIN)" }, { "iso-b7", "B7 (ISO/DIN)" }, { "iso-b8", "B8 (ISO/DIN)" }, { "iso-b9", "B9 (ISO/DIN)" }, 
        { "iso-c0", "C0 (ISO/DIN)" }, { "iso-c1", "C1 (ISO/DIN)" }, { "iso-c10", "C10 (ISO/DIN)" }, { "iso-c2", "C2 (ISO/DIN)" }, { "iso-c3", "C3 (ISO/DIN)" }, { "iso-c4", "C4 (ISO/DIN)" }, { "iso-c5", "C5 (ISO/DIN)" }, { "iso-c6", "C6 (ISO/DIN)" }, { "iso-c7", "C7 (ISO/DIN)" }, { "iso-c8", "C8 (ISO/DIN)" }, 
        { "iso-c9", "C9 (ISO/DIN)" }, { "iso-designated-long", "ISO DL(長寸)" }, { "italian-envelope", "イタリア封筒" }, { "italy-envelope", "イタリア封筒" }, { "japanese-postcard", "はがき(JIS)" }, { "jis-b0", "B0 (JIS)" }, { "jis-b1", "B1 (JIS)" }, { "jis-b10", "B10 (JIS)" }, { "jis-b2", "B2 (JIS)" }, { "jis-b3", "B3 (JIS)" }, 
        { "jis-b4", "B4 (JIS)" }, { "jis-b5", "B5 (JIS)" }, { "jis-b6", "B6 (JIS)" }, { "jis-b7", "B7 (JIS)" }, { "jis-b8", "B8 (JIS)" }, { "jis-b9", "B9 (JIS)" }, { "label.bottommargin", "下(&B)" }, { "label.inches", "(in)" }, { "label.info", "情報:" }, { "label.jobname", "ジョブ名(&J):" }, 
        { "label.leftmargin", "左(&F)" }, { "label.millimetres", "(mm)" }, { "label.numcopies", "印刷部数(&O):" }, { "label.priority", "優先度(&R):" }, { "label.psname", "名前(&N):" }, { "label.pstype", "タイプ:" }, { "label.rangeto", "印刷範囲" }, { "label.rightmargin", "右(&R)" }, { "label.size", "サイズ(&Z):" }, { "label.source", "ソース(&C):" }, 
        { "label.status", "状態:" }, { "label.topmargin", "上(&T)" }, { "label.username", "ユーザー名(&U):" }, { "large-capacity", "大容量" }, { "ledger", "レッジャ" }, { "main", "メイン" }, { "manual", "マニュアル" }, { "middle", "中間" }, { "monarch-envelope", "モナーク封筒" }, { "na-10x13-envelope", "10x15封筒" }, 
        { "na-10x14-envelope", "10x15封筒" }, { "na-10x15-envelope", "10x15封筒" }, { "na-5x7", "5x7インチ用紙" }, { "na-6x9-envelope", "6x9封筒" }, { "na-7x9-envelope", "6x7封筒" }, { "na-8x10", "8x10インチ用紙" }, { "na-9x11-envelope", "9x11封筒" }, { "na-9x12-envelope", "9x12封筒" }, { "na-legal", "リーガル" }, { "na-letter", "レター" }, 
        { "na-number-10-envelope", "No. 10封筒" }, { "na-number-11-envelope", "No. 11封筒" }, { "na-number-12-envelope", "No. 12封筒" }, { "na-number-14-envelope", "No. 14封筒" }, { "na-number-9-envelope", "No. 9封筒" }, { "not-accepting-jobs", "ジョブを受け付けません" }, { "oufuko-postcard", "往復はがき(JIS)" }, { "personal-envelope", "個人用封筒" }, { "quarto", "クォート" }, { "radiobutton.color", "カラー(&C)" }, 
        { "radiobutton.draftq", "ドラフト(&F)" }, { "radiobutton.duplex", "両面(&D)" }, { "radiobutton.highq", "高(&H)" }, { "radiobutton.landscape", "横(&L)" }, { "radiobutton.monochrome", "モノクロ(&M)" }, { "radiobutton.normalq", "標準(&N)" }, { "radiobutton.oneside", "片面(&O)" }, { "radiobutton.portrait", "縦(&P)" }, { "radiobutton.rangeall", "すべて(&L)" }, { "radiobutton.rangepages", "ページ(&E)" }, 
        { "radiobutton.revlandscape", "ランドスケープ(反転)(&N)" }, { "radiobutton.revportrait", "ポートレイト(反転)(&I)" }, { "radiobutton.tumble", "反転(&T)" }, { "side", "面" }, { "tab.appearance", "外観(&A)" }, { "tab.general", "一般(&G)" }, { "tab.pagesetup", "ページ設定(&S)" }, { "tabloid", "タブロイド" }, { "top", "上部" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\print\resources\serviceui_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */