package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_es extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "Automatic-Feeder", "Alimentador Automático" }, { "Cassette", "Casete" }, { "Form-Source", "Origen de Formulario" }, { "Large-Format", "Formato Grande" }, { "Manual-Envelope", "Sobre Manual" }, { "Small-Format", "Formato Pequeño" }, { "Tractor-Feeder", "Alimentador de Arrastre" }, { "a", "Ingeniería A" }, { "accepting-jobs", "Aceptando trabajos" }, { "auto-select", "Seleccionar Automáticamente" }, 
        { "b", "Ingeniería B" }, { "border.chromaticity", "Apariencia del Color" }, { "border.copies", "Copias" }, { "border.jobattributes", "Atributos del Trabajo" }, { "border.margins", "Márgenes" }, { "border.media", "Soporte" }, { "border.orientation", "Orientación" }, { "border.printrange", "Rango de Impresión" }, { "border.printservice", "Servicio de Impresión" }, { "border.quality", "Calidad" }, 
        { "border.sides", "Caras" }, { "bottom", "Abajo" }, { "button.cancel", "Cancelar" }, { "button.ok", "Aceptar" }, { "button.print", "Imprimir" }, { "button.properties", "P&ropiedades..." }, { "c", "Ingeniería C" }, { "checkbox.collate", "Inter&calar" }, { "checkbox.jobsheets", "Página de Rótu&lo" }, { "checkbox.printtofile", "I&mprimir en Archivo" }, 
        { "d", "Ingeniería D" }, { "dialog.noprintermsg", "No se ha encontrado el servicio de impresión." }, { "dialog.overwrite", "Este archivo ya existe. ¿Desea sobrescribirlo?" }, { "dialog.owtitle", "Imprimir en Archivo" }, { "dialog.printtitle", "Imprimir" }, { "dialog.printtofile", "Imprimir en Archivo" }, { "dialog.pstitle", "Preparar Página" }, { "dialog.writeerror", "No se puede escribir en el archivo:" }, { "e", "Ingeniería E" }, { "envelope", "Sobre" }, 
        { "error.destination", "Nombre de archivo no válido; inténtelo de nuevo" }, { "error.pagerange", "Rango de páginas no válido; vuelva a introducir los valores (por ejemplo, 1-3, 5, 7-10)" }, { "executive", "Ejecutivo" }, { "folio", "Folio" }, { "invite-envelope", "Sobre de Invitación" }, { "invoice", "Factura" }, { "iso-2a0", "2A0 (ISO/DIN & JIS)" }, { "iso-4a0", "4A0 (ISO/DIN & JIS)" }, { "iso-a0", "A0 (ISO/DIN & JIS)" }, { "iso-a1", "A1 (ISO/DIN & JIS)" }, 
        { "iso-a10", "A10 (ISO/DIN & JIS)" }, { "iso-a2", "A2 (ISO/DIN & JIS)" }, { "iso-a3", "A3 (ISO/DIN & JIS)" }, { "iso-a4", "A4 (ISO/DIN & JIS)" }, { "iso-a5", "A5 (ISO/DIN & JIS)" }, { "iso-a6", "A6 (ISO/DIN & JIS)" }, { "iso-a7", "A7 (ISO/DIN & JIS)" }, { "iso-a8", "A8 (ISO/DIN & JIS)" }, { "iso-a9", "A9 (ISO/DIN & JIS)" }, { "iso-b0", "B0 (ISO/DIN)" }, 
        { "iso-b1", "B1 (ISO/DIN)" }, { "iso-b10", "B10 (ISO/DIN)" }, { "iso-b2", "B2 (ISO/DIN)" }, { "iso-b3", "B3 (ISO/DIN)" }, { "iso-b4", "B4 (ISO/DIN)" }, { "iso-b5", "B5 (ISO/DIN)" }, { "iso-b6", "B6 (ISO/DIN)" }, { "iso-b7", "B7 (ISO/DIN)" }, { "iso-b8", "B8 (ISO/DIN)" }, { "iso-b9", "B9 (ISO/DIN)" }, 
        { "iso-c0", "C0 (ISO/DIN)" }, { "iso-c1", "C1 (ISO/DIN)" }, { "iso-c10", "C10 (ISO/DIN)" }, { "iso-c2", "C2 (ISO/DIN)" }, { "iso-c3", "C3 (ISO/DIN)" }, { "iso-c4", "C4 (ISO/DIN)" }, { "iso-c5", "C5 (ISO/DIN)" }, { "iso-c6", "C6 (ISO/DIN)" }, { "iso-c7", "C7 (ISO/DIN)" }, { "iso-c8", "C8 (ISO/DIN)" }, 
        { "iso-c9", "C9 (ISO/DIN)" }, { "iso-designated-long", "Largo Designado ISO" }, { "italian-envelope", "Sobre Italiano" }, { "italy-envelope", "Sobre Italiano" }, { "japanese-postcard", "Postal (JIS)" }, { "jis-b0", "B0 (JIS)" }, { "jis-b1", "B1 (JIS)" }, { "jis-b10", "B10 (JIS)" }, { "jis-b2", "B2 (JIS)" }, { "jis-b3", "B3 (JIS)" }, 
        { "jis-b4", "B4 (JIS)" }, { "jis-b5", "B5 (JIS)" }, { "jis-b6", "B6 (JIS)" }, { "jis-b7", "B7 (JIS)" }, { "jis-b8", "B8 (JIS)" }, { "jis-b9", "B9 (JIS)" }, { "label.bottommargin", "in&ferior" }, { "label.inches", "(pulg.)" }, { "label.info", "Información:" }, { "label.jobname", "&Nombre del Trabajo:" }, 
        { "label.leftmargin", "iz&quierdo" }, { "label.millimetres", "(mm)" }, { "label.numcopies", "Número de C&opias:" }, { "label.priority", "Prior&idad:" }, { "label.psname", "&Nombre:" }, { "label.pstype", "Tipo:" }, { "label.rangeto", "A" }, { "label.rightmargin", "d&erecho" }, { "label.size", "Tama&ño:" }, { "label.source", "Orig&en:" }, 
        { "label.status", "Estado:" }, { "label.topmargin", "s&uperior" }, { "label.username", "&Usuario:" }, { "large-capacity", "Gran Capacidad" }, { "ledger", "Libro Mayor" }, { "main", "Principal" }, { "manual", "Manual" }, { "middle", "Centro" }, { "monarch-envelope", "Sobre Monarch" }, { "na-10x13-envelope", "Sobre 10x15" }, 
        { "na-10x14-envelope", "Sobre 10x15" }, { "na-10x15-envelope", "Sobre 10x15" }, { "na-5x7", "Papel 5\" x 7\"" }, { "na-6x9-envelope", "Sobre 6x9" }, { "na-7x9-envelope", "Sobre 6x7" }, { "na-8x10", "Papel 8\" x 10\"" }, { "na-9x11-envelope", "Sobre 9x11" }, { "na-9x12-envelope", "Sobre 9x12" }, { "na-legal", "Legal" }, { "na-letter", "Carta" }, 
        { "na-number-10-envelope", "Sobre Nº 10" }, { "na-number-11-envelope", "Sobre Nº 11" }, { "na-number-12-envelope", "Sobre Nº 12" }, { "na-number-14-envelope", "Sobre Nº 14" }, { "na-number-9-envelope", "Sobre Nº 9" }, { "not-accepting-jobs", "No aceptando trabajos" }, { "oufuko-postcard", "Postal Doble (JIS)" }, { "personal-envelope", "Sobre Personal" }, { "quarto", "Cuarto" }, { "radiobutton.color", "&Color" }, 
        { "radiobutton.draftq", "B&orrador" }, { "radiobutton.duplex", "&Dúplex" }, { "radiobutton.highq", "Al&ta" }, { "radiobutton.landscape", "Hori&zontal" }, { "radiobutton.monochrome", "&Monocromo" }, { "radiobutton.normalq", "&Normal" }, { "radiobutton.oneside", "Una Ca&ra" }, { "radiobutton.portrait", "&Vertical" }, { "radiobutton.rangeall", "&Todo" }, { "radiobutton.rangepages", "Página&s" }, 
        { "radiobutton.revlandscape", "&Horizontal Inverso" }, { "radiobutton.revportrait", "Vertical I&nverso" }, { "radiobutton.tumble", "Cam&bio de Cara" }, { "side", "Cara" }, { "tab.appearance", "&Apariencia" }, { "tab.general", "&General" }, { "tab.pagesetup", "&Preparar Página" }, { "tabloid", "Tabloide" }, { "top", "Arriba" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\print\resources\serviceui_es.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */