package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_sv extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "Automatic-Feeder", "Automatisk matning" }, { "Cassette", "Kassett" }, { "Form-Source", "Formulärkälla" }, { "Large-Format", "Stort format" }, { "Manual-Envelope", "Manuell kuvertmatning" }, { "Small-Format", "Litet format" }, { "Tractor-Feeder", "Traktormatning" }, { "a", "Engineering A" }, { "accepting-jobs", "Accepterar jobb" }, { "auto-select", "Välj automatiskt" }, 
        { "b", "Engineering B" }, { "border.chromaticity", "Färg" }, { "border.copies", "Antal exemplar" }, { "border.jobattributes", "Utskriftsattribut" }, { "border.margins", "Marginaler" }, { "border.media", "Media" }, { "border.orientation", "Orientering" }, { "border.printrange", "Utskriftsintervall" }, { "border.printservice", "Utskriftstjänst" }, { "border.quality", "Kvalitet" }, 
        { "border.sides", "Sidor" }, { "bottom", "Botten" }, { "button.cancel", "Avbryt" }, { "button.ok", "OK" }, { "button.print", "Skriv ut" }, { "button.properties", "&Egenskaper..." }, { "c", "Engineering C" }, { "checkbox.collate", "&Sortera" }, { "checkbox.jobsheets", "F&örsättsblad" }, { "checkbox.printtofile", "Skriv ut till &fil" }, 
        { "d", "Engineering D" }, { "dialog.noprintermsg", "Hittade ingen utskriftstjänst." }, { "dialog.overwrite", "Denna fil finns redan.  Vill du skriva över den befintliga filen?" }, { "dialog.owtitle", "Skriv till fil" }, { "dialog.printtitle", "Skriv ut" }, { "dialog.printtofile", "Skriv till fil" }, { "dialog.pstitle", "Utskriftsformat" }, { "dialog.writeerror", "Kan inte skriva till filen:" }, { "e", "Engineering E" }, { "envelope", "Kuvert" }, 
        { "error.destination", "Ogiltigt filnamn. Försök igen." }, { "error.pagerange", "Ogiltigt sidintervall. Skriv in värdena igen (t ex 1-3,5,7-10)" }, { "executive", "Executive" }, { "folio", "Folio" }, { "invite-envelope", "Invitation-kuvert" }, { "invoice", "Invoice" }, { "iso-2a0", "2A0 (ISO/DIN & JIS)" }, { "iso-4a0", "4A0 (ISO/DIN & JIS)" }, { "iso-a0", "A0 (ISO/DIN & JIS)" }, { "iso-a1", "A1 (ISO/DIN & JIS)" }, 
        { "iso-a10", "A10 (ISO/DIN & JIS)" }, { "iso-a2", "A2 (ISO/DIN & JIS)" }, { "iso-a3", "A3 (ISO/DIN & JIS)" }, { "iso-a4", "A4 (ISO/DIN & JIS)" }, { "iso-a5", "A5 (ISO/DIN & JIS)" }, { "iso-a6", "A6 (ISO/DIN & JIS)" }, { "iso-a7", "A7 (ISO/DIN & JIS)" }, { "iso-a8", "A8 (ISO/DIN & JIS)" }, { "iso-a9", "A9 (ISO/DIN & JIS)" }, { "iso-b0", "B0 (ISO/DIN)" }, 
        { "iso-b1", "B1 (ISO/DIN)" }, { "iso-b10", "B10 (ISO/DIN)" }, { "iso-b2", "B2 (ISO/DIN)" }, { "iso-b3", "B3 (ISO/DIN)" }, { "iso-b4", "B4 (ISO/DIN)" }, { "iso-b5", "B5 (ISO/DIN)" }, { "iso-b6", "B6 (ISO/DIN)" }, { "iso-b7", "B7 (ISO/DIN)" }, { "iso-b8", "B8 (ISO/DIN)" }, { "iso-b9", "B9 (ISO/DIN)" }, 
        { "iso-c0", "C0 (ISO/DIN)" }, { "iso-c1", "C1 (ISO/DIN)" }, { "iso-c10", "C10 (ISO/DIN)" }, { "iso-c2", "C2 (ISO/DIN)" }, { "iso-c3", "C3 (ISO/DIN)" }, { "iso-c4", "C4 (ISO/DIN)" }, { "iso-c5", "C5 (ISO/DIN)" }, { "iso-c6", "C6 (ISO/DIN)" }, { "iso-c7", "C7 (ISO/DIN)" }, { "iso-c8", "C8 (ISO/DIN)" }, 
        { "iso-c9", "C9 (ISO/DIN)" }, { "iso-designated-long", "ISO Designated Long" }, { "italian-envelope", "Italienskt kuvert" }, { "italy-envelope", "Italienskt kuvert" }, { "japanese-postcard", "Postcard (JIS)" }, { "jis-b0", "B0 (JIS)" }, { "jis-b1", "B1 (JIS)" }, { "jis-b10", "B10 (JIS)" }, { "jis-b2", "B2 (JIS)" }, { "jis-b3", "B3 (JIS)" }, 
        { "jis-b4", "B4 (JIS)" }, { "jis-b5", "B5 (JIS)" }, { "jis-b6", "B6 (JIS)" }, { "jis-b7", "B7 (JIS)" }, { "jis-b8", "B8 (JIS)" }, { "jis-b9", "B9 (JIS)" }, { "label.bottommargin", "&nederkant" }, { "label.inches", "(tum)" }, { "label.info", "Info:" }, { "label.jobname", "&Utskrift:" }, 
        { "label.leftmargin", "v&änster" }, { "label.millimetres", "(mm)" }, { "label.numcopies", "Antal e&xemplar:" }, { "label.priority", "P&rioritet:" }, { "label.psname", "&Namn:" }, { "label.pstype", "Typ:" }, { "label.rangeto", "Till" }, { "label.rightmargin", "&höger" }, { "label.size", "Stor&lek:" }, { "label.source", "&Källa:" }, 
        { "label.status", "Status:" }, { "label.topmargin", "&överkant" }, { "label.username", "A&nvändarnamn:" }, { "large-capacity", "Hög kapacitet" }, { "ledger", "Ledger" }, { "main", "Huvud" }, { "manual", "Manuell" }, { "middle", "Mitten" }, { "monarch-envelope", "Monarch-kuvert" }, { "na-10x13-envelope", "10x15-kuvert" }, 
        { "na-10x14-envelope", "10x15-kuvert" }, { "na-10x15-envelope", "10x15-kuvert" }, { "na-5x7", "5x7-tumspapper" }, { "na-6x9-envelope", "6x9-kuvert" }, { "na-7x9-envelope", "6x7-kuvert" }, { "na-8x10", "8x10-tumspapper" }, { "na-9x11-envelope", "9x11-kuvert" }, { "na-9x12-envelope", "9x12-kuvert" }, { "na-legal", "Legal" }, { "na-letter", "Letter" }, 
        { "na-number-10-envelope", "No. 10-kuvert" }, { "na-number-11-envelope", "No. 11-kuvert" }, { "na-number-12-envelope", "No. 12-kuvert" }, { "na-number-14-envelope", "No. 14-kuvert" }, { "na-number-9-envelope", "No. 9-kuvert" }, { "not-accepting-jobs", "Accepterar inte jobb" }, { "oufuko-postcard", "Double Postcard (JIS)" }, { "personal-envelope", "Egen kuvertstorlek" }, { "quarto", "Quarto" }, { "radiobutton.color", "&Färg" }, 
        { "radiobutton.draftq", "Utka&st" }, { "radiobutton.duplex", "&Dubbelsidig" }, { "radiobutton.highq", "&Hög" }, { "radiobutton.landscape", "Liggan&de" }, { "radiobutton.monochrome", "&Monokrom" }, { "radiobutton.normalq", "&Normal" }, { "radiobutton.oneside", "&Ensidig" }, { "radiobutton.portrait", "&Stående" }, { "radiobutton.rangeall", "A&lla" }, { "radiobutton.rangepages", "Sid&or" }, 
        { "radiobutton.revlandscape", "Omvänt li&ggande" }, { "radiobutton.revportrait", "Omvänt ståen&de" }, { "radiobutton.tumble", "&Vänd" }, { "side", "Sida" }, { "tab.appearance", "Fo&rmat" }, { "tab.general", "&Allmänt" }, { "tab.pagesetup", "&Utskriftsformat" }, { "tabloid", "Tabloid" }, { "top", "Topp" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\print\resources\serviceui_sv.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */