package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui_pt_BR extends ListResourceBundle {
  protected final Object[][] getContents() { return new Object[][] { 
        { "Automatic-Feeder", "Alimentador Automático" }, { "Cassette", "Cassete" }, { "Form-Source", "Origem do Formulário" }, { "Large-Format", "Formato Grande" }, { "Manual-Envelope", "Envelope Manual" }, { "Small-Format", "Formato Pequeno" }, { "Tractor-Feeder", "Alimentador por Tracionador" }, { "a", "Engenharia A" }, { "accepting-jobs", "Aceitando jobs" }, { "auto-select", "Selecionar Automaticamente" }, 
        { "b", "Engenharia B" }, { "border.chromaticity", "Aparência da Cor" }, { "border.copies", "Cópias" }, { "border.jobattributes", "Atributos do Job" }, { "border.margins", "Margens" }, { "border.media", "Mídia" }, { "border.orientation", "Orientação" }, { "border.printrange", "Faixa de Impressão" }, { "border.printservice", "Serviço de Impressão" }, { "border.quality", "Qualidade" }, 
        { "border.sides", "Lados" }, { "bottom", "Inferior" }, { "button.cancel", "Cancelar" }, { "button.ok", "OK" }, { "button.print", "Imprimir" }, { "button.properties", "P&ropriedades..." }, { "c", "Engenharia C" }, { "checkbox.collate", "&Agrupar" }, { "checkbox.jobsheets", "Página com &Banner" }, { "checkbox.printtofile", "&Imprimir em Arquivo" }, 
        { "d", "Engenharia D" }, { "dialog.noprintermsg", "Nenhum serviço de impressão encontrado." }, { "dialog.overwrite", "Este arquivo já existe. Deseja substituir o arquivo existente?" }, { "dialog.owtitle", "Imprimir em Arquivo" }, { "dialog.printtitle", "Imprimir" }, { "dialog.printtofile", "Imprimir em Arquivo" }, { "dialog.pstitle", "Configuração da Página" }, { "dialog.writeerror", "Não é possível gravar no arquivo:" }, { "e", "Engenharia E" }, { "envelope", "Envelope" }, 
        { "error.destination", "Nome de arquivo inválido; tente novamente" }, { "error.pagerange", "Faixa de páginas inválida; insira novamente os valores (por exemplo, 1-3,5,7-10)" }, { "executive", "Executivo" }, { "folio", "Fólio" }, { "invite-envelope", "Envelope de Convite" }, { "invoice", "Fatura" }, { "iso-2a0", "2A0 (ISO/DIN & JIS)" }, { "iso-4a0", "4A0 (ISO/DIN & JIS)" }, { "iso-a0", "A0 (ISO/DIN & JIS)" }, { "iso-a1", "A1 (ISO/DIN & JIS)" }, 
        { "iso-a10", "A10 (ISO/DIN & JIS)" }, { "iso-a2", "A2 (ISO/DIN & JIS)" }, { "iso-a3", "A3 (ISO/DIN & JIS)" }, { "iso-a4", "A4 (ISO/DIN & JIS)" }, { "iso-a5", "A5 (ISO/DIN & JIS)" }, { "iso-a6", "A6 (ISO/DIN & JIS)" }, { "iso-a7", "A7 (ISO/DIN & JIS)" }, { "iso-a8", "A8 (ISO/DIN & JIS)" }, { "iso-a9", "A9 (ISO/DIN & JIS)" }, { "iso-b0", "B0 (ISO/DIN)" }, 
        { "iso-b1", "B1 (ISO/DIN)" }, { "iso-b10", "B10 (ISO/DIN)" }, { "iso-b2", "B2 (ISO/DIN)" }, { "iso-b3", "B3 (ISO/DIN)" }, { "iso-b4", "B4 (ISO/DIN)" }, { "iso-b5", "B5 (ISO/DIN)" }, { "iso-b6", "B6 (ISO/DIN)" }, { "iso-b7", "B7 (ISO/DIN)" }, { "iso-b8", "B8 (ISO/DIN)" }, { "iso-b9", "B9 (ISO/DIN)" }, 
        { "iso-c0", "C0 (ISO/DIN)" }, { "iso-c1", "C1 (ISO/DIN)" }, { "iso-c10", "C10 (ISO/DIN)" }, { "iso-c2", "C2 (ISO/DIN)" }, { "iso-c3", "C3 (ISO/DIN)" }, { "iso-c4", "C4 (ISO/DIN)" }, { "iso-c5", "C5 (ISO/DIN)" }, { "iso-c6", "C6 (ISO/DIN)" }, { "iso-c7", "C7 (ISO/DIN)" }, { "iso-c8", "C8 (ISO/DIN)" }, 
        { "iso-c9", "C9 (ISO/DIN)" }, { "iso-designated-long", "Longo Designado ISO" }, { "italian-envelope", "Envelope Italiano" }, { "italy-envelope", "Envelope Italiano" }, { "japanese-postcard", "Cartão Postal (JIS)" }, { "jis-b0", "B0 (JIS)" }, { "jis-b1", "B1 (JIS)" }, { "jis-b10", "B10 (JIS)" }, { "jis-b2", "B2 (JIS)" }, { "jis-b3", "B3 (JIS)" }, 
        { "jis-b4", "B4 (JIS)" }, { "jis-b5", "B5 (JIS)" }, { "jis-b6", "B6 (JIS)" }, { "jis-b7", "B7 (JIS)" }, { "jis-b8", "B8 (JIS)" }, { "jis-b9", "B9 (JIS)" }, { "label.bottommargin", "&inferior" }, { "label.inches", "(pol)" }, { "label.info", "Informações:" }, { "label.jobname", "Nome do &Job:" }, 
        { "label.leftmargin", "es&querda:" }, { "label.millimetres", "(mm)" }, { "label.numcopies", "Númer&o de cópias:" }, { "label.priority", "Pri&oridade:" }, { "label.psname", "&Nome:" }, { "label.pstype", "Tipo:" }, { "label.rangeto", "Até" }, { "label.rightmargin", "&direita" }, { "label.size", "Ta&manho:" }, { "label.source", "&Origem:" }, 
        { "label.status", "Status:" }, { "label.topmargin", "&superior" }, { "label.username", "Nome do &Usuário:" }, { "large-capacity", "Grande Capacidade" }, { "ledger", "Duplo Carta" }, { "main", "Principal" }, { "manual", "Manual" }, { "middle", "Meio" }, { "monarch-envelope", "Envelope Monarca" }, { "na-10x13-envelope", "Envelope 10x15" }, 
        { "na-10x14-envelope", "Envelope 10x15" }, { "na-10x15-envelope", "Envelope 10x15" }, { "na-5x7", "Papel 5\" x 7\"" }, { "na-6x9-envelope", "Envelope 6x9" }, { "na-7x9-envelope", "Envelope 6x7" }, { "na-8x10", "Papel 8\" x 10\"" }, { "na-9x11-envelope", "Envelope 9x11" }, { "na-9x12-envelope", "Envelope 9x12" }, { "na-legal", "Ofício" }, { "na-letter", "Carta" }, 
        { "na-number-10-envelope", "Envelope nº 10" }, { "na-number-11-envelope", "Envelope nº 11" }, { "na-number-12-envelope", "Envelope nº 12" }, { "na-number-14-envelope", "Envelope nº 14" }, { "na-number-9-envelope", "Envelope nº 9" }, { "not-accepting-jobs", "Não aceitando jobs" }, { "oufuko-postcard", "Cartão Postal Duplo (JIS)" }, { "personal-envelope", "Envelope Personalizado" }, { "quarto", "Quarto" }, { "radiobutton.color", "&Cor" }, 
        { "radiobutton.draftq", "Rascun&ho" }, { "radiobutton.duplex", "Duple&x" }, { "radiobutton.highq", "A&lta" }, { "radiobutton.landscape", "&Paisagem" }, { "radiobutton.monochrome", "&Monocromático" }, { "radiobutton.normalq", "&Normal" }, { "radiobutton.oneside", "Um La&do" }, { "radiobutton.portrait", "Re&trato" }, { "radiobutton.rangeall", "T&udo" }, { "radiobutton.rangepages", "&Páginas" }, 
        { "radiobutton.revlandscape", "Paisagem I&nvertida" }, { "radiobutton.revportrait", "Retrato In&vertido" }, { "radiobutton.tumble", "&Virar" }, { "side", "Lado" }, { "tab.appearance", "Apa&rência" }, { "tab.general", "&Geral" }, { "tab.pagesetup", "Con&figuração da Página" }, { "tabloid", "Tablóide" }, { "top", "Superior" } }; }
}


/* Location:              D:\software\jd-gui\jd-gui-windows-1.6.3\rt.jar!\sun\print\resources\serviceui_pt_BR.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.0.7
 */